### ISSUE TITLE
shutil.make_archive does not work with pyfakefs

### ISSUE THREAD

**Issue by borismod** [jmcgeheeiv/pyfakefs#104]
Hi, guys

It's me again with ZIP issues. I started using shutil.make_archive and it seems that it does not work with fakefs. 

Any idea how it can be fixed?

```Python
import shutil
import unittest
from pyfakefs import fake_filesystem_unittest


class TestPackageBuilder(fake_filesystem_unittest.TestCase):
    def setUp(self):
        self.setUpPyfakefs()

    def test_zip(self):
        self.fs.CreateFile(u'c:\\test\\readme.txt', contents='')

        shutil.make_archive(u'c:\\test\\some_file.zip', 'zip', u'c:\\test')

        self.assertFileExists(u'c:\\test\\some_file.zip')

    def assertFileExists(self, file_path):
        self.assertTrue(os.path.exists(file_path), msg='File {0} does not exist'.format(file_path))

```

Fails with the following error:

> Error
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
  File "C:\work\GitHub\shellfoundry\tests\test_package_builder.py", line 32, in test_zip
  File "C:\Python27\lib\shutil.py", line 527, in make_archive
WindowsError: [Error 2] The system cannot find the file specified: u'c:\\test'

**Comment by mrbean-bremen** [comment]
Seems like you are out of luck here - shutil.make_archive() is not implemented in fakefs (yet), and I don't see any workaround at the moment other than using zipfile directly.

**Comment by borismod** [comment]
@mrbean-bremen should I open an issue to shutil maintainers?

**Comment by mrbean-bremen** [comment]
No, this is an issue with pyfakefs, so this is already  the right place for the issue.

**Comment by mrbean-bremen** [comment]
No, this is an issue with pyfakefs, so this is already  the right place for the issue. 
Disclaimer: I'm just a user of pyfakefs, so don't rely on my judgment :)

**Comment by mrbean-bremen** [comment]
I just had another look at this, and the reason why it does not work is the usage of the real os module inside shutil.py. If removing 'shutil' from SKIPNAMES, it will work (if also removing the unneeded .zip extension from the filename in the above test code).
I see no immediate problem with this, as shutil is kind of a derived module and IMO it makes sense to stub out os inside this module, but there may be side effects I'm not aware of. @jmcgeheeiv: can you comment on this? I think you wrote all the unit test code. 
Maybe SKIPNAMES shall be configurable for different needs, as there seem to be other related issues?

**Comment by jmcgeheeiv** [comment]
Closing since @mrbean-bremen removed shutil from SKIPNAMES.
