### ISSUE TITLE
posixpath, genericpath in SKIPNAMES

### ISSUE THREAD

**Issue by benureau** [jmcgeheeiv/pyfakefs#106]
See: https://github.com/humm/pyfakefs/commit/3fe0eacd007eb323a6eebf2955e8d95f50cef410

Without this, I can't use methods like `real_os.path.isdir` after `setUp()` in a `fake_filesystem_unittest.TestCase` object.

**Comment by jmcgeheeiv** [comment]
Closing since @mrbean-bremen removed shutil from SKIPNAMES.
