### ISSUE TITLE
Add support for glob.glob recursive flag

### ISSUE THREAD

**Issue by matteosimone** [jmcgeheeiv/pyfakefs#116]
python3.5 added support for a recursive flag for glob.glob. It would be great if this was supported by this library.

**Comment by mrbean-bremen** [comment]
IMHO, faking glob is not needed at all (see my comment in issue #59).
I created a branch where glob is not faked out (https://github.com/mrbean-bremen/pyfakefs/tree/no_fake_glob) - if you want, you can check it out and play around, it should fix the issue.

**Comment by mrbean-bremen** [comment]
Fixed via #124.
