### ISSUE TITLE
fake_pathlib's resolve() does not reproduce error when path has file ancestor

### ISSUE THREAD

**Issue by romanlevin** [jmcgeheeiv/pyfakefs#139]
Under Python 3.6:

```python
>>> p = pathlib.Path('/path/to/file/this can not exist')
>>> p.resolve()
Traceback (most recent call last):
  ...
NotADirectoryError: [Errno 20] Not a directory: '/path/to/file/this can not exist'
```

`pyfakefs.fake_pathlib.FakePath.resolve()` does not raise an exception.

**Comment by mrbean-bremen** [comment]
Thanks for the report - you may be the first user of fake_pathlib so far, so we are certainly happy to get any feedback. I will have a look into this.

**Comment by mrbean-bremen** [comment]
I just added some fixes - please check if this solves your problem.
Note that you have to use the latest Python 3.6 beta (beta 4), as resolve() has got an additional `strict` argument, and the default behavior has changed (e.g. it does not throw with your example code).

**Comment by romanlevin** [comment]
@mrbean-bremen Thanks for pointing out this change in 3.6.0b4. It's not very well documented and would have taken me a while to find otherwise.

**Comment by romanlevin** [comment]
Verified that issue is solved on Python 3.6.0b4 with e3449bf.

**Comment by mrbean-bremen** [comment]
Well, we have to check again after the final version gets out - there always may be some changes. Though I don't really expect any, as the final version shall be out in another 2 weeks.

**Comment by romanlevin** [comment]
Yeah. although I wouldn't have expected this kind of compatibility-breaking change between beta releases, either.

**Comment by mrbean-bremen** [comment]
http://bugs.python.org/issue19717#msg280432
