### ISSUE TITLE
unable to open() files with mode="xb"

### ISSUE THREAD

**Issue by FelixSchwarz** [jmcgeheeiv/pyfakefs#147]
Python 3.5.2 (default, Sep 14 2016, 11:28:32) 
    [GCC 6.2.1 20160901 (Red Hat 6.2.1-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyfakefs.fake_filesystem_unittest import Patcher
    >>> stubber = Patcher()
    >>> stubber.setUp()
    >>> fp = open('foo.txt', 'xb')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "…/pyfakefs/fake_filesystem.py", line 3416, in __call__
        return self.Call(*args, **kwargs)
      File "…/pyfakefs/fake_filesystem.py", line 3459, in Call
        raise ValueError('Invalid mode: %r' % orig_modes)
    ValueError: Invalid mode: 'xb'

**Comment by mrbean-bremen** [comment]
@FelixSchwarz - please check if this fixes your problem.

**Comment by FelixSchwarz** [comment]
Yes, this works for me. Thank you very much!

**Comment by mrbean-bremen** [comment]
Thanks for the report!
