### ISSUE TITLE
publish pyfakefs 2.10?

### ISSUE THREAD

**Issue by FelixSchwarz** [jmcgeheeiv/pyfakefs#150]
I'd like to ask for a 2.10 release as the current git contains two features I rely on ("x" mode for open() and unsorted os.listdir results).

Release early, release often :-)

**Comment by jmcgeheeiv** [comment]
Yes, we have been talking about a release.  @mrbean-bremen, are we in a good state for this?  As I recall we were going to call it version 3.0.

**Comment by mrbean-bremen** [comment]
Yes, I think so. There is already a release branch there ready to be merged (actually it has only the version and the release notes updated - you may check if you want some changes in the readme). 
Also (I may have mentioned this) - make sure you have pypandoc installed before you register the version in pypi. In this case the pypi description is taken from README.MD (converted to rst).

**Comment by mrbean-bremen** [comment]
Besides - releases are cheap, and I'm with @FelixSchwarz here: release early, release often. So, please go ahead!

**Comment by jmcgeheeiv** [comment]
pyfakefs 3.0 released.  @FelixSchwarz and @mrbean-bremen, please scrutinize and close this issue if you are satisfied.

**Comment by mrbean-bremen** [comment]
Thanks, looks good for me!

**Comment by mrbean-bremen** [comment]
Closing as the release is out and contains the needed features.
