### ISSUE TITLE
FakeDirectory could use OrderedDict for contents?

### ISSUE THREAD

**Issue by FelixSchwarz** [jmcgeheeiv/pyfakefs#151]
For some tests I like to ensure that os.listdir returns the directory contents in a certain order (to check if my code actually sorts returned items). Currently `FakeDirectory` uses `{}` which also does not guarantee any ordering so my tests often work - but not always.

My workaround is to replace `.byte_contents` with an `OrderedDict` manually so items would be returned in the order of insertion. Is that something you could add to PyFakeFS directly?

**Comment by mrbean-bremen** [comment]
I wouldn't want to replace that in this way, because that would introduce an artificial order to the os.listdir() fake implementation, which may lead to tests incorrectly succeeding that rely on that order. Would it be sufficient if we added an additional property  (something like ordered_contents) to FakeDirectory?

**Comment by FelixSchwarz** [comment]
Sure, basically I would like to have _some_ mechanism to return a certain order without introducing flaky tests.

**Comment by mrbean-bremen** [comment]
Ok, I can add this, maybe in the evening if I get the time (can't promise).

**Comment by mrbean-bremen** [comment]
@FelixSchwarz - please check if this is sufficient for you.

**Comment by FelixSchwarz** [comment]
well, it looks like a start but ultimately I want that os.listdir would return the items in a way I can specify (using .ordered_dirs would be ok for that).

**Comment by mrbean-bremen** [comment]
If I understand correctly, you want that the faked os.listdir behaves different from the real implementation? Possibly by setting some parameter in the fake file system?

**Comment by mrbean-bremen** [comment]
Maybe we add an additional argument to `fake_filesystem.ListDir`, and you replace the `FakeOsModule.listdir`with the respective implementation in your test? I don't like the idea of introducing a global file system property for that purpose...

**Comment by jannero** [comment]
@FelixSchwarz couldn't you just patch os.listdir with mock.Mock(return_value=list_you_have_ordered)?

So something like this:

```
def test_ordering(self):
    with mock.patch('os.listdir', return_value=['a', 'd', 'b']):
        self.assertEqual(obj.get(), ['a', 'b', 'd'])
```

**Comment by mrbean-bremen** [comment]
@FelixSchwarz: I agree with @jannero - and by what I understand from your use case, I don't see the need of a new pyfakefs feature for your purpose. Depending on your need, you could also make sure that the sort function is called with the correct arguments by mocking it. What do you think?

**Comment by FelixSchwarz** [comment]
sorry for replying that late: I agree that my use case doesn't justify adding a lot of complicated API. My initial idea was to do something which did add any API at all (and I generally try to avoid undefined behavior if possible). However this is really just a minor concern, I can easily work around that so feel free to just close this as "won't fix" :-)

**Comment by mrbean-bremen** [comment]
As suggested, closing as won't fix. Thanks :)
