### ISSUE TITLE
Directory operand dot-dot breaks CreateFile and CreateDirectory

### ISSUE THREAD

**Issue by rtmcached** [jmcgeheeiv/pyfakefs#152]
When using `CreateFile` or `CreateDirectory` with `file_path` containing `..` the file/directory is not created. That can be reproduced by running
```py
import os

from pyfakefs import fake_filesystem_unittest


class TestExample(fake_filesystem_unittest.TestCase):

    def setUp(self):
        self.setUpPyfakefs()

    def tearDown(self):
        pass

    def test_createfile(self):
        root = os.path.dirname(os.path.realpath(__file__))
        filename = os.path.join(root, '..', 'file.txt')
        self.fs.CreateFile(filename, contents='whatevs')
        self.assertTrue(os.path.exists(filename))
```
Is this behaviour intentional?

**Comment by mrbean-bremen** [comment]
I don't think so - I guess nobody used it that way so far.

**Comment by mrbean-bremen** [comment]
On the second thought, your test code may not do what you intend to do: using `__file__` refers to the  real source file that does not exist in the fake file system, and using paths relative to non-existent directories will not work. Please check if this is your problem.

**Comment by rtmcached** [comment]
Yes you are right, using paths relative to non-existent directories will not work. Although in theory it seems easy (when you find `..` in the path - remove it together with the previous dir in that path), probably `pyfakefs` has different specs/requirements/restrictions on that subject. 

I resolved my issue by doing `self.fs.CreateDirectory(root)`, in order for `self.fs.CreateFile(filename, contents='whatevs')` to use a path relative to an already existent directory.

Thanks!
