### ISSUE TITLE
get an Name Error with a simple pytest test

### ISSUE THREAD

**Issue by hwmrocker** [jmcgeheeiv/pyfakefs#173]
Given this test from your example:
```
def test_write(fs):
    fs.CreateFile('/var/data/xx1.txt')
    assert os.path.exists('/var/data/xx1.txt')
```
I get this error:
```
E   NameError: global name 'os' is not defined
```
When I import os in my test i get around this error, but the file that uses os should import it, or the documentaion should be improved.

**Comment by jmcgeheeiv** [comment]
I looked around but could not find "test_write".  Where did you find this example?

Once I find it, if I were to add,
```python
import os
```
to the example, would that be satisfactory?

**Comment by hwmrocker** [comment]
oh sorry, i changed the function name it was  the example from the readme:
```
def my_fakefs_test(fs):
    # "fs" is the reference to the fake file system
    fs.CreateFile('/var/data/xx1.txt')
    assert os.path.exists('/var/data/xx1.txt')
```
but it feels kinda odd to import os in a file where you don't use it.

**Comment by mrbean-bremen** [comment]
well, you do use it (`assert os.path.exists()`)

**Comment by hwmrocker** [comment]
😊 oh no,
you have point m)

**Comment by jmcgeheeiv** [comment]
You're so funny.  Let us know if you find anything else.
