### ISSUE TITLE
Question on requirements (distribution packaging)

### ISSUE THREAD

**Issue by dmsimard** [jmcgeheeiv/pyfakefs#179]
Hi,

I'm working on packaging pyfakefs for Fedora and CentOS (EPEL) right now.

The requirements are very static currently:

    mox3==0.10.0
    pytest==2.8.0
    wheel==0.26.0

Is there a possibility of testing minimum and maximum versions and modifying the requirements accordingly ?
[mox3 is up to 0.21.0](https://pypi.python.org/pypi/mox3) now, [pytest up to 3.0.7](https://pypi.python.org/pypi/pytest) and [wheel 0.30](https://pypi.python.org/pypi/wheel).

We have varying versions available in RHEL-based derivatives of those already but I'm mostly interested if, for example, there are known bad versions.
Perhaps this could work ? Just an example.

    mox3>=0.10.0
    pytest>=2.8.0,<3.0.0
    wheel>=0.26.0

Otherwise, there's been 30+ commits since the last tagged release, maybe we could tag a new release if we choose to adjust the requirements.

Thanks a lot for this library, it's saved my life :)

**Comment by jmcgeheeiv** [comment]
Well, it looks like we've hit the big time now.

I added the mox3 dependency, and I think that your suggestion of `mox3>=0.10.0` should work just fine.

@mrbean-bremen, do you know about pytest or wheel?

**Comment by mrbean-bremen** [comment]
There was a problem with pytest < 2.8.6 with pyfakefs and doctest, so I think `pytest>=2.8.6` would be better (@jmcgeheeiv - I just noticed that the README also mentions 2.8.0 instead of 2.8.6).  
I don't know where the wheel dependency is coming from - isn't it only needed for packaging?

**Comment by mrbean-bremen** [comment]
Ah, and this has been tested with pytest 3, so `pytest<3.0.0` won't be needed IMHO.

**Comment by dmsimard** [comment]
Wheel comes from this [commit](https://github.com/jmcgeheeiv/pyfakefs/commit/7574281e7d5a26930e965f9c957fae91b8b72cb0) and it doesn't really seem [used](https://github.com/jmcgeheeiv/pyfakefs/search?utf8=✓&q=wheel&type=) throughout the project.

**Comment by mrbean-bremen** [comment]
It actually comes from this earlier [commit](https://github.com/jmcgeheeiv/pyfakefs/commit/adf51f781587fe02144c07ba402a908e88a073ee) - @jmcgeheeiv, can you please check if this is really needed?

**Comment by mrbean-bremen** [comment]
About mox3 - I have been using version 0.18.0 before, and just did a quick test with 0.21.0, which works without problems. So no problems expected here with the changed requirements.

**Comment by dmsimard** [comment]
FWIW I've done a RPM build without wheel and it works for me (quick sanity check):
http://paste.openstack.org/raw/608542/

It pulled mox3 0.17 and pytest 3.0.7 which are the latest available on Fedora right now.

**Comment by mrbean-bremen** [comment]
Ah well, this should be sufficient then - thanks!
@jmcgeheeiv - will you make a new release with the changed requirements, so that we have a consistent version, and Fedora gets the latest and greatest pyfakefs? ;)

**Comment by dmsimard** [comment]
I'll submit the package to Fedora with 3.1, we can update to 3.2 when it comes out -- it's not a problem. Thanks for your help !

**Comment by mrbean-bremen** [comment]
Thanks for your work!

**Comment by jmcgeheeiv** [comment]
I added the wheel requirement.  However, I added it rather naively.  I mildly recall that it was needed, but maybe not.  I would trust your empirical experience over my recollection of the past.

So, can we get a clear spec for the requirements?  I will go and update that 2.8.0 typo in the README right now.

**Comment by mrbean-bremen** [comment]
Yes - I think we can go with that  (see my comment above for the requirements I consider ok).

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - I just did a quick test using mock instead of mox3, and it seems to work fine, but for Python 2 this means a dependency on the mock package (for Python 3 it's built in).
Is there any reason to prefer mox3 over mock or vice verse? I checked the 2 issues with mock you had in #48, and one was a simple bug (#48), and the other one (#43) was unrelated.

**Comment by jmcgeheeiv** [comment]
Actually the killer problem was something else.  I entered an issue especially for pyfakefs, but I now cannot findl it.  However, [this mock issue](https://code.google.com/archive/p/mock/issues/250) describes the same problem.

@mrbean-bremen, how did you do your quick test?

**Comment by mrbean-bremen** [comment]
Mostly I just used your changes you did then. I have to admit that I ran only the tests in all_tests - just noticed that the pytest plugin test fails for Python 3. I will make a branch with the changes.

**Comment by mrbean-bremen** [comment]
https://github.com/mrbean-bremen/pyfakefs/commits/use-mock
Strangely enough, the pytest plugin test fails for all Python 3 versions except Python 3.5.
I may have a look at this tomorrow - just out of interest.

**Comment by dmsimard** [comment]
For what it's worth, I'm from the OpenStack community which maintains mox3 ( https://github.com/openstack/mox3 ) and they are looking to drop support for it and replace it by Mock right now.

It is one of the goals for the current development cycle:
![image](http://i.imgur.com/TtEEGPe.png)

It would probably be better if you could move away from Mox3 in favor of Mock.

**Comment by mrbean-bremen** [comment]
I created a new issue (#182) for the mox3 replacement. 
@dmsimard - you may close the current issue if you are done.

**Comment by dmsimard** [comment]
Yup, the requirements are now up to date with a proper minimum version.
Can you tag a new release once mock is replaced ?

**Comment by mrbean-bremen** [comment]
Sure!
