### ISSUE TITLE
Cannot use pyfakefs together with lxml

### ISSUE THREAD

**Issue by OskarPersson** [jmcgeheeiv/pyfakefs#180]
import os
    import unittest
    from lxml import etree
    from pyfakefs import fake_filesystem_unittest
    
    class TestExample(fake_filesystem_unittest.TestCase):
        def setUp(self):
            self.setUpPyfakefs()
    
        def test_lxml(self):
            os.mkdir('/test')
    
            root = etree.Element("root")
            tree = etree.ElementTree(root)
            tree.write('/test/file.xml')
    
    if __name__ == "__main__":
        unittest.main()

When running the example above I get this error:

    Traceback (most recent call last):
      File "example_test.py", line 25, in test_lxml
      File "src/lxml/lxml.etree.pyx", line 2033, in lxml.etree._ElementTree.write (src/lxml/lx
    ml.etree.c:63707)
      File "src/lxml/serializer.pxi", line 512, in lxml.etree._tofilelike (src/lxml/lxml.etree
    .c:134950)
      File "src/lxml/serializer.pxi", line 571, in lxml.etree._create_output_buffer (src/lxml/
    lxml.etree.c:135614)
      File "src/lxml/serializer.pxi", line 560, in lxml.etree._create_output_buffer (src/lxml/
    lxml.etree.c:135415)
    IOError: [Errno 2] No such file or directory

---

I am using lxml 3.6.4 and pyfakefs 3.1 in Python 2.7.13 on macOS 10.12.4
([Question on Stackoverflow](http://stackoverflow.com/questions/43606500))

**Comment by mrbean-bremen** [comment]
I can reproduce the problem locally, and as of now, I have no solution. 
I did not get to the root cause - I haven't seen this kind of code (C code generated from Python code and then compiled), so I guess I have to understand how that works first. Obviously, patching in lxml does not work (or works incompletely) for some reason, so that the xml file is written into the real file system (can be seen if the `test` directory is created in the real fs).
@jmcgeheeiv - any ideas?

**Comment by mrbean-bremen** [comment]
Just saw the answer on stackoverflow (using `xml.etree.ElementTree` works - as expected with a pure Python package). If you can afford the performance hit, this would be a workaround for the time being.

**Comment by jmcgeheeiv** [comment]
lxml is a fine library, but pyfakefs is not going to be able to patch the C libraries underlying lxml to make them use the fake filesystem.

Please leave this open while I add a disclaimer to README explaining that only pure Python libraries can access the file system.

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - you are right of course, my bad. I probably got confused by the original code written in Python (didn't know about Cython).

**Comment by jmcgeheeiv** [comment]
I added this to README.md:

> pyfakefs will not work with Python libraries that use C libraries to access the file system. This is because pyfakefs cannot patch the underlying C libraries' file access functions--the C libraries will always access the real file system. For example, pyfakefs will not work with lxml. In this case lxml must be replaced with a pure Python alternative such as xml.etree.ElementTree.

Do you think this is clear enough?

**Comment by jmcgeheeiv** [comment]
@mrbean-bremen, is there somewhere else this documentation must be added?

**Comment by mrbean-bremen** [comment]
This is very clear to me. And I think the README is sufficient, as it also shows up in PyPi.
I may add it in the introduction of the auto documentation though, as that is an excerpt of README.md.
