### ISSUE TITLE
Pyfakefs usage scenarios

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#189]
This is more of a discussion point than an issue, and also for a later release.

I wonder if there is really the need to use pyfakefs via mock (the third scenario), given that you always can use `Patcher` directly if not using `unittest` or `pytest`. From what I have seen from contributors so far, none of them seems to be using the `mock` scenario. 

Anyway, I doubt the usefulness of mocking `glob`, `tempfile` or `shutil` separately, but maybe I'm wrong here. On the other hand, if removing that scenario for these modules, `fake_filesystem_glob` and probably `fake_tempfile` (which is implemented incompletely anyway) can be removed, and most from `fake_filesystem_shutil` implementation also (though this needs some additions in FakeOsModule).

Edit: I moved some of the points into separate issues that can be implemented independently  (#191, #192, #193 and #194).

What remains for this issue:
- adapt the documentation (replace `mock` scenario with `Patcher` scenario)
- remove fake `glob` and `tempfile` implementation

**Comment by jmcgeheeiv** [comment]
Thank you for thinking so deeply about this.

I generally understand and agree.  Could I ask you to separate these into two or three paragraphs or perhaps even separate issues?  Also, please specify "one" in "...none seems to be using that one."

**Comment by mrbean-bremen** [comment]
Okay, I created a few more issues that can be handled separately.

Do you think this is something for the next release?  And thanks for the 3.2 release, by the way - you have done a lot of documentation cleanup, I liked that.

**Comment by jmcgeheeiv** [comment]
Sure, this is an excellent target for 3.3.

**Comment by mrbean-bremen** [comment]
Great! 

Note I won't have access to a computer for a couple of weeks - I will finish the nanosecond time related issues afterwards.

**Comment by jmcgeheeiv** [comment]
Bon voyage.

**Comment by mrbean-bremen** [comment]
Thanks, having that!

**Comment by mrbean-bremen** [comment]
Remaining task: adapt README.MD.

**Comment by mrbean-bremen** [comment]
All done - closing. 
@jmcgeheeiv - when you will be available again, you may prepare a 3.3 release. The bugs coming from TSTL are ongoing stuff, but nothing really important for the release, I think. I think the next major change would be to pep8tify the API.
