### ISSUE TITLE
Remove tempfile from Patcher

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#191]
The `tempfile` module seems not to depend on any low level file system code - It uses the modules `os`, `io` and `shutil` directly. For that reason, it can safely be removed from `Patcher`.

This ensures that the correct implementation of `tempfile` is used without the need for a fake implementation, if using `Patcher`.

See #189.

**Comment by jmcgeheeiv** [comment]
＃ｙ

**Comment by jmcgeheeiv** [comment]
I presume you mean "...safely removed from `Patcher.SKIPNAMES`"?

Masterful.

**Comment by mrbean-bremen** [comment]
No, I mean remove it completely, like I did with `glob` (provided I didn't overlook something).

**Comment by jmcgeheeiv** [comment]
Yes, of course you would also remove the module itself.
