### ISSUE TITLE
Remove unneeded implementations from fake shutil

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#194]
This one depends on the implementation of #189, #192  and #193.
Most of the implementation of `shutil` depends only on `os` functionality that is already faked out and can be safely removed.

**Comment by jmcgeheeiv** [comment]
I see.  You are saying that we can let `Patcher` go inside `shutil` and stub out all the references to `os` and other faked modules.  Correct?

**Comment by mrbean-bremen** [comment]
Yes, this is actually what we are already doing, since I removed `shutil` from `SKIPNAMES`. This is how `shutil.make_archive` and other functions work. I'm just saying that we can remove more of the fake implementation  (most of it, actually).

**Comment by jmcgeheeiv** [comment]
An excellent discovery.

When you remove the fake functionality, you will remove tests as well, but please leave one or two tests as canaries.

For example, leave the test for `shutil.copyfile()`.  You will have removed the fake `shutil.copyfile()`,  so the test will exercise the real `shutil.copyfile()`.  If the real `shutil.copyfile()` passes the test, we can assume that the rest of the real `shutil` is properly exposed and not patched.
