### ISSUE TITLE
pyfakefs clashes with faker and hypothesis

### ISSUE THREAD

**Issue by thedrow** [jmcgeheeiv/pyfakefs#197]
Both of these libraries are commonly used while testing and they use the filesystem.
How do I use pyfakefs with faker or hypothesis?
Is there a way to specify that only subsets of the filesystem are faked?

**Comment by mrbean-bremen** [comment]
About faker - as far as I remember it creates the test data in memory (don't have access to a computer now apart from my smartphone, so this is just out of my head), and saving it to disk is your responsibility. If this is so, I see 2 ways to make it work with pyfakefs: 
- if you write the test data before the test, you can use `add_real_file()` or `add_real_directory()` to add this data to the fake file system 
- if you create the data during the test, you can write it to disk using `os.write` or similar, which will write it to the fake file system 

I'm not sure how hypothesis accesses the file system, but you may basically use the same approach. The first approach will work as long as you don't add additional data to a directory after it has been added via `add_real_directory` and accessed from the test.

**Comment by jmcgeheeiv** [comment]
*How do I use pyfakefs with faker or hypothesis?*

I think we need you to tell us how you want pyfakefs to work with faker and hypothesis.  We can control what pyfakefs patches using the `fake_filesystem_unittest.TestCase(additional_skip_names)` argument.  If we can determine that, say, `faker` should be permanently skipped, we can add ii to the default `fake_filesystem_unittest.Patcher.SKIP_NAMES`.

*Is there a way to specify that only subsets of the filesystem are faked?*

@mrbean-bremen answered this question.

**Comment by thedrow** [comment]
Faker has files in site-packages that it uses in order to generate locale-based values. I need to figure out where faker is installed and load the directory to pyfakefs.
Hypothesis uses the '.hypothesis' folder for storing and fetching generated tests. The folder is located on the root of the project.
I'm not sure about this but I think that pyfakefs should be able to automatically infer that these files/folders shouldn't be faked.

**Comment by mrbean-bremen** [comment]
To get the install location of a module you can use `modulename.__file__` and go from there (I do it that way for other packages to work with `pyfakefs`). 

I don't think it would be a good idea to add specific support for all packages that could potentially be used by `pyfakefs` - that would be a maintenance nightmare, and introduce unnecessary dependencies. 
Doing it generically would mean something like detecting all imported modules and adding their install paths to the fake file system - not sure if this is a good idea, either, but I may think about this later. Your best bet is just to add these 2 directories to the fake for and check if that works.

**Comment by jmcgeheeiv** [comment]
@mrbean-bremen, Yes, I suggested permanent additons to `Patcher.SKIP_NAMES` with some trepedation.

@thedrow, it looks like `add_read_directory()` is what you need.  After you figure this out, a wiki article, *Using pyfakefs with faker and hypotheses* sure would be a nice addition.

**Comment by mrbean-bremen** [comment]
@thedrow - did this work for you?

**Comment by thedrow** [comment]
I'm going to check later on.

**Comment by mrbean-bremen** [comment]
@thedrow - I'm closing this as answered, feel free to reopen if you get back to this.
