### ISSUE TITLE
Class with py.path?

### ISSUE THREAD

**Issue by papadeltasierra** [jmcgeheeiv/pyfakefs#198]
Is, or was since I'm using Python 2.7, there a class between pyfakefs and py.path?  I'm seeing a number of strange errors trying to pyfakefs to test some code that I inherited and it almost looks like some existing libraries are attempting to go and load sub-modules 'on the fly' but this is failing because the file system has been faked.  The common feature is a stack which includes:

```
c:\virtualenv\pytest\lib\site-packages\_pytest\assertion\rewrite.py:97: in find_module
    fn_pypath = py.path.local(fn)
c:\virtualenv\pytest\lib\site-packages\pyfakefs\fake_filesystem.py:2489: in __getattr__
    return getattr(self._os_path, name)
E   AttributeError: 'module' object has no attribute 'local'
==================== 1 failed, 1 warnings in 0.33 seconds =====================
```

I'll see if I can repro this with a simplish script but I thought I'd ask in case this is a known, and hopefully solved, issue.

**Comment by jmcgeheeiv** [comment]
I do not really know what you mean by "a class between pyfakefs and py.path."

I have experience importing modules on the fly, and it worked.  I do have reservations however, because I recall that I was quite surprised that it did work.

A test case would be most helpful.  Also, it seems that you are reporting two problems.  If so, please create another issue so we can address them independently.

**Comment by mrbean-bremen** [comment]
This looks like `pyfakefs` is faking out `py.path` as `os.path`. This may happen if for example `path` is imported like `from py import path`. If this is indeed the problem, I see two possibilities to fix this:
- change the import to something like `import py.path`
- if you are using `pyfakefs.TestCase` or `pyfakefs.Patcher`, add the argument `patch_path=False` to `Testcase` or `Patcher` initialization

**Comment by papadeltasierra** [comment]
jmcgeheeiv - Sorry, stubby fingers, I meant 'clash' not class'.  mrbean-bremen, thanks for the suggestions - off to read up and see what I can do.

**Comment by papadeltasierra** [comment]
OK, mrbeam-bremen's suggestion worked a treat.  As far as I can tell, the 'import as path' is not in the code I'm working with so appears to be in some of the standard packages.  But things are progressing so I'm closing the issue.  Thanks for the help.

**Comment by jmcgeheeiv** [comment]
Well done.
