### ISSUE TITLE
Using sys.modules to patch all modules seems insufficient

### ISSUE THREAD

**Issue by SebastianFree** [jmcgeheeiv/pyfakefs#199]
I am using PyFakeFS (newest version) with its unit test implementation in a Django environment and Python 3.5.
Looking at the `Patcher` class, it seems insufficient to iterate over `sys.modules.items()` since it returns only those modules that have been imported until that point.
If my unit test imports a new module after `self.setUpPyfakefs()`, 'os' for example will not be patched there.

I managed to patch a new module using this wild construct: `self._stubber._stubs.SmartSet(new_module, 'os', self._stubber.fake_os)` but only after importing it, of course.

What am I doing wrong? How can modules that are being imported after setup still be patched automatically?

Thank you

**Comment by mrbean-bremen** [comment]
You are not doing anything wrong. This is indeed a shortcoming with pyfakefs and dynamic imports, and I have seen the same problem with Django views if using `django.conf.urls.patterns` in `urls.py`. If using the newer list syntax instead, e.g. instead of:
```
urlpatterns = patterns(
    'config.views',
    url(r'^configuration/$', 'config_page'),
    ...,
```
use
```
from . import views

urlpatterns = [
    url(r'^configuration/$', views.config_page),
    ...
```
you have to import the view class there and the problem may go away. Note that I have not tested this, though. If this does not help (or you already use that syntax), you can import the view class in your test source - this works, but gives an "unused import" warning.

**Comment by mrbean-bremen** [comment]
@SebastianFree - any progress on that? Do you need more help?

**Comment by SebastianFree** [comment]
Hi,
thanks for the reminder.
Atm I have other priorities, but I will come back to pyfakefs for sure.
All I can say now is that we are using the new URL syntax (didn't even know there was the old one).
Importing everything in advance kind of beats the purpose for me because it would mean individual efforts for every single test which is exactly what i wanted to avoid (only wanted one custom super class that sets up pyfakefs in setUp method).
But it might still be of value nevertheless. I"ll let you know.

**Comment by mrbean-bremen** [comment]
@SebastianFree - if you are still at this, can you please check if the problem persists with the current master branch? I added a fix for this, but I'm not completely sue that this resolves the problem.

**Comment by mrbean-bremen** [comment]
I could reproduce the problem in Django code, and it's now fixed for me. Closing this, please reopen if it doesn't work for you.
