### ISSUE TITLE
Spec for fake os.strerror()

### ISSUE THREAD

**Issue by jmcgeheeiv** [jmcgeheeiv/pyfakefs#202]
As pyfakefs users know, it is very useful for errors and exceptions to mention "fake file system".

While fixing a bug in fakefs related to exceptions, I noticed a nice way to add "fake file system" to the canonical error messages returned by `os.strerror()`.

In fake `os`, define `os.strerror()` as something like this:
```python
def strerror(errno):
    return '%s in the fake file system' % os.strerror(errno)
```
where the `os.strerror()` used within the function is the real `os.strerror()`.

The English grammar of this message should be correct in all cases.  Meanwhile, we can guarantee that `startswith()` can be used to detect the error message for both the real and fake file systems:
``` python
message = os.strerror(errno.ENOENT)
assert message.startswith('No such file or directory')
```
Then, all occurrences of literal string messages within pyfakefs should be replaced with the fake  `os.strerror()`.

**Comment by mrbean-bremen** [comment]
This is a very sensible thing to do - setting 3.4 milestone. 
Note, however, that checking for error messages is not a good idea because of localized error messages on non-English systems.

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - please check if this is what you had in mind.
I actually wanted to make a PR for this, but instead rebased and pushed to master, as I'm used to with the TSTL fixes - fingers faster than brain...

**Comment by mrbean-bremen** [comment]
Fixed by [this commit](https://github.com/jmcgeheeiv/pyfakefs/commit/ea6da7e59294ace72537fedee8087dba1d723b53), please reopen if something is missing.
