### ISSUE TITLE
Bad symlink allows getsize

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#210]
If you do a pure recursive symlink:

import pyfakefs.fake_filesystem

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test/alpha" 
os0.symlink(path0,path0) 
result = os0.path.getsize(path0)
print result

you can read the size (27)

Python os module instead, reasonably, fails getsize like other operations:

Traceback (most recent call last):
  File "bug3os.py", line 7, in <module>
    result = os0.path.getsize(path0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 62] Too many levels of symbolic links: '/Volumes/ramdisk/test/alpha'

**Comment by mrbean-bremen** [comment]
Shall be fixed, please verify.
