### ISSUE TITLE
With two FDs open for writing, file contents get corrupted, or reading raises

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#211]
``` python
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
path0 = "/Volumes/ramdisk/test/alpha" 
str0 = "aa" 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
os0.write(fd0,str0) 
fd1 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
os0.close(fd0) 
result = os0.path.getsize(path0) 
print result

```
This prints 2, while the Python os module yields 0.

Another case (from #221):
``` python
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path1 = path0 + "/" + component0
str0 = ""
str1 = str0 + 'a'
str2 = str1 + 'a'
str1 = str2 + 'a'
str0 = str1 + 'a'
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
fd1 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
os0.write(fd0,str0)
os0.write(fd1,str2)
result = os0.path.getsize(path1)
print result

```
pyfakefs gives 2, os gives 4

Yet another (from #229):
``` python
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path1 = path0 + "/" + component0
bytes0 = 1
str0 = ""
str1 = str0 + 'a'
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
os0.write(fd0,str1)
fd1 = os0.open(path1, os.O_RDONLY)
os0.close(fd0)
result = os0.read(fd1,bytes0)

```
The read fails with:

`(<type 'exceptions.AttributeError'>, AttributeError("'cStringIO.StringI' object has no attribute 'write'",), <traceback object at 0x10299b248>)`

Should obviously succeed -- the file was closed and has contents to read.

**Comment by mrbean-bremen** [comment]
Thanks for the reports, I may have a closer look at them at the weekend. TSTL sounds like a really helpful tool. Are you in the process of testing all of `pyfakefs` modules? Is this something you would advice us to do ourselves?

**Comment by agroce** [comment]
I might eventually get around to all of pyfakefs, but will probably just do what's easiest first.  My main goal is to put TSTL through the paces, add features to support testing interesting projects, and assemble benchmark examples for evaluating algorithms in papers.  I'd be more than happy to help if the pyfakefs team wants to go at this at a faster pace than I'm likely to, however!  You can take a look at the current test harness in the TSTL examples directory.  The exact version I run depends, since to get all the faults reported I drop some of the guards protecting against different bugs/unexpected behaviors.

**Comment by mrbean-bremen** [comment]
Thank you, this is really helpful! I will definitely check out TSTL some time. As for going at a faster pace - this is unlikely currently, given that both of us do this in our free time, which seems to shrink lately... I will see if I can fix your newly found issues as soon as possible and finish some ongoing work, and only after that I may start to actively try to find more problems using your tool.

**Comment by agroce** [comment]
That sounds good!  I'll hold off until you get a look at some of these.  Since the basic approach is to map every pyfakefs operation into an operation on the Python os module, these differences tend to either limit the testing and make it not effective, or just produce variations on the same differences.

For now, I can probably just run the setup a bit more to see if more stuff comes out once these are fixed.

Couple of questions:  how exact do you all want the replacement here?  I mostly expect right now that if you perform an operation, you'll either succeed or fail the same as Python-os module, but don't make sure your exceptions match (except that you shouldn't throw things like AttributeError or TypeError that aren't file-system related), for example.  And since you don't include reads, not sure how much file contents should match -- which is indirectly being checked by file size, in some cases that you may not care about.

I added globs yesterday, but other issues keep it from finding anything useful yet, will wait until some of the other issues are either resolved or considered okay to punch up the glob testing.

**Comment by mrbean-bremen** [comment]
I looked into the first ones, actually fixed some of them (the symllink related stuff, and the makedirs problem), didn't get to the other ones yet, as I decided first to finish some ongoing stuff.
As to your questions - we want to match the exception  type,  and  in the case of OSError/IOError ideally also the subtype, but not the exception  message, so that catching specific exceptions works the same as with the real `os`.
Also, we do include reads, and the file content usually  matters, except for files that are created with a size, but without content - these do not support reading / writing. Usually files are opened via `open` or `io.open`, which we also fake - the support for the low-level I/O functions like `os.open` may be incomplete, as they are seldom used.
Another thing, as you mentioned `glob` - the fake `glob` implementation is not really needed, if you patch `os`, and I want to remove it in the near future. The same is probably true for `tempfile`, whose fake implementation is quite incomplete anyway, and mostly for `shutil` (with the exception of `disk_usage ()`).

**Comment by jmcgeheeiv** [comment]
As @mrbean-bremen says, it would be a better use of your time to ignore `glob` and `tempfile`, as we plan to eliminate them from pyfakefs.

**Comment by agroce** [comment]
Removed glob from my tests; the ones you've reported look fixed (at least the particular test case; I'll run new fuzzing once a few more are fixed, and I can remove the TypeError and AttributeError exception OKs and reinstate rename and symlinks.
