### ISSUE TITLE
Directory that should exist is not created

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#215]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/alpha"
path2 = path0 + "/delta"
os0.mkdir(path2) 
os0.symlink(path0,path1) 
path1 = path1 + "/gamma"
try: os0.mkdir(path1)
except: pass
result = sorted(os0.listdir(path0)) 
print result

result = ['alpha','delta']

but with os, you also get 'gamma'

Seems like a bigger deal than the others, in that this is an actual filesystem structure discrepancy.

**Comment by mrbean-bremen** [comment]
Another symllink problem - shall be fixed now, please verify.

**Comment by mrbean-bremen** [comment]
Fixed by #218.
