### ISSUE TITLE
Rename allows recursive renames, which break file system

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#216]
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
path0 = "/Volumes/ramdisk/test"                     
path1 = path0 + "/alpha"                            
try: os0.rename(path0,path1)
except: pass
result = os0.path.isdir(path0)
print result

At this point, result is False, and something seems deeply wrong (the rename dies due to going over maximum recursion depth).  The right response for rename would be what os does:

Traceback (most recent call last):
  File "bug7os.py", line 6, in <module>
    os0.rename(path0,path1)
OSError: [Errno 22] Invalid argument

(and not modifying the file system)

**Comment by jmcgeheeiv** [comment]
This looks valid.

**Comment by agroce** [comment]
If I prevent this problem by not trying renames of X to X (which has always been a tricky thing, I remember at NASA "finding" this bug on a file system that hadn't actually gotten to me yet, just reading interface control documents, and asking what happened on rename(X,X) with directories), and disallow renames with src or dst as directory, rename seems to be ok now.  Clear those up and we can probably test with unrestricted renames.

**Comment by mrbean-bremen** [comment]
If even NASA doesn't get this right, we may be excused ;)
