### ISSUE TITLE
Rename disallows some valid renames

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#217]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
path0 = path0 + "/" + component0 
os0.mkdir(path0) 
os0.mkdir(path1)
try: os0.rename(path0,path1)
except: pass
result = sorted(os0.listdir(path0)) 
print result

The rename fails like this:

Traceback (most recent call last):
  File "bug8.py", line 16, in <module>
    os0.rename(path0,path1) 
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyfakefs/fake_filesystem.py", line 3215, in rename
    self.filesystem.RenameObject(old_file_path, new_file_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyfakefs/fake_filesystem.py", line 1655, in RenameObject
    new_file_path)
OSError: [Errno 17] Fake filesystem object: can not rename to existing directory: '/Volumes/ramdisk/test/alpha'

Should just move the directory into the other directory, like os does.

**Comment by jmcgeheeiv** [comment]
This is curious.  The pyfakefs `os` acts more like the [documentation](https://docs.python.org/3/library/os.html) than the real `os`.  This script uses fake pyfakefs `os`:
```python
import pyfakefs.fake_filesystem

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fakeos = pyfakefs.fake_filesystem.FakeOsModule(fs)

path0 = "Volumes/ramdisk/test/beta"
fs.CreateDirectory(path0)
path1 = "Volumes/ramdisk/test/alpha"
fs.CreateDirectory(path1)
#with open(path0 + '/betafile.txt', 'w') as f:
#    f.write('betafile.txt contents\n')
#with open(path1 + '/alphafile.txt', 'w') as f:
#    f.write('alphafile.txt contents\n')
fakeos.rename(path0, path1)
result = sorted(fakeos.listdir(path1))
print(result)
```
The above fake `os.rename()` results in the exception,
```
Traceback (most recent call last):
  File "bug8_pyfakefs.py", line 14, in <module>
    fakeos.rename(path0, path1)
  File "/Users/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 3469, in rename
    self.filesystem.RenameObject(old_file_path, new_file_path)
  File "/Users/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1835, in RenameObject
    new_file_path)
FileExistsError: [Errno 17] Fake filesystem object: can not rename to existing directory: '/Volumes/ramdisk/test/alpha'
```
However the documentation says that `OSError`, not `FileExistsError` should be raised.

Next, I tried the real `os`:
```python
import os

path0 = "Volumes/ramdisk/test/beta"
os.makedirs(path0)
path1 = "Volumes/ramdisk/test/alpha"
os.makedirs(path1)
#with open(path0 + '/betafile.txt', 'w') as f:
#    f.write('betafile.txt contents\n')
#with open(path1 + '/alphafile.txt', 'w') as f:
#    f.write('alphafile.txt contents\n')
os.rename(path0, path1)
result = sorted(os.listdir(path1))
print(result)
```
This does not raise `OSError`.  It overwrites directory `beta/`, and prints the empty list `[]`.

@agroce, @mrbean-bremen, please check my experiment and comment.

**Comment by mrbean-bremen** [comment]
I may check this tomorrow, if I find the time - quite possible that I did the implementation according to the documentation  (I rewrote the renaming code some time ago, so this is probably my fault). It is also possible, that the behavior differs under Windows. Note also that FileNotFoundError  is derived from OSError.

**Comment by agroce** [comment]
Hmm, you're right -- you're doing what Python docs say to do.  The experiment you sent does the same for me.  All of which seems more like what POSIX rename does than what the Python docs talk about:

http://pubs.opengroup.org/onlinepubs/009695399/functions/rename.html

**Comment by agroce** [comment]
I suspect the Python docs are just wrong, and this does a standard POSIX rename operation, which makes more sense than having Python do something of its own, with less functionality?

**Comment by mrbean-bremen** [comment]
Under Windows, rename fails (as it does per documentation for existing regular files). Ok, I will go with the assumption that the docs are just wrong.

**Comment by jmcgeheeiv** [comment]
I corrected my earlier incorrect statement about `FileNotFoundError` and `OSError`.

After we finish our work on this issue to make really sure that we know what we are talking about, we should notify the Python project.  Hopefully we can skip my example and just demonstrate the documentation problem using the existing test suite for the real `os.rename()`.

**Comment by jmcgeheeiv** [comment]
FYI, @mrbean-bremen and @agroce, I am soon leaving on vacation, returning June 30.  So you will not be hearing much from me until July.

**Comment by mrbean-bremen** [comment]
Well, have a nice vacation then!
 I will go on with fixing the issues found by @agroce.

**Comment by agroce** [comment]
Have a good vacation!

After the latest fixes, when I run without:

- rename
- symlinks
- more than one file descriptor (to prevent multiple opens on a file causing differences in contents)

I am now finding no issues at 3000+ tests of length 200.  There may be something in this set of operations, but at least it's subtle.  Checking in the tester that shows clean operation, so you can see which things are being tested.

**Comment by mrbean-bremen** [comment]
That sounds not so bad - better than I expected after the first problems!
I will hopefully fix the rename problems soon, and check the multiple file descriptor problem. 
Have you seen more problems with symlinks after the latest fixes?

**Comment by agroce** [comment]
Well, 3K tests is just a couple of minutes of tests, but yes -- it's a big jump in equivalence.

Just ran with rename, but with guards to ensure it avoids the reported bugs, found another AttributeError issue I'll submit.

About to turn off rename and turn on symlinks to see if there are outstanding symlink problems.
