### ISSUE TITLE
isdir / lexists fails on files handled by os module

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#219]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "c" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
path0 = path0 + "/" + component0 
str0 = "" 
str1 = str0 + 'c' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
path0 = path0 + "/" + component0 
os0.write(fd0,str1) 
result = os0.path.lexists(path0) 
print result

this dies with either lexists or isdir, with a TypeError.  For both, os module returns False.

**Comment by agroce** [comment]
also isfile, probably other similar functions

**Comment by agroce** [comment]
(looks like this pattern, which can't be further reduced, so the double /c/c is presumably important, basically causes the functions to fail with TypeError rather than just realizing the open failed -- in fact, the open presumably didn't correctly fail, since the write doesn't cause any exception to be thrown?)

**Comment by agroce** [comment]
Ok, this basically happens for every path query function that needs to actually check state of the file.

**Comment by mrbean-bremen** [comment]
This is a rather obscure bug - it happens if a file path is queries, weher the last (non-existing) component has a name that is contained in the existing "parent" file content.
