### ISSUE TITLE
makedirs fails that succeeds on os (another symlink issue)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#220]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "epsilon" 
component1 = "b" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "f" 
os0.symlink(path0,path1) 
path1 = path1 + "/" + component0 
component0 = "delta" 
path2 = path0 + "/" + component1 
os0.mkdir(path2) 
path2 = path1 + "/" + component0 
os0.makedirs(path1) 

(fails with "Not a directory" on /Volumes/ramdisk/test)

**Comment by agroce** [comment]
Until this is fixed, I can't test with symlinks, because even if I ignore the initial difference, it later yields all kinds of differences.

**Comment by mrbean-bremen** [comment]
Yes, symlink support seems to be quite shaky - maybe we need some refactoring for the related code. I have to admit that I didn't really look at that code until now - symlinks are practically not used under Windows.
