### ISSUE TITLE
File size difference due to two open FDs writing

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#221]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
str0 = "" 
str1 = str0 + 'a' 
str2 = str1 + 'a' 
str1 = str2 + 'a' 
str0 = str1 + 'a' 
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
fd1 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
os0.write(fd0,str0) 
os0.write(fd1,str2) 
result = os0.path.getsize(path1) 
print result

pyfakefs gives 2, os gives 4

**Comment by mrbean-bremen** [comment]
Seems to be related to #211.

**Comment by mrbean-bremen** [comment]
Merged into #211.
