### ISSUE TITLE
Just test that the non-faked shutil functions are equal to real shutil functions

### ISSUE THREAD

**Issue by jmcgeheeiv** [jmcgeheeiv/pyfakefs#223]
In #222, most of the fake `shutil` functions were removed in favor of patching `shutil` itself with fake `os`, etc.  Just the functions that _must_ be faked remain in `fake_filesystem_shutil.py`.

The real shutil functions are still being tested in `fake_filesystem_shutil_test.py`.  This should be left as-is for at least one release cycle (until pyfakefs 3.4).  However, in the future this will become a maintenance problem.  I propose that we test them more analytically, testing that:
* Imports in `shutil` are in fact patched with pyfakefs modules
* All the `shutil` functions that are supposed to be faked are not equal to the real `shutil` functions
* All other `shutil` functions are equal to the real `shutil` functions

Then test the functionality of the fake `shutil` functions as is done currently.

We should retain a couple of tests for real `shutil` functions as canaries to tell us if there are holes in the analytical tests.

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - I checked how to implement this one, and did some re-evaluation of the issue. Now I'm not sure if that is really needed. A couple of thoughts:

There are not many tests for `shutil` (about 30, compared to about 900 tests we have in pyfakefs, not counting the real fs tests), so I don't think, there will be much of a maintanance problem here. Given that the tests only cover a small part of `shutil`, I see them as canaries even now and would like to leave them for the time being. Also, most of them are now run both with the fake and the real file system, so I would like to keep them as an additional check that we behave correctly.
That the imports in `shutil` are patched is evident from any of the tests for non-faked functions. As there is only one faked function (`get_disk_usage()`), and the rest is forwarded to the real implementation, there is not much to test here for that part. Enumerating all non-faked functions and comparing them to the real ones may be possible, but I don't see that we gain much from that. 

What do you think?

**Comment by mrbean-bremen** [comment]
Having written this, just noticed that the `shutil` tests fail under Python 3.7... obviously, the implementation has changed. Wil have a look at this later.

**Comment by mrbean-bremen** [comment]
Clearing milestone, has to be re-evaluated.

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - I would like to keep the tests to catch changed implementations in new Python versions (see my comment above). What do you think?

**Comment by jmcgeheeiv** [comment]
No longer needed.
