### ISSUE TITLE
Symlink after deep makedirs produces very different directory structures in walk

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#225]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
path2 = path1 + "/" + component0 
path1 = path2 + "/" + component0 
path2 = path1 + "/" + component0 
os0.makedirs(path1) 
os0.symlink(path1,path2) 
result = [p for p in os0.walk(path0,topdown=True,followlinks=True)]
print result

I get a much larger directory structure from walk with os than with fakeosmodule (length 23 vs. 36)

**Comment by mrbean-bremen** [comment]
I'm not sure about this one. Currently, the maximum number of symbolic links is hardcoded to 20 in pyfakefs. Different Linux kernels have different values, and I don't know how to get them (I'm more of a Windows guy) or if this even needed. This is something I wouldn't think is important to behave in exactly the same way - I think the important thing is that symlink loops are detected.
Maybe just increase the number to 40 (which seems to more consistent with current kernels) to avoid false loop detection?

**Comment by mrbean-bremen** [comment]
I adapted the symlink max depth to match at least most current systems - please check if this fixes the issue.

**Comment by agroce** [comment]
Not quite.  I get length 35 for pyfakefs vs. 36 for os, so it still fails.  Looks to me like when I run the random tester, it now takes longer and produces a much larger directory structure that exposes the problem, which is expected, but this example also still doesn't quite match.

I'll have to work out how to keep symlinks from getting to the point there is a mismatch in random testing.

**Comment by mrbean-bremen** [comment]
Ah ok, should be a simple matter how to count the depth then - I will check this tomorrow.

**Comment by mrbean-bremen** [comment]
Shall be fixed via https://github.com/jmcgeheeiv/pyfakefs/commit/fa2a4b8510c8cb021f5f44360452e7581aebf1b2.
