### ISSUE TITLE
After symlink, rmdir fails due to "not a directory" incorrectly

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#226]
(Could well be duplicate with other symlink issues, in some deep way, but this one seems nicely simple, at least):

import pyfakefs.fake_filesystem
import os
import shutil

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
component1 = "beta" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.mkdir(path1) 
path1 = path0 + "/" + component1 
os0.symlink(path0,path1) 
path0 = path1 + "/" + component0 
os0.rmdir(path0) 

The rmdir should succeed, but fails with:

Traceback (most recent call last):
  File "bug14.py", line 23, in <module>
    os0.rmdir(path0) 
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 3518, in rmdir
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 2442, in RemoveDirectory
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 2395, in ConfirmDir
OSError: [Errno 20] Not a directory in fake filesystem: '/Volumes/ramdisk/test/beta/alpha'

**Comment by mrbean-bremen** [comment]
Not a duplicate, but had a similar cause - the path was not resolved for symlinks. Most of these shall be gone now. 
I'm done for today, will hopefully continue with more issues tomorrow evening. Thanks for the work, this is going to be a real boost for the quality of the library!
