### ISSUE TITLE
Read fails when it should not with two open FDs

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#229]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
bytes0 = 1 
str0 = "" 
str1 = str0 + 'a' 
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.write(fd0,str1) 
fd1 = os0.open(path1, os.O_RDONLY) 
os0.close(fd0) 
result = os0.read(fd1,bytes0) 

The read fails with:

(<type 'exceptions.AttributeError'>, AttributeError("'cStringIO.StringI' object has no attribute 'write'",), <traceback object at 0x10299b248>)

Should obviously succeed -- the file was closed and has contents to read.

**Comment by mrbean-bremen** [comment]
Another problem with 2 open file descriptors - it works only if closing the first one before opening the second one. I will tackle these ones together later - there seems to be conceptual problem. This is mostly still the original code written by Mike Bland in 2011 - so some refactoring is overdue...

**Comment by mrbean-bremen** [comment]
Merged into #211.
