### ISSUE TITLE
Failing rename differs from os

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#230]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "gamma" 
component1 = "epsilon" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "phi" 
path0 = path1 + "/" + component1 
path1 = path0 + "/" + component0 
component0 = "f" 
path2 = path1 + "/" + component0 
component0 = "alpha" 
path0 = path0 + "/" + component0 
path1 = path2 + "/" + component0 
os0.makedirs(path2) 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
os0.rename(path0,path1)

The rename fails 

Traceback (most recent call last):
  File "bug18.py", line 29, in <module>
    os0.rename(path0,path1)
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 3525, in rename
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 1903, in RenameObject
OSError: [Errno 22] Fake filesystem object: invalid target for rename: '/Volumes/ramdisk/test/gamma/epsilon/phi/f/alpha'

Works on os

**Comment by agroce** [comment]
After this fix, except for the fact that unlike os it won't handle directories in src or dst, rename looks ok.  A few thousand tests, no failures.  Will keep running, rename bugs can be subtle, but I expect without directories in either argument, it's equivalent to os now!

**Comment by mrbean-bremen** [comment]
Hm, sounds good, but what happens with directories in src or dest? There is code to handle this, obviously still buggy...

**Comment by mrbean-bremen** [comment]
And I heartily agree now that rename is tricky!

**Comment by agroce** [comment]
Ok, so rename should handle src/dst == directory?  Any constraints on that?  When I remove the guard and have "naked" rename, I find things.  Let me run and push one (wasn't sure this had been fixed).

Rename is really a beast, gets even worse when you have to worry about atomicity: http://www.cs.cmu.edu/~agroce/icse07.pdf

**Comment by mrbean-bremen** [comment]
Yes, it shall handle this, but I'm sure there are more issues there. Go ahead and add issues!
And we won't worry about atomicity here - I don't think we will support multi-threading tests. Also, we don't worry (at least at the moment) about OS specific stuff like file flags `st_rdev` or `st_gen`, or the already mentioned maximum symlink rescursion depth. Apart from that, the goal is to have the same behavior.
I'm looking forward to the day we will use TSTL ourselves for the tests, including different Python versions...

**Comment by agroce** [comment]
Sounds good -- added one test where you allow something os doesn't.

Yes, I figured atomicity would be a huge pain, and probably not important for most testing uses.  We probably want to find some way around the symlink issue, since right now it prevents finding more interesting symlink issues, I suspect (you hit this problem first, so either only get it, or have to inspect each failure to see if it is the same bug).

TSTL doesn't have a 3.0+ ready version yet, but it's not a huge leap to make it work on both, just time consuming and hasn't been on my priority list yet.

**Comment by mrbean-bremen** [comment]
I just scanned your paper - so it was the work at JPL that started TSTL? Though the paper is 10 years old, I guess you have invested a lot of time into this topic since then... I myself haven't been aware about random testing until recently (I think I watched a lecture at PyCon, probably about Hypothesis), and never used it. Going to chnage this...

**Comment by mrbean-bremen** [comment]
Is this a specific symlink issue you are mentionng, or just the general bugginess of the implementation?

**Comment by agroce** [comment]
I did my PhD on software verification (exhaustive exploration), then used random testing when I was at JPL partly because it scales better in many ways.  Random testing was/is one of my major research efforts, but TSTL started in late 2014 when a grad student and myself became frustrated writing custom test generation code every time we wanted to try our ideas on a new experimental subject.  But definitely the work at JPL had a big impact on the design of TSTL, since it taught me how to build a large complex tester.

The symlink issue that's still open, #225, I think that one will keep cropping up with symlink testing.

**Comment by agroce** [comment]
http://www.cs.cmu.edu/~agroce/sttt17.pdf is the most comprehensive TSTL paper, but has a lot of detail that's only interesting for folks implementing new testing algorithms using it.

**Comment by mrbean-bremen** [comment]
Ah, that issue - but this is more an issue with `walk`, as I see it. `walk` just stops when it reaches the maximum symlink depth, while other functions raise OSError. I may check the Python implementation later, maybe I can find a way to fix this.

**Comment by agroce** [comment]
Aha.  I'll just test symlink without walk then!

**Comment by mrbean-bremen** [comment]
Ok,  👍 . I'm done for today...
