### ISSUE TITLE
Open on nonexistent file exception difference

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#237]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path1 = path0 + "/" + component0
fd0 = os0.open(path1, os.O_RDWR)

(the particular flags don't matter, just that os produces OSError and pyfakefs yields IOError, when attempting to open file that doesn't exist)

**Comment by agroce** [comment]
Doesn't seem totally fixed?  I get the same mismatch when doing O_CREAT | O_WRONLY | O_TRUNC on

/Volumes/ramdisk/test/alpha/alpha from a fresh filesystem -- I guess technically a different bug, since it involves missing dir, not just missing file being opened for read.

**Comment by mrbean-bremen** [comment]
Agreed - I may check this tomorrow. For today I'm done  (anyway, it ends in half an hour).

**Comment by mrbean-bremen** [comment]
Ok, you wrote a new issue - closing this one again in this case.
