### ISSUE TITLE
Exception mismatch on O_CREAT with bad path

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#238]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path1 = path0 + "/" + component0
path1 = path1 + "/" + component0
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)

**Comment by mrbean-bremen** [comment]
Can't reproduce this one - I get OSError 2 on both sides. What do you get here?

**Comment by agroce** [comment]
IOError for pyfakefs, OSError for os

Could it be OS X?

**Comment by mrbean-bremen** [comment]
Ok, will check again tomorrow - maybe I tested in the wrong environment  (e.g. Python 3).
