### ISSUE TITLE
Reading from fake block devices doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jmcgeheeiv/pyfakefs#24]
```
What steps will reproduce the problem?
1. Create a fake block device (dev = fs.CreateFile('name', stat.S_IFBLK))
2. Try and read from it (dev.read())


What is the expected output? What do you see instead?
This should work, but an error is raised about trying to read from a directory.

Patch with fix and test attached.

```

Original issue reported on code.google.com by `dmwh...@google.com` on 12 Dec 2013 at 3:13

Attachments:
* [block_device_read.patch](https://storage.googleapis.com/google-code-attachments/pyfakefs/issue-24/comment-0/block_device_read.patch)

**Comment by jmcgeheeiv** [comment]
Fixed by @dougluce in pull request #67.
