### ISSUE TITLE
os.walk produces wrong output with symlinks and followlinks=False

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#240]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "gamma" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.symlink(path0,path1)
result = [p for p in os0.walk(path1,topdown=True,followlinks=False)]

print result

You get [] from pyfakefs, but [('/Volumes/ramdisk/test/gamma', ['gamma'], [])] from os.

The previous case/diagnosis/title were wrong.  symlink succeeds in both cases, just produces different file system.  Sorry.

**Comment by mrbean-bremen** [comment]
Uh, I already hate symlink... will check it another day, too tired today.

**Comment by agroce** [comment]
Sounds good.  Looks like just a missing guard leading to error, at least.

You're running clean on 1 file descriptor + rename with no restrictions other than avoiding apple's bug.

**Comment by agroce** [comment]
(symlink is off until this is fixed)

**Comment by agroce** [comment]
Problems with this test case, hold on, fixing it

**Comment by mrbean-bremen** [comment]
Ok, just tested the behavior - under Windows it is completely broken (in the given case, it behaves like `pyfakefs`, in other cases, `followlinks` makes no difference, or returns incorrect results).
So I will ignore Windows completely here (anyway, symlinks are not used here in reality).
Under Linux, `followlinks` is ignored for the top directory (which is not obvious from the documentation, at least for me), I will change the implementation accordingly.
