### ISSUE TITLE
Link followed by walk exceeds recursion limit

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#242]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.link(path0,path1) 
result = [p for p in os0.walk(path0,topdown=True,followlinks=True)]

Maybe a result of the fix just put in, since I think we'd have seen this before.  os just fails with OSError: [Errno 1] Operation not permitted, but pyfakefs bombs out with a recursion depth overflow in cmp.

Below test is likely same issue, since it is a case where os fails with Errno 1, but it does a different thing, so including:

import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "phi" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "alpha" 
path0 = path0 + "/" + component0 
os0.mkdir(path1) 
os0.link(path1,path0) 
path0 = "/Volumes/ramdisk/test" 
result = sorted(os0.listdir(path0)) 
print result

This leads to different listdir results, of course.

**Comment by mrbean-bremen** [comment]
Strange. I get OSError 1 in pyfakefs (indeed I just added this in the last fix).

**Comment by mrbean-bremen** [comment]
Are you sure you are using the latest version?
I added this less than an hour ago (noticed that directory links are allowed while fixing the IOError vs. OSError bug).

**Comment by agroce** [comment]
Aha, not latest version!  I did a git pull after all the issue closes, I thought, but apparently not.

**Comment by agroce** [comment]
Running tests again with latest, sorry!

**Comment by mrbean-bremen** [comment]
thats ok then :)

**Comment by mrbean-bremen** [comment]
I'm done for today anyway - unfortunately I'm not a professor in the summer, so I have to get up early in the morning...

**Comment by agroce** [comment]
(Closed #242 as based on non-latest version)
