### ISSUE TITLE
symlink of file to itself succeeds as NOP, should fail with OSError Errno 2

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#247]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
path0 = path1 + "/" + component0 
os0.symlink(path0,path0) 

os fails the symlink with OSError and Errno 2, pyfakefs succeeds.

**Comment by agroce** [comment]
If you change it to not be a self-symlink, there's also an issue:

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
path0 = path1 + "/" + component0 
os0.symlink(path1,path0) 

Basically, symlink is not checking existence of the path early enough and exiting if it doesn't exist.

Not an exciting error, but holding up aggressive symlink testing.  Exception types look to be matching for all tested operations other than symlink, under the "1 open file descriptor" constraint.

**Comment by mrbean-bremen** [comment]
Yes, hopefully the symlink issues are soon over... Will check this over the weekend. I'm currently working on  another issue (tempfile removal) and hit a road block there, so I want to get this done first (before I start dreaming about symlinks...).

**Comment by agroce** [comment]
Sounds good, I'll hold off a bit.  It turns out that this one also stops checking for symlink problems without checking failure equivalence, since it allows some symlinks that should fail to do something, as in this case:

import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = path0 + "/" + component0 
component1 = "alpha" 
path3 = path2 + "/" + component1
try:
    os0.symlink(path1,path3)
except Exception as e:
    print "FAILED WITH",e
result = ([p for p in os0.walk(path2,topdown=True,followlinks=False)])

print result
