### ISSUE TITLE
Rename fails in pyfakefs, succeeds in os (after symlink)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#249]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
path0 = path0 + "/" + component0 
os0.symlink(path0,path1) 
os0.rename(path1,path0) 

I think the key is that the os is having the symlink do something, and create path1, even though the target isn't there yet.  By POSIX this looks to be correct, I think:  http://pubs.opengroup.org/onlinepubs/009695399/functions/symlink.html

**Comment by mrbean-bremen** [comment]
Yes, I may check this tomorrow (done for today). Maybe `rename` is  trying to resolve the symlink, while it should rename the symlink itself. I think next I will look at the issues with 2  FDs, I mostly finished the other stuff with tempfile for now.

**Comment by agroce** [comment]
I noticed the very large git pull.

I should check posix rename, if it is supposed to fix a broken symlink like this.  This is obviously a sort of odd corner case.

I have an "assume" that checks for isdir hitting a "too many links" exception, and terminates the test if it hits it, but still can't avoid os.walk running into issues with symlink chains.

For example:

component0 = "delta" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.symlink(path0,path1) 
result = [p for p in os0.walk(path0,topdown=True,followlinks=True)]

result differs from os to pyfakefs, but isdir doesn't return a "too many links" on path0 or path1 (my check for hitting an invalid state).
