### ISSUE TITLE
Rename failure difference after symlink (different structure)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#251]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path2 = path0 + "/" + component0 
component0 = "beta" 
path0 = path0 + "/" + component0 
path1 = path0 + "/" + component0 
os0.mkdir(path0) 
os0.symlink(path1,path2) 
os0.rename(path0,path2)

**Comment by mrbean-bremen** [comment]
I think broken symlinks have not been considered at all so far in pyfakefs. TSTL generates a lot of them...
Will check this tomorrow (as always, I finish as you start working on this)

**Comment by agroce** [comment]
Sounds good.  I added a non-symlink bug to give a break.  Started testing what can be checked on stat.

**Comment by mrbean-bremen** [comment]
`os.rename` shall raise OSError(errno.ENOTDIR) here, is that correct?
