### ISSUE TITLE
Equality on stat objects doesn't handle None

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#253]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha"

path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 

fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)

stat0 = os0.fstat(fd0)

stat0 == None

This is handled fine by os, but pyfakefs does:

Traceback (most recent call last):
  File "bug36.py", line 24, in <module>
    stat0 == None
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 199, in __eq__
    self._st_atime_ns == other._st_atime_ns and
AttributeError: 'NoneType' object has no attribute '_st_atime_ns'

(I introduced some checking for stat fields that can be expected to be correct, but this is a showstopper for stat testing, since TSTL has to check objects created for equality with None)

**Comment by agroce** [comment]
(at least it's not a symlink bug!)

**Comment by mrbean-bremen** [comment]
My bad - unable to write an __eq__ operator correctly! But yeah, it's not a symlink bug, thanks for that!
