### ISSUE TITLE
open with just O_CREAT succeeds on os, fails on pyfakefs

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#254]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
mode0 = os.O_CREAT 
fd0 = os0.open(path1, mode0) 

Added testing for arbitrary mode combinations, hit this immediately.

**Comment by mrbean-bremen** [comment]
Not symlink-related either - thanks! Should be a simple logical error here.
