### ISSUE TITLE
stat nlink count incorrect for directories

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#255]
``` python
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.mkdir(path1) 
stat0 = os0.stat(path1) 
result = stat0.st_nlink 

print result


```
I'm reporting this (you get 1 vs. os 2) but I'm not sure it's an issue with pyfakefs; where the second link comes from for os is not obvious to me, but I've never investigated nlink meaning much.  Going to remove nlink from comparisons and continue.

**Comment by mrbean-bremen** [comment]
Found this:
> The st_nlink for dirs is actualy not well defined. But the convention
> under unix is that it is the number of subdirectories including "." and
> "..".
> 
I didn't know that, in pyfakefs, we just count the number of hard links. I think this is low priority...

**Comment by agroce** [comment]
Aha.  I will modify to work like st_size and only check for non directories, then.
