### ISSUE TITLE
open with O_WRONLY and O_EXCL should fail

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#256]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
mode0 = os.O_WRONLY 
mode1 = os.O_EXCL 
mode2 = mode0 | mode1 
fd0 = os0.open(path1, mode2) 

The file doesn't exist, and there's no O_CREAT.  os returns OSError Errno 2

**Comment by agroce** [comment]
Busy today, but left it running in a mode where it'll collect new failing tests, normalize them into a simplest-possible form, and see if it digs up anything new.  So far it's just collected a few variations of this bug (and shown me I needed to make sure st_size wasn't checked for directories).

**Comment by agroce** [comment]
(by variations I mean it finds something that is the O_WRONLY | O_EXCL bug, in a different form, but then converts it and determines it's just a repeat of the basic pattern, so discards it -- convenient if you don't want to look at hundreds of tests for the same bug, but want to leave testing running)

**Comment by mrbean-bremen** [comment]
Ok. I have to admit that in this case I just assumed that a valid combination of flags is used. From man open(2):
> In general, the behavior of O_EXCL is undefined if it is used without O_CREAT.

I will change this, maybe tomorrow.

**Comment by mrbean-bremen** [comment]
and that variation feature sounds quite convenient - one day I will get to TSTL... 
I had some trouble today to wrap my head around the file operations implementation to fix these caching problems with multiple FDs - I will tackle this another day with a clear head

**Comment by mrbean-bremen** [comment]
On a second thought (and after discussing this with another pyfakefs user) I'm inclined to not implement this as I wrote before, but instead raise `NotImplemented`. This is indeed how it is in the released version (e.g. 3.2) for all modes that do not contain `O_CREAT`, and until now, nobody has complained, so I guess, almost nobody is using this low-level API. As the behavior for the case in the current issue is undefined (e.g. it can be considered a programming error to use it that way) I think it is appropriate to raise. I think you can accept certain exceptions in your tests and ignore these cases, is that correct?
Also, I have been thinking about priorities. At the current rate, I will be busy fixing bugs for a long time, so I will think more about cost (e.g. spent time)/effectiveness here, and about relevant use cases. For example, the three issues with two FDs open for writing are not easy to fix, and writing into a file simultaneously by different users is unlikely to happen in test code (and usually not a good idea in production code), so I may just give them a low prority (maybe add priority labels), and also merge them into one bug, which they essentially are.
The other side is if some bug prevents you from testing further - in this case it is better to fix it anyway, of course. 
What do you think?

I don't have much time today, so I won't probably fix any bugs and reorganize them instead...

**Comment by agroce** [comment]
The two FDs bugs is basically only stopping two-FDs bugs.  Weird modes is very easy to avoid generating (I wasn't generating them for a long time).  Those seem easy to just ignore.  The stat bugs, ditto.

**Comment by mrbean-bremen** [comment]
Ok - I will raise `NotImplementedError` for this case and consider this issue fixed.
