### ISSUE TITLE
Mode of just created file differs

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#258]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
stat0 = os0.fstat(fd0) 
result = stat0.st_mode 

print result

**Comment by mrbean-bremen** [comment]
I'm not sure about this one. I currently set the mode to 0o777 for `os.open()` if not given as per documentation (changed this from the previous 0o666), but the real value may depend on the umask on the system, as I understand. 
I tested this under Windows and Linux and got 0o666 and 0o775, respectively. I think I will leave this open for a while if you can live with this - maybe @jmcgeheeiv has an idea how to handle this.
