### ISSUE TITLE
Please host the documentation for pyfakefs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jmcgeheeiv/pyfakefs#26]
```
It is very difficult to browse through the documentation in source. Kindly 
upload it to pythonhosted or readthedocs.
```

Original issue reported on code.google.com by `pratika...@gmail.com` on 21 Jan 2014 at 4:08

**Comment by jmcgeheeiv** [comment]
I enhanced the README and added a tutorial showing a practical usage example showing how to test your software.
