### ISSUE TITLE
Symlink + mkdirs before rename failure

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#261]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
path2 = path0 + "/" + component0 
path0 = path1 + "/" + component0 
os0.mkdir(path2) 
os0.symlink(path2,path1) 
os0.mkdir(path0) 
os0.rename(path2,path0) 

Quite possibly same bug as #260 -- but this one has a different rename exception, so I'm giving it a separate entry in case they aren't the same cause.

**Comment by mrbean-bremen** [comment]
Do you expect that rename shll succeed here? I tried this with the real os, and got an OSError (Invalid Argument), which I also get in pyfakefs after I tried to fix this. If I understand this correctly, this rename shall not be possible, as it tries to rename the path to it's own parent.

**Comment by agroce** [comment]
Hmm, fails for both for me, now.  I hadn't looked in detail.

**Comment by mrbean-bremen** [comment]
Ok, I will check in the changes then and consider this fixed.
