### ISSUE TITLE
Walk with followlinks issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#264]
import pyfakefs.fake_filesystem
import os
import shutil

def sortWalk(l):
    newList = []
    for (p,l1,l2) in l:
        newList.append((p,sorted(l1),sorted(l2)))
    return sorted(newList,key=lambda x:x[0])

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.symlink(path0,path1) 
result0 = sortWalk([p for p in os0.walk(path0,topdown=True,followlinks=True)])

if os.path.exists('/Volumes/ramdisk/test'):
    shutil.rmtree('/Volumes/ramdisk/test')
os.mkdir('/Volumes/ramdisk/test')

os0 = os

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
os0.symlink(path0,path1) 
result1 = sortWalk([p for p in os0.walk(path0,topdown=True,followlinks=True)])

print len(result0),len(result1)

for i in xrange(0,len(result0)):
    if result0[i] != result1[i]:
        print "MISMATCH AT",i
        print "  pyfakefs = ",result0[i]
        print "  os       = ",result1[i]        

More elaborate test case than usual, to let you see what is happening, it's a long symlink chain, but the difference is only in last element.  I suspect there is some related bug that can cause a termination issue (not recursion overflow, but testing just locks up), with symlinks and walk with followlinks, but haven't yet managed to capture a test case.

**Comment by mrbean-bremen** [comment]
This is again the problem with the maximum recursion depth - I have changed the algorithm slightly, so that it now gets out one more element then before to match your findings, but that may have been wrong. On the Mac, the maximum recursion depth is 32, but we effectively get 33 here.
As I said before, I do not consider this something that pyfakefs should support at all, but I may have a further look as it seems to hinder your testing.
Can you give me the full output of result0 and result1 here, just to be sure I understand this correctly? I cannot really reproduce this properly under Windows.

**Comment by agroce** [comment]
Output on my mac, latest version from github of pyfakefs:

33 33
RESULT0 = [('/Volumes/ramdisk/test', ['alpha'], []), ('/Volumes/ramdisk/test/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], [])]
RESULT1 = [('/Volumes/ramdisk/test', ['alpha'], []), ('/Volumes/ramdisk/test/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], []), ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', [], ['alpha'])]
MISMATCH AT 32
  pyfakefs =  ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', ['alpha'], [])
  os       =  ('/Volumes/ramdisk/test/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha/alpha', [], ['alpha'])

**Comment by mrbean-bremen** [comment]
Ok, thanks - not really what I expected. The real result looks somewhat strange, I will try to understand this.

**Comment by mrbean-bremen** [comment]
Hm, this is strange - if I test this in pyfakefs, I get exactly the same as result1 (which is from the real os if I understand correctly).

**Comment by mrbean-bremen** [comment]
Ok, I may have another look tomorrow. I have no idea why you get different results - reverting to the version from yesterday didn't change the outcome.

**Comment by agroce** [comment]
This is weird.  I didn't think you guys cared, just seeing if I can find some way to test walk with followlinks=True.  For now, just turning it off.  My guess (based on a hanging test) was that followlinks=True leads to some issue with a loop not terminating, so I wanted to test it some, but if we keep hitting this and the behavior is weird, maybe ignorable.

Very odd if my mac and your machine produce different pyfakefs results.  os, sure, but pyfakefs?

**Comment by mrbean-bremen** [comment]
Maybe I did some mistake, though I don't know how. You are right, I don't care much about this issue as it is not a real world issue, but I'm just intrigued...

**Comment by mrbean-bremen** [comment]
Ok, my mistake was to test under Python 3. 
This was an `IOError` vs. `OSError` issue - `IOError` was catched in the relevant place, `OSError` was not (as they are the same in Python 3, it behaved correctly there).
