### ISSUE TITLE
mkdir fails after symlink, makedirs

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#266]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
path0 = path0 + "/" + component0 
path2 = path0 + "/" + component0 
os0.makedirs(path2) 
os0.symlink(path0,path1) 
path0 = path1 + "/" + component0 
os0.removedirs(path0) 
os0.mkdir(path0) 

pyfakefs fails the mkdir with ENOENT (no such fake directory)

**Comment by mrbean-bremen** [comment]
For me, `removedirs` raises OSError with ENOENT in pyfakefs, in my understanding, correctly, as path0 does not exist.

**Comment by mrbean-bremen** [comment]
Can you confirm that for you, `removedirs` works both in os and pyfakefs?

**Comment by agroce** [comment]
Yes, the code runs without any exceptions raised until the mkdir, for me.  I'm using the latest pyfakefs from github, I believe (just to check we have the same code, I get:

> wc -l pyfakefs/fake_filesystem.py
    4431 pyfakefs/fake_filesystem.py

This is quite odd.

**Comment by agroce** [comment]
Ok, I made the test a bit more verbose, and it looks like the right things happen up until the mkdir, to me, in my version:

import pyfakefs.fake_filesystem
import os

def crawl(n,d,osm):
    print " "*n,d
    for p in osm.listdir(d):
        if osm.path.isdir(d+"/"+p):
            crawl(n+2,d+"/"+p,osm)
    return

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

crawl(0,"/Volumes/ramdisk/test",os0)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
path0 = path0 + "/" + component0 
path2 = path0 + "/" + component0
print "MAKEDIRS",path2
os0.makedirs(path2)
crawl(0,"/Volumes/ramdisk/test",os0)
print "SYMLINK",path1,"-->",path0
os0.symlink(path0,path1)
crawl(0,"/Volumes/ramdisk/test",os0)
path0 = path1 + "/" + component0
print "REMOVEDIRS",path0
os0.removedirs(path0)
crawl(0,"/Volumes/ramdisk/test",os0)
print "MKDIR",path0
os0.mkdir(path0)
crawl(0,"/Volumes/ramdisk/test",os0)


Running this with pyfakefs I get:

 /Volumes/ramdisk/test
MAKEDIRS /Volumes/ramdisk/test/beta/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/beta
     /Volumes/ramdisk/test/beta/beta
SYMLINK /Volumes/ramdisk/test/alpha --> /Volumes/ramdisk/test/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/alpha
     /Volumes/ramdisk/test/alpha/beta
   /Volumes/ramdisk/test/beta
     /Volumes/ramdisk/test/beta/beta
REMOVEDIRS /Volumes/ramdisk/test/alpha/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/beta
MKDIR /Volumes/ramdisk/test/alpha/beta
Traceback (most recent call last):
  File "bug50.py", line 40, in <module>
    os0.mkdir(path0)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 3670, in mkdir
    self.filesystem.MakeDirectory(dir_name, mode)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 2354, in MakeDirectory
    raise OSError(errno.ENOENT, 'No such fake directory', base_dir)
OSError: [Errno 2] No such fake directory: '/Volumes/ramdisk/test/alpha'


with os, I get:

 /Volumes/ramdisk/test
MAKEDIRS /Volumes/ramdisk/test/beta/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/beta
     /Volumes/ramdisk/test/beta/beta
SYMLINK /Volumes/ramdisk/test/alpha --> /Volumes/ramdisk/test/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/alpha
     /Volumes/ramdisk/test/alpha/beta
   /Volumes/ramdisk/test/beta
     /Volumes/ramdisk/test/beta/beta
REMOVEDIRS /Volumes/ramdisk/test/alpha/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/alpha
   /Volumes/ramdisk/test/beta
MKDIR /Volumes/ramdisk/test/alpha/beta
 /Volumes/ramdisk/test
   /Volumes/ramdisk/test/alpha
     /Volumes/ramdisk/test/alpha/beta
   /Volumes/ramdisk/test/beta
     /Volumes/ramdisk/test/beta/beta

**Comment by agroce** [comment]
(bleah, indentation destroyed, but should be easy to fix up)

**Comment by mrbean-bremen** [comment]
Strange. I already switched the PC off, so I will have another look tomorrow - maybe I made an error while copying the test.

**Comment by mrbean-bremen** [comment]
Indentation restored :)

**Comment by mrbean-bremen** [comment]
After looking at your output, it is clear that `removedirs` is the culprit - it removes the symlink. I definitely must have made an error in the  test, will check that in the evening.

**Comment by agroce** [comment]
7 hours of testing shows nothing but a few variations on that pattern, plus one really obscure way to produce the OS X rename bug, that gets around my guard by using a series of symlinks, so this may be the last issue in the high-priority API set.

**Comment by mrbean-bremen** [comment]
Sounds great! Though I still expect a lot of issues in the rest of the API. How did you define the high priority API, BTW?

**Comment by agroce** [comment]
Sorry, I meant high priority part of what I have TSTL testing!  I'm not testing what I would guess is the actual high priority API yet at all -- using non-os module open/read/write.  That will take some work.  I just meant ignoring multiple open FDs and modes, etc.; the high priority API only within the fake os module, not all of pyfakefs.  Is there anything very interesting (permissions?) in the fake os module not tested now?

**Comment by mrbean-bremen** [comment]
No, you are right - in the scope of `os` (without `os.path`) you got the important stuff, I think. Permissions are not well enough handled to test them (see also the other issue about `st_mode`), and the more interesting stuff is indeed `open()` and `io.open()` and the related functionality, and `os.path` functions.

**Comment by agroce** [comment]
We're testing a decent bit of os.path too, right?  isdir, isfile, exists, abspath, dirname, isabs, etc.

Though the paths I provide are thus far really simple.

**Comment by mrbean-bremen** [comment]
You are right, there is already some coverage.
What I really would like to test is `pathlib` as I implemented this one without much testing in the real os (most of the other parts have already been implemented by Mike Bland at Google, at least partly). But that has to wait until Python 3 support...

**Comment by mrbean-bremen** [comment]
About the current issue - I actually implemented this behavior (symlink to directory can be removed in `removedirs`) a couple of days ago for #259. I don't currently see why it has to be different (e.g. the symlink is not deleted) in this case... I see no semantic difference in both tests regarding `removedirs`.
But then I may just be tired - will look at this again another day.

**Comment by agroce** [comment]
I'm at ISSTA for a good part of the next week, but I'll take a look at the semantics here, when I get a chance.  Python os does not really document how removedirs and such interact with symlinks, that I see, and these aren't posix functionality...

**Comment by mrbean-bremen** [comment]
Enjoy the conference! I see you have a talk there,  too.

**Comment by mrbean-bremen** [comment]
Ok, understood my error - the 2 issues were indeed semantically eqivalent regarding `removedirs`, I just didn't correctly fix the first one. I understood that the symlink is removed, which was incorrect.
