### ISSUE TITLE
Ability to return modified file content for each read

### ISSUE THREAD

**Issue by kalidasya** [jmcgeheeiv/pyfakefs#267]
I am testing an application what calculates machine usage by reading the /proc/stat file, I can easily mock it but the problem I ran into is that the app needs modified values for each request (its read in a thread in a 1 sec interval), I could not find an easy way to control what is being returned for each reads besides calling `SetContent` in another thread on the `FakeFile`. Any other way to do that? like a passing a callback or something similar?
Thanks for the help

**Comment by mrbean-bremen** [comment]
I think there is nothing that that would help you with this in pyfakefs, though I think this is a little out of scope for the library. You may have to think about your testing strategy:
- do you really want to use multi-threading in unit tests (note that we do not aim at thread-safety), or could you just split the testing into smaller parts that do not need it?
- can you just mock out the timer to be able to modify the files in the mock out? that could also decrease the test time as you don't have to wait a full second for each change
- if you want to do something like an integration test, pyfakefs may not be the best choice - in that case it is better to use something like a RAM disk that can be cleared after each test

Just my 2 cents - without knowing your application it is difficult to get more specific.

**Comment by kalidasya** [comment]
@mrbean-bremen thank you for your answer, unfortunately this is unit level, the method is part of an snmp library and how it is written the whole file reading and calculating logic is in the `run` method of a `Thread` subclass. I do not really want to refactor it now for testing, but indeed that is maybe the best solution. 
I hoped stubbing consecutive reads is part of the library but maybe in the future can be part of it?

**Comment by mrbean-bremen** [comment]
I may not understand that correctly - what do mean by "stubbing consecutive reads"?
Reads are faked to work with the fake file system, like most of I/O, and you can always stub them out yourself to change the functionality or add additional functionality. Pyfakefs is just about replacing the real fs with the fake fs. Can you elaborate a little about the feature you want to see?

**Comment by kalidasya** [comment]
thanks, sorry this is my first time to use pyfakefs so maybe everything is there. I do not know how can I stub out or what exactly I need to stub. 
My usecase is, I have a class `CpuStats` which has a static function `getIdle()` what returns with a number. The function itself is implementing a moving average with an alternate approach, so it needs the previous value and the current to do the calculation. It is implemented in a way that it reads the /proc/stat in a thread independently from my unit test (async). If the content of the file does not change  I will get `ZeroDivisionError` (as in real life the jiffies are always increased in that file), because it uses the differences in the jiffies in the calculation. My naive approach was use a function what returns the file content for each call so I can make sure its always valid:
```
def generate_cpu_stat():
   # store some state here (amount of calls, test data etc)
   return 'cpu  %s %s %s %s 106698 0 3117 0 0 0' % (USR, NICE, SYS, IDLE)
file = fs.CreateFile('/proc/stat', content=generate_cpu_stat)
```
I tried to monkey patch FakeFile#contents but it does not seem to work, it seems only the initial content is being returned ( I tried subclassing `FakeFile` and setting that class in my instance, or overriding the `FakeFile.contents` in the test script, as its a property I cannot override the instance attribute itself)

**Comment by kalidasya** [comment]
monkey patching byte_contents also wont work as it will set it for `FakeDirectory` as well FakeDirectory#GetEntry calls `contents` what is calling `byte_contents`

**Comment by mrbean-bremen** [comment]
Thanks - I will have another look at this in the evening.

**Comment by mrbean-bremen** [comment]
Ok, the question here is what you want to test in your unit tests.
If you want to test the algorithms used in your static function, I would split that out and provide it with the data as a parameter - then you can run it in a loop, which provides the data you want (without a thread, and without a delay). Your function then has only to read the data, pass it to the algorithm and return the result.
If you want to test reading the data, you can test that separately, but then again, I'm only guessing... 
Depending on what you really want to test, you may not need `pyfakefs` at all - as sorry as I would be about this ;)

**Comment by kalidasya** [comment]
I can understand, its a legacy code what I do not really want to change, I will think about it, thanks for your help

**Comment by mrbean-bremen** [comment]
As an aside, in case you haven't read it - some time ago I read Michael Feather's "Working effectively with legacy code". It has a lot of patterns how to unit test legacy code, and at least for me it was very helpful.

**Comment by kalidasya** [comment]
will check, thanks!

**Comment by mrbean-bremen** [comment]
@kalidasya - can this be closed, or do you need more help?

**Comment by kalidasya** [comment]
can be closed
