### ISSUE TITLE
Multiple FDs on file cause size difference

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#268]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str1 = str0 + 'a' 
str0 = str1 + 'a' 
str1 = str0 + 'a' 
str0 = str1 + 'a' 
str1 = str0 + 'a' 
str0 = str1 + 'a' 
str1 = str0 + 'a' 
str0 = str1 + 'a' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
fd1 = os0.open(path0, os.O_WRONLY | os.O_APPEND) 
os0.write(fd0,str0) 
os0.write(fd0,str1) 
os0.write(fd1,str1) 
result = os0.path.getsize(path0) 

print result

**Comment by mrbean-bremen** [comment]
I was quite sure that multiple FDs bring more surprises. Well, at least I understand the code now.

**Comment by agroce** [comment]
Right, I'll hold off on any further problems here until you get a chance to look at this.  At least the first one reported is fairly complex looking.

PS, using the OS X bug we found testing pyfakefs as my example during my first ISSTA talk, tomorrow.
