### ISSUE TITLE
Unexpected exception raised in read

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#269]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
str0 = "" 
str1 = str0 + 'a' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.write(fd0,str1) 
fd2 = os0.open(path0, os.O_CREAT) 
fd1 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
result = os0.read(fd2,bytes0) 

Yields:

Traceback (most recent call last):
  File "bug44.py", line 25, in <module>
    result = os0.read(fd2,bytes0) 
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 3280, in read
    return file_handle.read(num_bytes)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 4289, in __getattr__
    self._UpdateStringIO()
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 4181, in _UpdateStringIO
    self._io.write(contents)
AttributeError: 'cStringIO.StringI' object has no attribute 'write'

**Comment by agroce** [comment]
Generated while chairing a session at ISSTA :)

**Comment by mrbean-bremen** [comment]
Hey, you are supposed to be busy with your chairing and talks!
Though this one sounds familiar, maybe a regression.
