### ISSUE TITLE
getsize difference with multiple truncates

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#271]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str1 = str0 + 'a' 
str0 = str1 + 'a' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
fd1 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.write(fd1,str0) 
os0.close(fd0) 
result = os0.path.getsize(path0) 

print result

0 for pyfakefs, 2 for real os

**Comment by mrbean-bremen** [comment]
Here we go again... I thought this would be a silent week :)

**Comment by agroce** [comment]
turns out people like seeing it demoed :)

**Comment by mrbean-bremen** [comment]
Ah, that's very convenient! How was your talk accepted?

**Comment by agroce** [comment]
Well -- actually, there was a talk plus a demonstration session.  The difference between the ugly test and the final version after normalization (what I'm sending you guys) is striking.  I also made a few changes to the test harness that'll probably give us slightly nicer tests.

**Comment by mrbean-bremen** [comment]
Thanks for that - your tests are almost usable for the test suite as they are, just a bit of renaming and simplifying does the job.
