### ISSUE TITLE
Read difference with truncates

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#272]
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
bytes0 += 1 
bytes0 += 1 
str0 = "" 
str0 += 'c' 
str0 += 'p' 
str0 += 'l' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
fd1 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
fd2 = os0.open(path0, os.O_CREAT) 
os0.write(fd1,str0) 
os0.close(fd0) 
result = os0.read(fd2,bytes0) 

Probably the same issue as #271 but the only test hit that does not have a getsize involved, and it looks somewhat different.

**Comment by mrbean-bremen** [comment]
Looks basically the same - the buffer of one FD is written on closing and overwrites stuff written later. I have to switch this off for low level i/o, as that is unbuffered.

**Comment by mrbean-bremen** [comment]
I already had done that, just forgot to pass a flag in one place.

**Comment by agroce** [comment]
Clean with multiple FDs, renames, symlinks, after about 1 million test operations while sitting down for a few minutes.

**Comment by agroce** [comment]
Using you guys as an example again tomorrow -- I'm working on methods for composing tests for different parts of a system, so ran an experiment merging directory-operation-only tests with file-operation-only tests.  Worked fairly nicely, though in pyfakefs' case no reason not to just test them together.

**Comment by mrbean-bremen** [comment]
Pity can't see your talks, sounds interesting.

**Comment by agroce** [comment]
I'll send you slides when I'm back home, if you're interested.
