### ISSUE TITLE
Difference in read values

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#273]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
str0 = "" 
str0 += 'm' 
fd1 = os0.open(path0, os.O_CREAT) 
fd2 = os0.open(path0, os.O_RDWR) 
os0.write(fd2,str0) 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
result = os0.read(fd2,bytes0) 
os0.write(fd2,str0) 
result = os0.read(fd1,bytes0) 

print result

Spoke too soon, there was a rather intricate one hiding, still.

**Comment by agroce** [comment]
Failure rate on this one is less than once an hour, so it's pretty low probability, whatever is going on.

**Comment by mrbean-bremen** [comment]
Thanks, I was already worried that I wouldn't know what to do in the evening ;)

**Comment by mrbean-bremen** [comment]
Ok, this is a little obsure, but completely valid - the position in one file handle is after the file end because the file has been truncated by opening another handle, and the next write produces a hole (e..g. a zero byte) in the file.
I will check this tomorrow.

**Comment by mrbean-bremen** [comment]
Took a timeout from pyfakefs today, and may do so for some more days, so if you need something fixed to be able to continue the work, let me know!

**Comment by agroce** [comment]
Sounds good.   If I turn off O_TRUNC, nothing seems to come up, so this may be all that's left with the current testing set.  Extending to "normal" Python file I/O is something that will have to wait until I get some free time to play with this, it's a good deal trickier due to not having a nice module to route the reference through.  You guys are going to want to just "take over" open, etc. right?

**Comment by mrbean-bremen** [comment]
If by "take over" you mean emulate the real behavior similar to `os.open`- right,  that's we try to do (or rather what the original author did).
Give us notice when you have the time. I want to wait for @jmcgeheeiv to get back, before going on with other stuff in `pyfakefs` - I like to have someone to review my code...

**Comment by agroce** [comment]
I was being stupid about how to handle open, just go through FakeFileOpen for everything, ignore patching interface.  Got it wrapped now, may report a few things.

**Comment by mrbean-bremen** [comment]
Ah well, let's see how many "few" will be :)
