### ISSUE TITLE
FakeFileOpen error code

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#274]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
os0.symlink(path0,path0) 
file0 = opener0(path0) 

Has the same IOError where it should be OSError problem as os.open.  I expect to see more of these.  Not devoting much time to it, but suddenly realized testing FakeFileOpen wasn't that difficult, with the right POV.

**Comment by mrbean-bremen** [comment]
Ah ok, not really unexpected. I will have a look somewhere this week.

**Comment by mrbean-bremen** [comment]
Hm, I get OSError with ELOOP here. Isn't that what you expect?

**Comment by agroce** [comment]
Hmm, you're right.  There was some problem, but I can't recreate it when I run this.  I suppose if there's anything real we'll rediscover it.  Can close in the meantime.

**Comment by mrbean-bremen** [comment]
Closing according to last comment.

**Comment by agroce** [comment]
AHA.  I checked, the problem is that I didn't check Python itself.  On OS X, open on ELOOP raises IOError, not OSError.  Does it do the same on windows?  If so, may want to change pyfakefs (even if I think you are more consistent with low level FD based routines) since this will show up again and again in testing.

**Comment by mrbean-bremen** [comment]
Ok, what you are saying is that low/level I/O raises OSError, but high-level IOError? This is consistent with some other exceptions.

**Comment by mrbean-bremen** [comment]
Under Windows this is not an issue, as symlinks are only supported in Python 3, where IOError is an alias to OSError.

**Comment by mrbean-bremen** [comment]
Ok, I confirmed that - IOError for open() under Python 2, OSError for os.open().
