### ISSUE TITLE
FakeFileOpen doesn't raise exception when reading from closed file

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#275]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_EXCL) 
file0 = opener0(path0) 
file0.close() 
result = file0.readline() 

Python normally yields a ValueError for reading from closed file.  Probably this one is a bit of a halter, in that not checking for it means turning off all read value comparisons.

**Comment by mrbean-bremen** [comment]
Right, this is not tested at all - wouldn't have thought it...
Something is wrong with my tests - correct exception is raised, but seen as an error... I will check again another day, obviously I'm just doing something dumb now.
