### ISSUE TITLE
Data loss with multiple open files

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#278]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str0 += 'o' 
str0 += 'v' 
str0 += 'r' 
str0 += 'f' 
str0 += 't' 
str0 += 'f' 
str0 += 'b' 
str0 += 'm' 
str0 += 'g' 
file1 = opener0(path0,'a+') 
file0 = opener0(path0) 
file1.write(str0) 
result = file1.read() 
result = file0.read() 

print result

pyfakefs gets blank, Python returns "ovrftfbmg"

**Comment by mrbean-bremen** [comment]
Under Windows, I also get blank.

**Comment by agroce** [comment]
From Python, or from pyfakefs?

**Comment by mrbean-bremen** [comment]
from Python.
Here is the output in Windows:

```
>>> f1 = open(path0, 'a+')
>>> f2 = open(path0)
>>> f1.write('test')
>>> f1.read()
'\x00\x00\x00\x00\xb0E\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
... (lots of these)
>>> f2.read()
''
```

and in my Ubuntu VM:
```
>>> f1 = open(bp + '/f1', 'a+')
>>> f2 = open(bp + '/f1')
>>> f1.write('test')
4
>>> f1.read()
''
>>> f2.read()
'test'
>>> 
```

This is basically what you get.

**Comment by mrbean-bremen** [comment]
Ok, but in Python 3 under Windows I get the same as under Linux.

**Comment by mrbean-bremen** [comment]
Also, if I remove the first read, I get under Linux the same for the read from f2 (e.g. 'test'), but under Windows the same as for the previous read from f1 (e.g. '' for Python 3 and long string with lots of zeros in Python 2).
Argh....

**Comment by agroce** [comment]
Hmm, I can drop down to testing with one file open at a time, which is more common usage anyway, for a while, and leave this, since it seems like the different Python implementations don't offer up some clean semantics to copy here.

**Comment by mrbean-bremen** [comment]
Yeah, I would appreciate that - this is a can of worms I just don't want to open at the moment...

**Comment by mrbean-bremen** [comment]
With low-level I/O this was easier, e.g. more predictable, because it has no buffering, but the buffered I/O seems to rely on some different OS behavior (maybe, just guessing).
