### ISSUE TITLE
Read on file not open for reading

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#279]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
file0 = opener0(path0,'a') 
result = file0.read(bytes0) 

print result

should fail with IOError exception, but succeeds

**Comment by agroce** [comment]
next, tell, etc. have the same issue -- will hold off on new stuff until the functions map a bit more to open mode, or we won't get much signal in the noise

**Comment by agroce** [comment]
(in particular, next raises a StopIteration when it needs to say the file's not open for reading, I keep hitting, now)

**Comment by mrbean-bremen** [comment]
Ok, I will see if I can fix this in the evening.
