### ISSUE TITLE
Interaction between writing to files and getsize, buffering

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#281]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path0 += "/" + component0
str0 = ""
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
file0 = opener0(path0,'a')
file0.write(str0)
str0 += 'a'
str0 += 'a'
file0.write(str0)
result = os0.path.getsize(path0)

print result

I think pyfakefs behavior is fine (16), but OS returns 0, presumably since getsize is reflecting only what is sync-ed.  Not a major issue, or one in Python OS, except that it is a problem for testing.  Not a bug but for discussion of how to test:  right now only response I see is to test getsize and buffered I/O separately, which is not ideal.

**Comment by mrbean-bremen** [comment]
I will have a look later; we actually simulate the buffering here, but this is probably incomplete. So maybe this one can be fixed.
