### ISSUE TITLE
Read allowed on closed file

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#282]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path0 += "/" + component0
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
file0 = opener0(path0)
file0.close()
result = file0.read()

OS raises exception, pyfakefs lets me read ''

**Comment by mrbean-bremen** [comment]
Ok, this one is a clear bug, but the fix introduces (aka reveals) an error in the tempfile tests, so it may take a litte.
