### ISSUE TITLE
next on file not open for reading

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#284]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path0 += "/" + component0
bytes0 = 0
str0 = ""
str0 += 'a'
file0 = opener0(path0,'w')
file0.write(str0)
file0.write(str0)
file0.seek(bytes0)
file0.next()

OS raises an exception on the .next, pyfakefs does something (and it changes the seek position, which can cause problems later on with writes, so isn't merely harmless failure to fail)

**Comment by mrbean-bremen** [comment]
Ok, this is not implemented.

**Comment by mrbean-bremen** [comment]
The python 2 doc says:
> This method returns the next input line, or raises StopIteration when EOF is hit when the file is open for reading (behavior is undefined when the file is open for writing).

So I'm not sure if this is even a bug (it is certainly a programming bug).
Maybe we should raise `NotImplemented`.
