### ISSUE TITLE
flush on closed file doesn't fail

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#287]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
file0 = opener0(path0,'w') 
file0.close() 
file0.flush() 

This one the issue name pretty much says it all

**Comment by mrbean-bremen** [comment]
Ah well, an easy fix this time - will do this tomorrow. 
BTW - I'm not planning to fix the 3 remaining open issues. If this isn't a problem for you, I'd rather mention them somewhere under known problems and close them - I don't think they have any practical relevance.
