### ISSUE TITLE
tell on open file seems to interfere with buffering simulation

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#288]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
file0 = opener0(path0,'w') 
file0.write(str0) 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
str0 += 'a' 
file0.write(str0) 
result = file0.tell() 
result = os0.path.getsize(path0)

print result

0 vs. 15

the tool produced a bunch of variants of this overnight, but they all seem to have the same pattern of a tell followed by a getsize.  Not quite sure why normalization isn't making them all the same (or shorter, the 'a's don't seem all needed, but I just copied them over from an arbitrary bug).

**Comment by mrbean-bremen** [comment]
Will have a look tomorrow.

**Comment by mrbean-bremen** [comment]
Hm, I get size 0 both on Windows and in pyfakefs, but 15 under Linux. Sems that tell() does a flush under Unix, but not under Windows.
