### ISSUE TITLE
getsize issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#290]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
bytes0 += 1 
bytes0 += 1 
str0 = "" 
str0 += 'a' 
file0 = opener0(path0,'w') 
file0.seek(bytes0) 
file0.write(str0) 
file0.seek(bytes0) 
result = os0.path.getsize(path0) 

print result

A zero from pyfakefs, but os raises an exception that the file isn't there.

**Comment by mrbean-bremen** [comment]
I see other behavior: in pyfakefs 0 is returned, same as you found, but both in Windows and Linux `getsize()` returns 4. I'm not sure, why, too - if just calling the first `seek()` and the `write()`, `getsize()` returns 0, but the second `seek()` seems to flush the buffer.

**Comment by mrbean-bremen** [comment]
Ok, a `seek()` always seems to do a `flush()`, the first `seek()` just had nothing to flush yet. 
Can you confirm that the behavior under MacOS is different?

**Comment by mrbean-bremen** [comment]
I changed the code to conform to Windows and Linux, just have to check what to do with the MacOS behavior.

**Comment by agroce** [comment]
This may well be a Mac OS issue, and I'm not seeing it exactly in tests now.  But another getsize one is about to be submitted, simpler.  Maybe MacOS also, we'll see.

**Comment by agroce** [comment]
Oh, forgot to say -- on OS X the behavior is:

Traceback (most recent call last):
  File "bug1.py", line 33, in <module>
    result = os0.path.getsize(path0) 
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/Volumes/ramdisk/test/alpha'

**Comment by mrbean-bremen** [comment]
Fixed to match Windows/Linux behavior, created separate issue #292 for MacOS.
