### ISSUE TITLE
write then truncate on buffered file getsize difference

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#291]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str0 += 'a' 
file0 = opener0(path0,'a') 
file0.write(str0) 
file0.truncate() 
result = os0.path.getsize(path0) 

print result

**Comment by mrbean-bremen** [comment]
Same as previous issue: the flush is missing in pyfakefs (will fix this), after that it shall behave as in Windows and Linux.

**Comment by mrbean-bremen** [comment]
Fixed to match Windows/Linux behavior, created separate issue #292 for MacOS.

**Comment by mrbean-bremen** [comment]
@agroce - I'm not sure while I referenced this in the other bug - I think I was confused. This one did not raise an exception, right?
