### ISSUE TITLE
Under MacOS, no file system entry is created on opening a file for writing

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#292]
This is a spin-off of #290 and #291.
If creating a file in pyfakefs using `open()` a file system entry is created, so that `os.path.getsize()` can be called on the file.
Under MacOS, `OSError` with `errno.ENOENT` is raised instead, as the entry seems to be created only on close (and maybe other operations like `flush()`).

**Comment by mrbean-bremen** [comment]
@agroce: I wrote this MacOS specific issue, but I don't have a Mac to test. 
I need some more information about the behavior to get this fixed - like: 
- does the new file not exist in the file system at all (is it seen by `listdir()` etc.)? 
- what other functions (besides `close()`) will create the file?

I may wait for @jmcgeheeiv for this one - he has a Mac available. I'm not sure how this bug impacts your testing, though.

**Comment by mrbean-bremen** [comment]
Ok, I tried to fix this under the assumption that only `flush()` (inclusing operations causing a flush like `seek()` and `tell()`) or `close()` will add the open file to the file system under MacOS. This may not be complete - for now I ignored functions like `listdir()`, have to check the real behavior first.

**Comment by mrbean-bremen** [comment]
@agroce: I tested the behavior on a Mac, and couldn't reproduce it. It behaves like Linux here (e.g. no exception raised).
This was under MacOS 10.11.6 (Darwin 15.6.0) and Python 2.7.6, in HFS+.
Can you check how your system differs?

**Comment by mrbean-bremen** [comment]
I will revert the changes for this issue, as it is unclear under which conditions it happens.

**Comment by agroce** [comment]
Will check this soonish, been buried under various things.

**Comment by mrbean-bremen** [comment]
Take your time - it is unlikely that someone will run into this, so this can certainly wait.

**Comment by agroce** [comment]
Tests #290 and #291 work for me on Mac OS 10.12.6.

I have one new looking test signature, related to truncates, submitting now, but I think this seems to be right on Mac now, since truncate variations (and Mac's rename being broken) are all an overnight test run finds.

**Comment by mrbean-bremen** [comment]
So you are saying you don't see this issue? E.g. #290 is not happening on Mac with current master?

**Comment by agroce** [comment]
I don't see either #290 or #291 failing with current master.  Results from pyfakefs and os are the same.  There is the new issue I submitted today.

**Comment by mrbean-bremen** [comment]
Ok, thanks - closing this one in this case.
