### ISSUE TITLE
seek/truncate/seek/getsize issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#296]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
file0 = opener0(path0,'w') 
file0.seek(bytes0) 
file0.truncate() 
file0.seek(bytes0) 
result = os0.path.getsize(path0) 

print result

1 for os, 0 for pyfakefs.  Hope this is the last of these!

**Comment by mrbean-bremen** [comment]
Yeah, these are a little tricky, the behavior is not really predictable - I hope so, too.
And you are at the night shift again!
