### ISSUE TITLE
Seek/truncate/truncate/tell discrepancy

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#298]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

os0 = os
opener0 = open

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
file0 = opener0(path0,'w') 
file0.seek(bytes0) 
file0.truncate() 
file0.truncate() 
result = file0.tell() 

print result

pyfakefs: 3
os: 1

Yes, they are getting more obscure

**Comment by mrbean-bremen** [comment]
Not really - a dumb regression I introduced in the last fix.

**Comment by agroce** [comment]
Ah, man.  I'd have hoped piling up all these TSTL tests in the regression suite would have guarded against those.  Different form of the problem than in the suite, or just didn't run the right test?

**Comment by mrbean-bremen** [comment]
Different form of the problem, hadn't a test for that yet. Well, as I said - I should have seen that one - I'm writing zero bytes into the stream if the truncate position is after the stream end, but forgot to rewind the position in the stream before that.

**Comment by mrbean-bremen** [comment]
All these problems with writing/truncating after a seek outside of the file content had no tests before, there are corner cases.

**Comment by mrbean-bremen** [comment]
And yes, the test suite got certainly larger with your tests, I think I added about 50 tests meanwhile. And writing the tests is easy - just sanitize the variable names, normalize the test code a little more, and find a name for the test.
Just to give you an example.

This is your test:
``` python
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path0 += "/" + component0
str0 = ""
str0 += 'a'
str0 += 'a'
str0 += 'a'
file0 = opener0(path0,'w')
file0.write(str0)
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
str0 += 'a'
file0.write(str0)
result = file0.tell()
result = os0.path.getsize(path0)

print result
```

This is my "normailized" version I used for testing:
``` python
    def test288(self):
        base_path = '/foo/bar'
        self.filesystem.CreateDirectory(base_path)
        file_path = base_path + "/baz"
        f0 = self.open(file_path, 'w')
        f0.write('foo')
        f0.write('bar')
        self.assertEqual(6, f0.tell())
        self.assertEqual(0, self.os.path.getsize(file_path))
```

And this is how it ended up in the test suite:
``` python
    def testTellFlushesUnderPosix(self):
        """Regression test for #288."""
        self.filesystem.is_windows_fs = False
        file_path = 'foo'
        f0 = self.open(file_path, 'w')
        f0.write('test')
        self.assertEqual(4, f0.tell())
        self.assertEqual(4, self.os.path.getsize(file_path))

    def testTellFlushUnderWindowsInPython3(self):
        """Regression test for #288."""
        self.filesystem.is_windows_fs = True
        file_path = 'foo'
        f0 = self.open(file_path, 'w')
        f0.write('test')
        self.assertEqual(4, f0.tell())
        expected = 0 if sys.version_info < (3, ) else 4
        self.assertEqual(expected, self.os.path.getsize(file_path))
```

**Comment by agroce** [comment]
Great!  Some of the data it chooses puzzles me, but it may be even more simple and direct in future tests, did a change to how test reduction works (based on some ideas from my wife, actually).

**Comment by agroce** [comment]
(as in, I don't think all those 'a's were actually needed, and they should have been removed by reduction, I think)

**Comment by mrbean-bremen** [comment]
Ah well, most tests are shorter, I  just had my original test still lying around for this one.
So your wife is into testing, too?

**Comment by mrbean-bremen** [comment]
And your current test reduction works quite nicely, I liked that - I think you had it in your slices from ISTA.

**Comment by agroce** [comment]
The old reduction was good, this one is just a little better (no change to the normalization ISSTA work, this actually just changes the inner loop a bit).

Yes, she is technically a GIS person by background, but a couple of years ago got interested in testing research when she was testing ArcPy (which crashes a lot) and used TSTL.  She's had some very nice ideas since then, and several papers.

**Comment by agroce** [comment]
PS clean on 2 million new tests, without rename (so I don't have to confirm that rename bugs are just OS X acting up).  This is with Python open, no os.open, and only one file open at a time.

**Comment by mrbean-bremen** [comment]
This sounds good! I think rename now behaves good enough, you found quite a lot of problems there. Of the 2 open issues one is MacOS-specific (I won't do anything there now, maybe @jmcgeheeiv will have a look some time later), and one related to multiple files open - I may have another look at this.
Are you going to test more stuff?
Ah, and now I understand how you got to ArcPy testing! How you got to pyfakefs, by the way? Did you use it yourself?

**Comment by agroce** [comment]
I'll probably open up a little more, make sure not missing anything on the "core" here at some point.  I think open + os.open is not going to work unless you guys want to put a lot into fixing it (the already reported issues there).  Any requests for future testing?

I found pyfakefs because I was looking for a way to to file system testing using TSTL -- since Python has a pretty complete interface to POSIX, I wanted something to use as a reference model, without having to hit two "real" file systems (and on Mac, finding ones with different software layers would be hard).  Ended up reversing things, of course, and I guess the concept worked out ok, since it did discover a real OS X issue!

**Comment by mrbean-bremen** [comment]
Ah, so you wanted use it for testing and ending up testing it... good for us! 
I have no specific requests for testing right now, maybe `pathlib` once it works under Python 3. Python 3 has really got a boost with Python 3.5 and seems to be gaining fast.
About `open`/`os.open` - if these are more theoretical corner cases that do not come up in real code, I don't think it is worth to put much work into it, but that is sometimes difficult to decide.

**Comment by agroce** [comment]
Yeah, I need to get TSTL itself 3.0+ ready before tackling any Python 3 libraries, alas, and that'll be a week's work I suspect.
