### ISSUE TITLE
Strange close behavior

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#299]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
file1 = opener0(path0,'w') 
file1.close() 
file0 = opener0(path0) 
file1.close() 
result = file0.read() 

Raises an error claiming file0 is not open for reading, something to do with closing file1 again.  Works fine as expected with os/open.

**Comment by agroce** [comment]
(It looks as if file1 is somehow the "same" object as file0, which with FDs would make some sense but not really here)

**Comment by mrbean-bremen** [comment]
Ok. Looks like the second `close()` closes `f1` because it has the same fd as the `f0` or something like that.

**Comment by agroce** [comment]
Ah, the object doesn't know it's closed, so it allows the close operation to just hit the fd.  Which I guess in a way fits OS -- os doesn't raise an exception on the second close, it just isn't sharing the fd.

**Comment by mrbean-bremen** [comment]
Yes, there is a check missing if it already closed - the os does that.

**Comment by mrbean-bremen** [comment]
Was missing, I mean ;)
