### ISSUE TITLE
Simpler truncate issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#301]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
bytes0 = 0 
bytes0 += 1 
file1 = opener0(path0,'w') 
file0 = opener0(path0) 
file1.seek(bytes0) 
file1.truncate() 
result = file0.read() 
print repr(result)

OS:

'\x00'

pyfakefs:

''

**Comment by agroce** [comment]
Maybe this will show some insight on the other one, since it is a truncate/seek issue but without the only difference being a weird tell change.

**Comment by mrbean-bremen** [comment]
This one looks easier, I actually thought that this was working. This may take some - I have to check if some of the existing tests are incorrect, too (I found at least one ). I also had some problems with my notebook I spent the last evenings with, hopefully mostly solved now.
BTW - you can't take the existing test suite in pyfakefs and test it against the real fs automatically? That would be a really nice test of the tests, at least on your system - but I guess ithis would be too much effort.

**Comment by agroce** [comment]
Sounds good.  That would be really great, but unfortunately it would be a huge effort, since TSTL doesn't help at all.  TSTL generates and understands tests only in its own internal format (where each step in a test is a single choice from a very large finite set of possible actions), and can't "pull in" external tests.  Eventually being able to do so is a long-term goal, but it's a very complex one to make actually work right, and even then it'd have to map into the internal actions to get the "free" comparison with a reference, since that's all based on a series of regexps that translate pyfakefs operations into os operations (they turn out to be very simple transformations here, but in general can be fairly arbitrarily complex).

Trying to think of a simple way to do it without TSTL in the loop, since the behaviors are so similar.  There might be some simple source transform of each test that would turn it into asserts on the operating systems?

**Comment by mrbean-bremen** [comment]
I may think about this - it should actually not be too difficult, but would need some effort. There are some convenience functions that would have to be translated, some tests use fancy path separators to make sure they are not dependent on specific systems, or pretend to be a Windows or Linux system what would not work on the other system. There are already some basic tests against the real fs, but I would like to have a more comprehensive test. Well, something to think about...

**Comment by mrbean-bremen** [comment]
Well, not that easy, I have to rewite the tests for this to work - they have to use some base path as your tests, and the checks have to consider the real path separator. But it can be done for some tests or test classes as needed - I may check this some time later.
