### ISSUE TITLE
Latest 3.3 doesn't seem to be on PyPI

### ISSUE THREAD

**Issue by emauton** [jmcgeheeiv/pyfakefs#304]
I'm working with a project that uses `nosetests` - running that using the pyfakefs 3.2 version available on PyPI fails, but directly installing 3.3 with

    pip install git+https://github.com/jmcgeheeiv/pyfakefs

works out. I spotted this is noted at https://pypi.python.org/pypi/twintrimmer/0.13 as well.

Will 3.3 make it to PyPI sometime soon?

Thanks!

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - I think we are in a good state for a release. What do you say?

**Comment by mrbean-bremen** [comment]
BTW, I checked your failing tests, and it looks like it just expects that the temp directory exists in the fake fiilesystem. In the current version, the temp dir is always created in `setUp()`.

**Comment by emauton** [comment]
Aha, thanks for that!

**Comment by jmcgeheeiv** [comment]
pyfakefs 3.3 is released on PyPi.
