### ISSUE TITLE
Symlink and path ending in "/"

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#307]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
component1 = "" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
path0 += "/" + component1 
os0.symlink(path0,path0) 

os raises an exception:
OSError: [Errno 2] No such file or directory

pyfakefs happily does it

I think symlink has to handle paths in a special way, POSIX req's?

**Comment by mrbean-bremen** [comment]
This one is a little tricky - will handle this later. Have to understand the behavior first....
