### ISSUE TITLE
Case sensitivity (symlink again)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#311]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "beta" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "Beta" 
path2 += "/" + component0 
component0 = "alpha" 
path1 += "/" + component0 
os0.symlink(path0,path0) 
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.link(path1,path2) 

os fails it with Errno 17, pyfakefs allows

**Comment by mrbean-bremen** [comment]
Ah well... I leave that  (and the rest) for another day. Anyway,  this is really helpful and shows the missing test coverage!

**Comment by agroce** [comment]
Yes, it's really making a nice case for looking at the unkilled mutants.  I suspect paths with multiple extra "/" in various positions will also uncover a few more things, once that first tricky one is resolved.
