### ISSUE TITLE
symlink and lstat

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#312]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "Alpha" 
os0.symlink(path1,path0) 
path0 += "/" + component0 
stat0 = os0.lstat(path0)

os does this fine, pyfakefs raises Errno 2

**Comment by mrbean-bremen** [comment]
I don't understand this one. Why should the last `path0` exist? The link is at "../test/alpha", but the check is for "../test/alpha/Alpha". What do I miss?

**Comment by agroce** [comment]
Well, on OS X, pyfakefs is supposed to be not case sensitive, right?

Actually, to make our testing more complete, I should at some point create a case sensitive ramdisk and change the line selecting case sensitivity in initialization of the fake file system locally.

**Comment by mrbean-bremen** [comment]
Well, yes, but I still don't understand it in this case. It should work for  "/Volumes/ramdisk/test/Alpha", sure, but why for  "/Volumes/ramdisk/test/alpha/Alpha"?

**Comment by agroce** [comment]
Follow the symlink -- alpha --> /Volumes/ramdisk/test so that is actually just lstating /Volumes/ramdisk/test/alpha itself, right?

**Comment by agroce** [comment]
the symlink links /Volumes/ramdisk/test/alpha to /Volumes/ramdisk/test so then you expand all but last component links and you're at alpha itself

**Comment by mrbean-bremen** [comment]
Ok, got it - took me some time... thanks!

**Comment by agroce** [comment]
I cheated in that I just ran the TSTL version and saw the state changes, which made clear the symlink chain.

**Comment by mrbean-bremen** [comment]
I had kind of a mental block there... sometimes can't wrap my mind around these symlink chains...
