### ISSUE TITLE
Cases in listdir

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#314]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "b" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "beta" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
os0.symlink(path1,path0) 
path0 += "/" + component0 
component0 = "Beta" 
path1 += "/" + component0 
os0.mkdir(path1) 
os0.rename(path1,path0) 
result = sorted(os0.listdir(path2))

print result

pyfakefs gives ['Beta', 'b']
vs. os ['b', 'beta']

**Comment by mrbean-bremen** [comment]
Renaming a directory to a symlink pointing to the same directory, but with another case... who does such things?
Ok, I know, TSTL...

**Comment by mrbean-bremen** [comment]
I'm waiting for the macos builds in Travis, so will merge this back probably tomorrow.

**Comment by agroce** [comment]
> Ok, I know, TSTL...

That's its job, man.  :)
