### ISSUE TITLE
Symlink / rename complex case issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#317]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "gamma" 
component1 = "c" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
path1 += "/" + component0 
component0 = "Alpha" 
path0 += "/" + component0 
component0 = "a" 
os0.symlink(path2,path1) 
path1 += "/" + component0 
component0 = "f" 
path2 += "/" + component0 
component0 = "phi" 
os0.mkdir(path0) 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "alpha" 
os0.mkdir(path0) 
path0 = "/Volumes/ramdisk/test" 
os0.mkdir(path1) 
os0.symlink(path0,path2) 
path0 += "/" + component0 
os0.rename(path1,path0) 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component1 
os0.mkdir(path0) 
os0.mkdir(path1) 
result = sorted(os0.listdir(path2)) 

print result

os gives ['a', 'alpha', 'c', 'f', 'gamma', 'phi']

pyfakefs gives ['Alpha', 'a', 'c', 'f', 'gamma', 'phi']

**Comment by mrbean-bremen** [comment]
This was actually a dumb regression. Actually TSTL didn't such a good job normalizing in this case - the test boils down to something like:
``` python
    def test317(self):
        self.filesystem.is_case_sensitive = False
        base_path = '/foo/bar'
        self.filesystem.CreateDirectory(base_path)
        self.os.mkdir(base_path + '/Alpha')
        self.os.mkdir(base_path + "/beta")
        self.os.rename(base_path + "/beta", base_path + "/alpha")
        self.assertEqual(['alpha'], self.os.listdir(base_path))
```
Note that `symlink` had noting to do with the problem, and also 3 of the created directories.

**Comment by agroce** [comment]
Hmm, tstl didn't actually normalize it, looks like to me.  Weird.

**Comment by agroce** [comment]
The gamma and c etc. are pretty clear non-normalized test.  Have to look into that.

**Comment by agroce** [comment]
The fix didn't fix yet, by the way -- I see commit referencing this, but it still fails on latest, fyi.

**Comment by mrbean-bremen** [comment]
Ah, I hadn't merged it yet to master, waiting for travis to have it's say. I merged it just now.

**Comment by mrbean-bremen** [comment]
For all case-insensitive stuff, I'm waiting for the Mac builds from Travis CI first, but they have a huge backlog, so it sometimes takes a few hours.
