### ISSUE TITLE
Case and symlink again

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#318]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "Beta" 
component1 = "g" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "f" 
os0.symlink(path1,path0) 
path0 += "/" + component0 
component0 = "beta" 
os0.symlink(path1,path0) 
path0 += "/" + component0 
path1 += "/" + component0 
path2 += "/" + component1 
os0.mkdir(path2) 
os0.rename(path0,path1) 
result = sorted(os0.listdir(path0)) 

print result

case difference in the sorted directories

['beta', 'f', 'g']

vs.

['Beta', 'f', 'g']

**Comment by mrbean-bremen** [comment]
So, you get 'Beta' under MacOS? Under Windows, I get 'beta', same as in pyfakefs.

**Comment by agroce** [comment]
Definitely get "Beta" on Mac.

**Comment by mrbean-bremen** [comment]
hm, ok, may check this later...

**Comment by agroce** [comment]
Here is what I think is the same issue, just much simpler:

import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "beta" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "Beta" 
os0.symlink(path1,path0) 
path0 += "/" + component0 
path1 += "/" + component0 
os0.rename(path0,path1) 
result = sorted(os0.listdir(path0))

print result

os yields ['beta'] vs pyfakefs ['Beta']

Normalization can't change the "beta"s to "alpha"s because you'd need to change both at once, but otherwise this one's fully normalized.  The other one is less so due to a heuristic of trying to keep the exception matching as fully as possible, which isn't quite working right here.

**Comment by mrbean-bremen** [comment]
Hm, that is indeed the stripped down version of that problem - nice normalization!
Still, I don't get the logic here - the rename sees to do nothing. For me, the Windows (and pyfakefs) behavior seems more logical, doing the renaming.
