### ISSUE TITLE
Another symlink/rename case sensitivity issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#319]
import pyfakefs.fake_filesystem
import os

if os.path.exists('/Volumes/ramdisk/test'):
    shutil.rmtree('/Volumes/ramdisk/test')
os.mkdir('/Volumes/ramdisk/test')

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "e" 
component1 = "Alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
path1 += "/" + component0 
component0 = "alpha" 
os0.symlink(path0,path1) 
path0 += "/" + component0 
path1 += "/" + component1 
os0.mkdir(path1) 
os0.rename(path1,path0) 
result = sorted(os0.listdir(path2)) 

print result

['Alpha', 'e'] for pyfakefs
['alpha', 'e'] for os

**Comment by mrbean-bremen** [comment]
Yes, I was afraid there are more of these - I didn't really get the logic behind that behavior yet.

**Comment by mrbean-bremen** [comment]
Hm, returns 'alpha' for me both in pyfakefs and Windows. Do you have the latest version?

**Comment by mrbean-bremen** [comment]
Ah, wait, I made an error in the test...

**Comment by agroce** [comment]
Grabbed again, there were some changes, but it still fails for me on OS X

**Comment by mrbean-bremen** [comment]
Yes, you are right - my bad, I messed up the test.

**Comment by mrbean-bremen** [comment]
It works under Windows, fails just under MacOs - the change I made specifically for MacOS was too generic, apparently.

**Comment by mrbean-bremen** [comment]
I will wait for Travis before merging this back, so that will probably be only tomorrow.
