### ISSUE TITLE
complex symlink/rename chain (no case sensitivity or path separator oddities involved)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#321]
```
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = "/Volumes/ramdisk/test" 
path2 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
path0 += "/" + component0 
path1 += "/" + component0 
component0 = "beta" 
path0 += "/" + component0 
path2 += "/" + component0 
str0 = "" 
os0.symlink(path0,path2) 
path0 += "/" + component0 
path2 += "/" + component0 
os0.makedirs(path0)
try:
    os0.rename(path1,path2)
except:
    pass
fd0 = os0.open(path0, os.O_CREAT) 
os0.write(fd0,str0)
```

This one is ugly.  Only found it when investigating unkilled mutants, realized one mutant required particularly deep symlink chains, and the way to get that was to crank the depth of tests up to 1,000 operations.  Doing that fairly quickly produced this test.

The failed rename corrupts something in the underlying representation (in fact, this rename is the same kind of "bad rename" that OS X handles incorrectly!), and you get a weird exception thrown by the write call as a result:

Traceback (most recent call last):
  File "bug60.py", line 35, in <module>
    os0.write(fd0,str0) 
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 3423, in write
    file_handle._sync_io()
AttributeError: 'FakeDirWrapper' object has no attribute '_sync_io'

**Comment by mrbean-bremen** [comment]
Ah, ok, this one is not so complicated and does not need symlinks at all:
``` python
    def test321(self):
        self.checkPosixOnly()
        path0 = self.makePath("alpha")
        self.os.mkdir(path0)
        fd0 = self.os.open(path0, os.O_CREAT)
        self.os.write(fd0, "")
```
The problem is simply that writing to a directory is not supported/implemented. How does it behave under MacOS?

**Comment by agroce** [comment]
AHA.

Nasty.  The problem was that

1) I guard in the harness against trying to write to a directory
2) But my guard, until just now, actually uses os.path.isdir, not the fake OS module's .path.isdir.  After the bad rename, the Mac OS X information is wrong, so my harness carries on and writes to a directory.  Fixed now.

**Comment by agroce** [comment]
(so not really a bug)

**Comment by agroce** [comment]
The symlinks etc. are to get the OS X system to lie about directory status.

**Comment by mrbean-bremen** [comment]
Ah, I see - so it was complicated anyway. I'm not sure though what should happen in this case - should it throw OSError with errno.EISDIR or something?

**Comment by agroce** [comment]
Yeah, dying with an AttributeError does seem bogus.  Is there some Python equivalent idiom of throwing NotImplemented?

**Comment by mrbean-bremen** [comment]
The python equivalent is throwing NotImplementedError ;)
Anyway, I would rather raise the same as under Posix, just don't have a Linux running right now. What does MacOs say if you just try to write to a directory? E.g. what happens after
``` python
path = '/Volumes/ramdisk/test/alpha'
os.mkdir(path)
fd0 = s.open(path, os.O_CREAT)
os.write(fd0, "")
```

**Comment by agroce** [comment]
Aha.  I was thinking POSIX did allow this, but it doesn't.  So it is a bug, just a simple one in a way, that was being hidden by the way I guard writes.

OS X does OSError: [Errno 9] Bad file descriptor

**Comment by mrbean-bremen** [comment]
ah, ok - pyfakefs does this if removing the call to `mkdir` before `os.open`. I first thought, that it is not needed, but without it, pyfakefs behaves correctly.

**Comment by mrbean-bremen** [comment]
Though I would have thought that `os.open` with `O_CREAT` should fail on an existing directory...

**Comment by mrbean-bremen** [comment]
Ok, I rebooted into Linux to check this. With an existing directory, OSError - IsADirectoryError is raised on `os.open`, without it OSError - Bad file descriptor in `os.write`, as in pyfakefs.

**Comment by mrbean-bremen** [comment]
So, to summarize the behavior: opening a directory in write mode fails both in Linux and MacOS (opening a directory in Windows is not possible at all) - this is covered in pyfakefs.
Opening a directory in create mode (O_CREAT) fails in Linux, but works in MacOS - this is also covered now.
Writing to a directory is not possible in Linux, because it cannot be opened in write mode, and shall raise EBADF under MacOS (I will add this).
