### ISSUE TITLE
Patcher context manager doesn't return an object

### ISSUE THREAD

**Issue by jvuori** [jmcgeheeiv/pyfakefs#323]
Despite of what's documented Patcher object is not returned by `__enter__` so the following code doesn't work:
```
from pyfakefs.fake_filesystem_unittest import Patcher


def test_context_manager():
    with Patcher() as patcher:
        assert patcher
```

Fakefs 3.2
Python 3.6
Windows 10

**Comment by mrbean-bremen** [comment]
You are right - this is a bug in the documentation - or rather, in the implementation, as it really should work that way.

**Comment by jvuori** [comment]
Wow! That was fast! 👍
