### ISSUE TITLE
Mixed case drive letters don't work

### ISSUE THREAD

**Issue by jvuori** [jmcgeheeiv/pyfakefs#324]
Populating content into multiple directories with mixed case drive letters causes pyfakefs to crash:
```
from pyfakefs.fake_filesystem_unittest import Patcher


def test_drive_letter_case():
    fs_patcher = Patcher()
    with fs_patcher:
        fs_patcher.fs.CreateFile(r'c:\dir1\test.txt')
        fs_patcher.fs.CreateFile(r'C:\dir2\test.txt')

```

`FileExistsError: [Errno 17] Directory exists in fake filesystem: 'C:'`

Pyfakefs 3.2
Python 3.6
Windows 10

**Comment by mrbean-bremen** [comment]
I think this one is fixed in the current master - could you check that?

**Comment by jvuori** [comment]
You are right. I used the version found from PyPI. After changing my requirements.txt to `git+git://github.com/jmcgeheeiv/pyfakefs.git` the test case started to work. Also my real use case scenario started to work.

Thank you!

**Comment by mrbean-bremen** [comment]
You are welcome! Can we close the issue, then?
