### ISSUE TITLE
Fake Filesystem Never Empty. There Is Always Folder '/var/folders'

### ISSUE THREAD

**Issue by Quibi** [jmcgeheeiv/pyfakefs#329]
Before pyfakefs 3.3 (3.2 and above), it is possible to check that the fake filesystem is empty and only has the root directory /. A simple scandir() was enough.

However, **since version 3.3** the fake filesystem is not really empty any more. **There is always a '/var/folders' directory**. Why?

I think that a best solution —the ideal one, I must say— will be that the fake filesystem is really empty, except for root directory. **Any file or folder must exist only if you create it**. That was the behaviour of pyfakefs till 3.3.

In my case, it causes a lot of errors in my tests. scandir, ListDir, glob, etc. does not returns expected results any more...

Pyfakefs 3.3
Python 3.6.3
MacOs 10.6.2

Thanks a lot

**Comment by jmcgeheeiv** [comment]
Test `testNewFilesystem()` in `fake_filesystem_test.py` checks that the new file system is empty.

Further, I searched for "var" and "folders" in the source code and found nothing unusual.

Could you please provide code that demonstrates the problem?  Thank you.

**Comment by mrbean-bremen** [comment]
That is due to the fact that the temp directory is now always created in `setUp()` (under MacOS it is located under `/var/folders`). The reason for this is a technical one - the `tempfile` module is no longer faked out (the fake implementation was incomplete anyway), instead the real module is used with the fake file system. The real `tempfile` module relies on the existence of the temp directory, as may some other modules (see #304 for an example), so we now create it in `setUp()`. I didn't realize that this could break existing tests, so it is not mentioned specifically in the release notes. 

I still think that this is more expected behavior then a bug, but you are right of course, that it breaks tests relying on the old behavior. I can think of  2 solutions, both not ideal: add some function in `pyfakefs` that changes the behavior back to not creating the `temp` path (could break tests that use `temofile`), or provide an additional function that checks for an empty file system  (needs more changes to the existing tests). If you are using `fake_filesystem_unittest`, you could also use your own derived test class, that removed the temp path in `setUp()`.

What do you think? 

And thanks for the fast report BTW, with 3.3 only just released!

**Comment by jmcgeheeiv** [comment]
Aha.

**Comment by Quibi** [comment]
Thank you for your remakes, @jmcgeheeiv and @mrbean-bremen.

I am currently doing some additional research on this issue (mainly in order to provide a useful example).

For the moment, I have found that the files in /var/folders that my tests found, there exist in the real filesystem (sorry, I must check this earlier).

My first suspicion was that I am not really mocking the filesystem in my tests any more. But I disregarded this hypothesis since the tests just see the /var folder on the root directory and just the files inside /var/folder directory, not the whole real filesystem.

Maybe it is related to the facts mentioned by @mrbean-bremen. I should check it.

If you please, I like to put this issue on hold till I can collect additional information and can provide a useful example.

Thanks.

**Comment by Quibi** [comment]
Ok. I have crafted the code below.

It is unittest suite with three tests:

- `test_is_mocked`: that checks if the suite has really mocked the real filesystem and it is using pyfakefs package.

- `test_is_empty`: that checks if the fake filesystem is empty (and fails because of /var).

- `test_contents_after_creating_file`: that checks that the fake filesystem is not empty and contains a newly created file (and also fails because of /var).

This is the (long) script (can also be watched at [gist](https://gist.github.com/Quibi/b40eab879fe19b15070d98e2b3ba2a4f)):

```
"""Test that the fake system is empty.

Tests that the fake system is empty before
creating any file or folder.

A empty fake filesystem must contain only
the root directory.

Currently, test_empty() method should fail
since there is a '/var' folder in the fake tree.

"""

import sys

import unittest

import os
import pathlib

from pyfakefs import fake_filesystem
from pyfakefs import fake_pathlib
from pyfakefs import fake_filesystem_unittest

class EmptyFakeFilesystemTestCase(fake_filesystem_unittest.TestCase):

    def setUp(self):

        self.maxDiff = None
        self.setUpPyfakefs()
        unittest.TestCase.setUp(self)


    def test_is_mocked(self):
        """Test if the filesystem is really mocked."""

        self.assertEqual(
            type(os).__name__, 'FakeOsModule',
            "The os package has not been mocked."
        )

        self.assertEqual(
            type(pathlib).__name__,
            fake_pathlib.FakePathlibModule.__name__,
            "The pathlib package has not been mocked."
        )

        self.assertEqual(
            type(pathlib).__name__,
            "FakePathlibModule",
            "The pathlib package has not been mocked."
        )


    def test_is_empty(self):
        """Test if fake filesystem is empty.

        A filesystem is empty if it only contains
        the root directory.

        """

        # a way to get the root directory

        root = pathlib.Path(pathlib.Path().resolve().anchor)

        # get all files and folders including root
        # from filesystem

        fake_ls = sorted(list(root.glob("**/*")) + [root])

        # output all files and folders list
        # just for human check

        print()
        print()
        print(f"All files and folders at '{str(root)}:'")
        print()
        [print(f'\t{file}') for file in fake_ls]
        print()
        print()

        # expected fake filesystem

        expected = [root]

        # assertion fails under pyfakefs 3.3 on MacOs 10.12.6

        self.assertEqual(
            fake_ls, expected,
            'The list of all files and folders is not the expected one.'
        )


    def test_contents_after_creating_file(self):
        """Test the contents after creating a file.

        The fake filesystem must contain the root directory,
        the parent folder of the new file, and the file itself.

        """

        # a way to get the root directory

        root = pathlib.Path(pathlib.Path().resolve().anchor)


        # create a file with touch

        pathlib.Path(root, 'foo').mkdir()  # first make directory

        new_file = pathlib.Path(root, 'foo', 'spam.egg')
        new_file.touch()

        # get all files and folders including root
        # from filesystem

        fake_ls = sorted(list(root.glob("**/*")) + [root])

        # output all files and folders list
        # just for human check

        print()
        print()
        print(f"All files and folders at '{str(root)}:'")
        print()
        [print(f'\t{file}') for file in fake_ls]
        print()
        print()

        # expected fake filesystem

        expected = sorted(
            [
                root, new_file.parent, new_file
            ]
        )

        # assertion fails under pyfakefs 3.3 on MacOs 10.12.6

        self.assertEqual(
            fake_ls, expected,
            'The list of all files and folders is not the expected one.'
        )


def suite():
    return unittest.TestLoader().loadTestsFromModule(sys.modules[__name__])


def main():
    return unittest.TextTestRunner(verbosity=2).run(suite())


if __name__ == '__main__':
    main()

```

The output on my system is this (from IDLE):

```
test_contents_after_creating_file (__main__.EmptyFakeFilesystemTestCase)
Test the contents after creating a file. ... 

All files and folders at '/:'

	/
	/foo
	/foo/spam.egg
	/var
	/var/folders
	/var/folders/_g
	/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn
	/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T


FAIL
test_is_empty (__main__.EmptyFakeFilesystemTestCase)
Test if fake filesystem is empty. ... 

All files and folders at '/:'

	/
	/var
	/var/folders
	/var/folders/_g
	/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn
	/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T


FAIL
test_is_mocked (__main__.EmptyFakeFilesystemTestCase)
Test if the filesystem is really mocked. ... ok

======================================================================
FAIL: test_contents_after_creating_file (__main__.EmptyFakeFilesystemTestCase)
Test the contents after creating a file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jv/Downloads/pyfakefs_var_folder_test.py", line 143, in test_contents_after_creating_file
    'The list of all files and folders is not the expected one.'
AssertionError: Lists differ: [Posi[52 chars]egg'), PosixPath('/var'), PosixPath('/var/fold[155 chars]/T')] != [Posi[52 chars]egg')]

First list contains 5 additional elements.
First extra element 3:
PosixPath('/var')

+ [PosixPath('/'), PosixPath('/foo'), PosixPath('/foo/spam.egg')]
- [PosixPath('/'),
-  PosixPath('/foo'),
-  PosixPath('/foo/spam.egg'),
-  PosixPath('/var'),
-  PosixPath('/var/folders'),
-  PosixPath('/var/folders/_g'),
-  PosixPath('/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn'),
-  PosixPath('/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T')] : The list of all files and folders is not the expected one.

======================================================================
FAIL: test_is_empty (__main__.EmptyFakeFilesystemTestCase)
Test if fake filesystem is empty.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jv/Downloads/pyfakefs_var_folder_test.py", line 91, in test_is_empty
    'The list of all files and folders is not the expected one.'
AssertionError: Lists differ: [PosixPath('/'), PosixPath('/var'), PosixPath('/var/fold[155 chars]/T')] != [PosixPath('/')]

First list contains 5 additional elements.
First extra element 1:
PosixPath('/var')

- [PosixPath('/'),
?                ^

+ [PosixPath('/')]
?                ^

-  PosixPath('/var'),
-  PosixPath('/var/folders'),
-  PosixPath('/var/folders/_g'),
-  PosixPath('/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn'),
-  PosixPath('/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T')] : The list of all files and folders is not the expected one.

----------------------------------------------------------------------
Ran 3 tests in 1.472s

FAILED (failures=2)
```

As you can see, there are some subfolders in '/var'.

As I have mentioned in a previous reply, those folders actually exist in the real filesystem. There are also more (real) folders in '/var', in '/var/folders', etc. There are even more (real) folders and files inside '/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T', the deepest folder according to pyfakefs. As you can see, none of these files and folders are scanned by pyfakefs.

I am really confused since I do not know anything useful about /var folder on MacOs beyond that is a system folder (don't touch it!).

Thanks.

**Comment by Quibi** [comment]
Thanks @mrbean-bremen. I think that you are right.

I had written additional comments on this issue (providing an example and some outputs). However, after rereading your answer (and better understanding it), I have deleted those comments. Your answer fully explains the issue in my opinion.

I cannot say that this (new) expected behaviour is the best one for a package mocking the filesystem. **I rather prefer a mock that only creates those files and folders that are commanded to do**.

I understand that there are some trade-offs and some implementation decisions that, of course, I am not able to catch as a seasonal programmer.

So it is fine. I will refactor my tests to fulfil the new behaviour.

Thanks you and @jmcgeheeiv for this nice and useful package.

**Comment by mrbean-bremen** [comment]
I had a look at your results, and I have no idea, where these files come from - this seems to be a location where some caches are stored under MacOS (not the temp directory, actually), and someone must be writing them after `setupPyfakefs()`, but I can't understand who from your code. You can always set a breakpoint in the file creation code in pyfakefs to check where that comes from.
Anyway, I think it is not a good idea to assume that you have full control over the contents of the fake file system, as nobody prevents some python libraries to create files in the system cache or temp directories that then end up in the fake file system.

**Comment by Quibi** [comment]
>I think it is not a good idea to assume that you have full control over the contents of the fake file system, as nobody prevents some python libraries to create files.

I have not thought about that. You are right: the filesystem can be written by other modules as well. Nobody should expect that a fake filesystem is still empty after a while because of that.

However, in my tests, I usually check that the filesystem is empty just after "creating" the fake filesystem or immediately after deleting all files. So I think that the problem that you mentioned does not apply here, in my tests. Maybe I am wrong about that assumption.

On the other hand, **I have made the "breakpoint test"**. The "results" are:

- `temp_dir is` set to '/var/folders/_g/00pdg6k10y90x6g2wfp6z8h00000gn/T' (That's correct, I suppose).
- at fake_filesystem_unittest.py:402, the value of `self.fs.root.contents = {}` (So filesystem is empty at that point: Patcher.SetUp() just after calling _refresh method.)
- after fake_filesystem_unittest.py:426, the temp directory has been created. So `self.fs.root.contents` is no longer empty and contains the folder /var.

Does this provide useful information to you? Should I perform any additional debugging to get more data?

**Comment by mrbean-bremen** [comment]
Ok, thank you - I wasn't aware that the temp folder location under MacOS is that cryptic (certainly hasn't been this way the time I have worked with it).
I understand your problem, but I still think it would be better to restrict your tests to the part of the file system you are working with. The first test you make is basically just testing that pyfakefs is working - that should not be your job ;) And if you are testing anything using pyfakefs, the location you will be testing should be the same as in the real fs - so it usually makes no sense to check the content of `/` (or `/var`, for that matter). 
What do you think?

**Comment by Quibi** [comment]
Sorry for resurrecting this issue. I have made some further investigation and I would like to propose some minor changes in the package.

First of all, I would like to say that an **initial empty fake filesystem is a desired feature for me**. So I have tried to revert the actual behaviour to previous one in versions above 3.3. **If you consider that this is not a desirable feature, this patch is worthless**.

My proposal is to **delay the creation of the fake temporary directory until it is actually requested**. To achieve this, I propose to **stub the `tempfile._sanitize_params()` method** which is called, among other things, to set the default directory where a temporary folder or file would be created.

The stub method `_sanitize_params` checks if the temporary directory already exists, and if not, created.

The proposed alternative passes the tests of `pyfakefs` package.

I have made modifications in `fake_filesystem_unittest.py` and in `fake_filesystem_unittest_test.py`. The former was modified to include the hack while the latter includes an additional test for checking that initial filesystem is empty (not really needed).

Both files can be seen at https://gist.github.com/Quibi/05ba9afeb94994123dcfd0bb1e7bbb1f.

Changes can be searched by '# HACK' for convenience.

In my opinion, the **advantages** of this approach are:

- Initial empty fake filesystem.

- Fake temporary directory is created just once needed.

- No need to mock all `tempfile` package as proposed in #191

- Since `tempdir.gettempdir()` is not stubbed, the user can delete and re-create the temporary directory as it would be in his own OS when ever he wants.

The **disadvantages** I can imagine are:

- A slightly complicated if compared with correct implementation. Among other things, it needs to create and use a flag called `__create_temp_dir` to avoid that the fake temporary directory was created more than once (e.g. after being deleted the temporary directory and call for a new temporary file —in this case, a test should fail, for instance). This is not nice.

- Additional tests on tempdir may be needed. Actual tests are passed and I carefully scanned the source of `tempfile`, but I can assure that this hack will work in any possible situations (instead, the current implementation does).
 
- No temporary directory in fake filesystem if expected (minor since that was not the expected behaviour in previous version).

Thank you.

**Comment by mrbean-bremen** [comment]
That sounds reasonable to me. I currently don't have  a working PC at home  (my hard disk finally died today), so I can't check this very well -  but you may just create a pull request and we can go from there. It will take me a few days to get back to that, so take your time ;)

**Comment by Quibi** [comment]
Ouhh. Hard drives... Sorry about that.

My first pull request. It will be a great new experience...
