### ISSUE TITLE
Pyfakefs doesn't work with Python 2.6+ backport of os.scandir

### ISSUE THREAD

**Issue by OskarPersson** [jmcgeheeiv/pyfakefs#332]
pyfakefs doesn't work with [the backport](https://github.com/benhoyt/scandir) of [`os.scandir`](https://docs.python.org/3.6/library/os.html#os.scandir) Is this possible or does it have the same [limitations as lxml](https://github.com/jmcgeheeiv/pyfakefs#compatibility)?

Currently the backport, just like in #119, doesn't find any directories created by pyfakefs and raises an OSError:

```
OSError: [Errno 2] No such file or directory: 'root'
```

**Comment by mrbean-bremen** [comment]
Yes, unfortunately it has the same limitations as lxml. The backport is a C based module, and thus cannot be faked without explicit support in the library. Currently, we have no support for any non-standard libraries, and I'm not sure if that would be in the scope of this package. @jmcgeheeiv - what do you think?

**Comment by jmcgeheeiv** [comment]
If it's C/C++, it is technically infeasable to patch it and fake it.

**Comment by mrbean-bremen** [comment]
Well, we could fake it the same way we fake `os`, I'm just not sure if this is the way to go. We already have a fake implementation of `os.scandir`, so that could be used in this case, e.g. we would have to fake out the `scandir` module in case it is available.

**Comment by mrbean-bremen** [comment]
I have thought about this a little more, and I think that we can refactor `Patcher` a little to be able to add other faked modules without the need to directly reference them in the patcher itself. 
I may have a go at this after the pep8 stuff is merged.

**Comment by mrbean-bremen** [comment]
@OskarPersson - please check if this works for you and reopen otherwise.
Just learned that mentioning the issue in the PR description (not in the commit message) also auto-closes it...

**Comment by OskarPersson** [comment]
Hmm, no I can't get it to work :/

I cloned the master branch, created a new Python 2.7.14 virtualenv, pip installed scandir and tested with `python all_tests.py`. This resulted in 8 errors, all with the same traceback:

```
======================================================================
ERROR: testIndexAccessToStatTimesReturnsInt (fake_filesystem_test.FakeScandirTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oskar/git/pyfakefs/fake_filesystem_test.py", line 4832, in setUp
    from fake_scandir import scandir
ImportError: No module named fake_scandir
```
---

I also tried setting up a simple test in `example_test.py`:

```

from scandir import scandir

def test_scandir_backport(self):
    self.fs.CreateFile('/test/text.txt')
    self.assertEqual(len(list(scandir('/test'))), 1)
```

This results in the following error:

```
=====================================================================
ERROR: test_scandir_backport (example_test.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oskar/git/pyfakefs/example_test.py", line 152, in test_scandir_backport
OSError: [Errno 2] No such file or directory: '/test'
```

**Comment by mrbean-bremen** [comment]
Ok, I will check this tomorrow, if I find the time.

**Comment by mrbean-bremen** [comment]
Ok, several things here:
- the `from scandir import scandir` will generally not work under pyfakefs, you have to `import scandir` (there is the possibility to enable the dynamic patcher to fix this, but this is experimental and breaks at least `pytest`)
- the example will not work that way - you have to add the tested code to the "sut", which is `example.py`; I adapted the existing example to also work with the `scandir` module
- there was a syntax error in the other test, which I did not catch, because I tested under Windows, where the test was disabled (I overlooked this)
- there was a real bug in the implementation - it did not work under Python 2 due to changed syntax for `next` in the iterator (`__next__` vs `next`)

**Comment by OskarPersson** [comment]
From my tests this seems to work now, thanks!

**Comment by mrbean-bremen** [comment]
Glad to hear that!
