### ISSUE TITLE
When 'Path' from 'pathlib' is imported, it isn't faked.

### ISSUE THREAD

**Issue by godfried** [jmcgeheeiv/pyfakefs#344]
Hi, 

When I import `Path` from `pathlib`, it isn't faked. However, when I import `pathlib`, and use it with `pathlib.Path`, it is.
Example reproducing the issue (home shouldn't exist since it is faked):
```
>>> from pyfakefs.fake_filesystem_unittest import Patcher
>>> from pathlib import Path
>>> import pathlib
>>> with Patcher() as patcher:
...     h1 = Path.home()
...     h2 = pathlib.Path.home()
...     print(h1.exists())
...     print(h2.exists())
... 
True
False
```
Using:
`pyfakefs==3.3`
`Python 3.6.3`
`Ubuntu 17.10`
Reproduced on latest version of master.
I tried to identify the root cause myself, but I'm afraid I couldn't make any headway. 
If you could point me in the right direction I'd be happy to attempt to fix it.

**Comment by mrbean-bremen** [comment]
Hi,
short answer - this is a well-known limitation of `pyfakefs` (or rather a known but undocumented one). There are only a few imports that are faked retrospectively (e.g. after the modules are loaded), as this has to be done name-based, so in this case, `pathlib` is faked, but `Path` is not.
So, if you have the control over the code, you can just use the less convenient long form. 

Longer answer:
If the module is loaded only inside the test, it should be faked anyway if `use_dynamic_patch` is set to `True` (this is the default in the master, but not in the released version):
``` python
from pyfakefs.fake_filesystem_unittest import Patcher

with Patcher(use_dynamic_patch=True) as patcher:
    from pathlib import Path
    
    print(Path.home().exists())
```
If the import happens in another module in the SUT (the normal case), there is also the possibility to reload this module in the test - there is a `modules_to_reload` argument both in `Patcher` and in `TestCase` that can be used for this. Something like this should work, at least in master:
sut.py:
``` python
from pathlib import Path

def home_exists():
    return Path.home().exists()
``` 
test.py
``` python
import sut

with Patcher(modules_to_reload=[sut])
    print(sut.home_exists())
```
Note that this feature is tagged as experimental in the released version, there has been a bug in `tearDown` handling. In master, this has been fixed, and I actually was planning to add something like the above to the documentation next weekend.

One final note: I was also thinking about adding the possibility to add faked module names to the patcher, that would look something like `Patcher(additional_fake_modules={'Path', FakePathModule}`, where `FakePathModule` would be a simple stub forwarding to `FakePathlibModule` in this case. That would have less possible side effects than reloading the module, but would avoid faking any module named `Path` for all users.

**Comment by godfried** [comment]
Thanks for the prompt and detailed explanation.
Could this limitation be added to the wiki/readme?
I do have control over the code, so it isn't really an issue for me.
That last solution looks like ideal.
Thank you for the great work as well.

**Comment by mrbean-bremen** [comment]
You are welcome :)
I added some documentation in http://jmcgeheeiv.github.io/pyfakefs/master/intro.html#limitations, I may clean this up before the next release.
