### ISSUE TITLE
CreateDirectory with fake directory content

### ISSUE THREAD

**Issue by gsemet** [jmcgeheeiv/pyfakefs#347]
Hello

Is it possible to have a mix of `CreateDirectory` and `add_real_directory`, where I can define a fake directory but matching the content of an existing directory (but not with the same path)?

I am looking for an equivalent of this code:
```python
def map_directory(fs, real_dir: Union[str, Path], fake_path: Union[str, Path]):
    if isinstance(real_dir, str):
        real_dir = Path(real_dir)
    if isinstance(fake_path, str):
        fake_path = Path(fake_path)
    fs.CreateDirectory(str(real_dir))
    for fil in real_dir.iterdir():
        if not fil.is_file():
            continue
        with fil.open() as f:
            fake_fil = fake_path / fil.name
            log.debug("Mapping fake file", real_path=str(fil), fake_path=str(fake_fil))
            fs.CreateFile(str(fake_fil), contents=f.read())
```

thanks

**Comment by mrbean-bremen** [comment]
No, that is not possible directly.
We could add an additional `destination` argument to `add_real_directory()` and `add_real_file()` (but probably not to `add_real_paths()`).

**Comment by mrbean-bremen** [comment]
Ok, I added a new argument `target_path` in master - please check, if this is what you need.

**Comment by gsemet** [comment]
looks great !
