### ISSUE TITLE
pyfakefs 3.4 - fs.add_real_paths fails to add the paths correctly (compared to 3.3)

### ISSUE THREAD

**Issue by TonyFlury** [jmcgeheeiv/pyfakefs#357]
I have a test cases which works well under pyfakefs 3.3, but which fails under 3.4

The test cases adds a real path to the fake file system - as follows : 

        with Patcher() as patcher:
                patcher.fs.add_real_paths([pkg_resources.resource_filename('cataloger','templates')])

Where 'cataloger' is the package under test.

Later the code under test attempts to open a file at this path:

      os.path.join(pkg_resources.resource_filename('cataloger','templates'),'final_create.tmpl')

The 'final_create.tmpl' file exists in the relevant directory.

Under pyfakefs 3.4, opening this file fails with the exception:
         [Errno 2] No such file or directory in the fake filesystem: '/home/tony/Development/python/cataloger/cataloger/templates/final_create.tmpl'

Under pyfakefs 3.3 with all code the same - the file opens correctly with the expected contents.

**Comment by mrbean-bremen** [comment]
Can you please check with master? This should have been fixed already.

**Comment by TonyFlury** [comment]
yes - the master does work - when will this master get pushed to pypi as a bug fix release ?

**Comment by mrbean-bremen** [comment]
I was thinking to do it in about a week, in case something else comes up, but maybe I will do it tomorrow instead, as this issue now came up the second time in a few days.

**Comment by TonyFlury** [comment]
That would be great thanks - amazing package BTW

**Comment by mrbean-bremen** [comment]
Thanks - tomorrow it will be then :)

**Comment by mrbean-bremen** [comment]
Ok, done.
