### ISSUE TITLE
mismatch in readlink results (MacOS only)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#392]
```
import shutil
import pyfakefs.fake_filesystem
import os

ROOT_PATH = "/Volumes/ramdisk/test"

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

if False:
    os0 = os
    shutil.rmtree(ROOT_PATH)
    os.mkdir(ROOT_PATH)

component0 = "alpha" 
component1 = "" 
path0 = ROOT_PATH 
path1 = ROOT_PATH 
path1 += os.path.sep + component0 
component0 = "beta" 
path0 += os.path.sep + component0 
os0.symlink(path0,path1) 
os0.symlink(path1,path0) 
path0 += os.path.sep + component1 
result = os0.readlink(path0) 

print result
```

`/Volumes/ramdisk/test/alpha` for OS, but `/Volumes/ramdisk/test/beta` for pyfakefs

**Comment by agroce** [comment]
(these are all from a big batch produced during a two-day run until estimated coverage saturation; I will have a few more from it once triage is done on the 8K failing tests produced)

**Comment by mrbean-bremen** [comment]
Sounds like a lot of work... I don't have much time for fixing issues currently, so I will go slow on these. Let me know if there are blocking issues that prevent further testing.

**Comment by agroce** [comment]
Eh, it's all automated; I mostly was doing a test of my saturation implementation, and figured why not get some bug hunting done at the same time to keep it real.  Running AFL from the same base now, see if it turns up any other issues, and then just keep those and report remaining issues as you get a chance to fix things.  No showstoppers I can see.
