### ISSUE TITLE
lstat succeeds that should fail (part of pattern with multiple other operations)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#396]
```
import shutil
import pyfakefs.fake_filesystem
import os

ROOT_PATH = "/Volumes/ramdisk/test"

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

if False:
    os0 = os
    shutil.rmtree(ROOT_PATH)
    os.mkdir(ROOT_PATH)
    opener0 = open

component0 = "alpha" 
path0 = ROOT_PATH 
path1 = ROOT_PATH 
path0 += os.path.sep + component0 
component0 = "beta" 
path1 += os.path.sep + component0 
component0 = "" 
os0.symlink(path1,path0) 
path0 += os.path.sep + component0 
stat0 = os0.lstat(path0) 
```

OS raises `OSError: [Errno 2] No such file or directory: '/Volumes/ramdisk/test/alpha/'`

**Comment by agroce** [comment]
Ok, full list of essentially equivalent issues:

```
================================================================================
FAILED WITH os0.mkdir(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'exceptions.OSError'>) == (<type 'NoneType'>) ",), <traceback object at 0x104a62098>)
================================================================================
FAILED WITH os0.makedirs(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'exceptions.OSError'>) == (<type 'NoneType'>) ",), <traceback object at 0x105c3fef0>)
================================================================================
FAILED WITH os0.remove(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'NoneType'>) == (<type 'exceptions.OSError'>) ",), <traceback object at 0x105a6f200>)
================================================================================
FAILED WITH stat0 = os0.lstat(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'NoneType'>) == (<type 'exceptions.OSError'>) ",), <traceback object at 0x105b08998>)
================================================================================
FAILED WITH result = os0.readlink(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'NoneType'>) == (<type 'exceptions.OSError'>) ",), <traceback object at 0x104e9cd40>)
================================================================================
FAILED WITH os0.rename(path0,path1) 
(<type 'exceptions.AssertionError'>, AssertionError(" (<type 'NoneType'>) == (<type 'exceptions.OSError'>) ",), <traceback object at 0x105a96758>)
================================================================================
FAILED WITH result = os0.path.lexists(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(' (True) == (False) ',), <traceback object at 0x105a32518>)
================================================================================
FAILED WITH result = os0.path.islink(path0) 
(<type 'exceptions.AssertionError'>, AssertionError(' (True) == (False) ',), <traceback object at 0x1059b02d8>)
```

**Comment by agroce** [comment]
(you can get a more verbose and full of extra stuff similar result doing:

```
> tstl_generalize lstatnorm.test
...
tat0 = os0.lstat(path0)                                                             # STEP 10
#  or os0.mkdir(path0) 
#  or os0.makedirs(path0) 
#  or os0.remove(path0) 
#  or stat1 = os0.lstat(path0) 
#  or stat2 = os0.lstat(path0) 
#  or stat3 = os0.lstat(path0) 
#  or stat4 = os0.lstat(path0) 
#  or result = os0.readlink(path0) 
#  or os0.rename(path0,path1) 
#  or result = os0.path.lexists(path0) 
#  or result = os0.path.islink(path0) 
GENERALIZED IN 52.8304390907 SECONDS
```

at the command line; FYI if you ever start running TSTL tests much yourself.  Generalize will often show if a bug is part of a general pattern.

**Comment by agroce** [comment]
No rush, I'll just run the regression directory when you fix it, but it seems to cover a lot of the current Mac OS issues (how important it is, involving both symlinks and extra separators, I leave to you to judge; probably unimportant except for shutting up the tests).

**Comment by mrbean-bremen** [comment]
Ok, here is the behavior for these cases:

command | Real OS | Fake FS
------ | ----- | -----
lstat Linux | OSError 2 | OSError 2  :white_check_mark:
lstat MacOS | no error | OSError 2 :x:
lstat Windows | OSError 22 | OSError 2 :x:
mkdir+makedirs Linux | OSError 17 | OSError 17 :white_check_mark:
mkdir+makedirs MacOS | no error | OSError 17 :x:
mkdir+makedirs Windows | OSError 17 | OSError 17 :white_check_mark:
remove+rename Linux | OSError 20 | no error :x:
remove+rename MacOS | OSError 2 | no error :x:
remove+rename Windows | OSError 22 | no error :x:
readlink Linux | OSError 2 | OSError 40 :x:
readlink MacOS | OSError 2 | no error :x:
readlink Windows | OSError 22 | OSError 22 :white_check_mark:
lexists+islink Linux | False | False :white_check_mark:
lexists+islink MacOS | False | True :x:
lexists+islink Windows | False  | False :white_check_mark:

Looks like a bit of work...

**Comment by mrbean-bremen** [comment]
This is a lot of special handling again for the different functionality, so I doubt that fixing this will help with many others,

**Comment by agroce** [comment]
We can just drop testing extra path separators, of course, and these will all go away.

**Comment by agroce** [comment]
I have no problem with that, though it means any interesting weirdness with path separators is going to be missed.  I can't figure a good way to not always produce tons of these, but catch more "interesting" stuff (and I'm not sure what that would even be)

**Comment by mrbean-bremen** [comment]
While this took a while to fixi because of the different cases, it is still faster than fixing each of these separately, so the generalization really helped here.
