### ISSUE TITLE
getsize difference

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#412]
May be related to the tell bug?

```
import shutil
import pyfakefs.fake_filesystem
import os

ROOT_PATH = "/Volumes/ramdisk/test"

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

if False:
    os0 = os
    shutil.rmtree(ROOT_PATH)
    os.mkdir(ROOT_PATH)
    opener0 = open

component0 = "alpha" 
path0 = ROOT_PATH 
path0 += os.path.sep + component0 
bytes0 = 0 
str0 = "" 
str0 += 'a' 
file0 = opener0(path0,'a') 
file0.write(str0) 
file0.seek(bytes0) 
file0.truncate() 
file0.write(str0) 
file0.truncate() 
result = os0.path.getsize(path0) 

print result
```

OS gives 1, pyfakefs gives 2.

**Comment by agroce** [comment]
On reflection, no, this is probably not related to the tell issue, despite the append.  It's a truncate problem, I'd bet.

**Comment by agroce** [comment]
no symlinks, no weird extra slashes, no rename.  just a nice, simple, basic POSIX thing.

**Comment by mrbean-bremen** [comment]
I don't thik so either, I will check later. I had a go at the tell problem earlier, and it looks tough. I may actually revert a fix for another more obscure bug to fix this one - I may have another look at the weekend.

**Comment by agroce** [comment]
This and tell seem more important than symlinks + weird extra slashes, to me.  I will probably remove extra slashes and add back in symlinks when I get a chance.

Running a bunch of new tests, since I have a cool new test generation heuristic I want to test out, anyway (count times every call has appeared in testing, and if I can call a seldom-called operation, make that highly probable, vs. the normal pure random selection)

**Comment by mrbean-bremen** [comment]
Yes, I'm already tired of the exta slashes :P
Sounds interesting, may be I will have a closer look at tstl again later (but only after the temparatures are going a bit down here, I have trouble getting something into my head at the moment).

**Comment by agroce** [comment]
Symlinks included but extra slashes lost seems ok-ish.  2116 tests so far with no failures.  So maybe we are mostly down to multi-slash nonsense as problems (I'm ignoring renames for now)

**Comment by mrbean-bremen** [comment]
Ok, that sounds not so bad.

**Comment by agroce** [comment]
Many hours of testing seems to just show this issue, when extra slashes and rename aren't in the mix.  You can detect it with readline, readlines, getsize, or st.size, but they all look like the same fancy footwork with truncate.

**Comment by mrbean-bremen** [comment]
I tested only with getsize() - hopefully the other ones will also be fixed...

**Comment by agroce** [comment]
Variant still fails:

```
import shutil
import pyfakefs.fake_filesystem
import os

ROOT_PATH = "/Volumes/ramdisk/test"

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

if False:
    os0 = os
    shutil.rmtree(ROOT_PATH)
    os.mkdir(ROOT_PATH)
    opener0 = open

component0 = "alpha" 
path0 = ROOT_PATH 
path0 += os.path.sep + component0 
str0 = "" 
str0 += 'a' 
file0 = opener0(path0,'a') 
file0.write(str0) 
file0.truncate() 
file0.write(str0) 
file0.truncate() 
stat0 = os0.stat(path0) 
result = stat0.st_size 
print result
```

**Comment by mrbean-bremen** [comment]
Reopen according to last comment.
