### ISSUE TITLE
TestCase without modules_to_reload might not clean up properly

### ISSUE THREAD

**Issue by ivar010f** [jmcgeheeiv/pyfakefs#416]
When not using `modules_to_reload` in a test case, the clean up might not be done properly. I could not find any mention of this in the documentation or issues.

### Fail case and solution
In a testsuite of ~1000 tests where many use real file IO, a `pyfakefs` test without the `modules_to_reload` caused a following testcase to recieve a module using `FakePath`, when a real `Path` were expected. The failing test passed after adding an explicit `modules_to_reload` to the `pyfakefs` test. This was the only fake test without the `modules_to_reload` attribute set.

### Test setup sketch
[...]
FakeTest: uses module `MyToolPaths` in a `pyfakefs TestCase`.
[...]
RealTest: a standard `unittest.TestCase` that uses module `MyToolPaths`, which will unexpectedly use `FakePath` when run after FakeTest in a `unittest discover` command, resulting in a fail. Standalone, it runs fine.
[...]

**Comment by ivar010f** [comment]
I just noted an `importlib.reload(MyToolPaths)` in the FakeTest test method. I am pretty sure this is the reason the clean-up gets messed up.

**Comment by mrbean-bremen** [comment]
Thanks for the report!
You explanation sounds reasonable - the `reload` could mess up the restore of the original modules. I have no real idea how to fix this at the moment. Is this `reload` part of the real code, or just of the test? If it is the test - why it is needed?
Also, it would be nice to have a minimum example that reproduces the problem, so we can be sure to be on the same page here.

**Comment by mrbean-bremen** [comment]
Ah, and I guess you use the latest version of pyfakefs? There has been a related bug in 3.4.0, which has been fixed in 3.4.1.

**Comment by ivar010f** [comment]
Thanks for the quick response! I'm sorry for a non-bug report. So, after a quick review of the test, I realize this is the expected behaviour of the dynamic patcher feature. Essentially, an importlib.reload of a module triggered in the tested code, leaving a module reloaded with fake filesystem state. This test is required to use a module reload, regardless of which patching framework is used.

A minimal setup follows.
```
# plugin.py
from pathlib import Path

version = None
path = Path("version")


def update_version():
    global version
    with path.open() as f:
        version = f.read()

# application.py
import importlib

import plugin


def get_fresh_plugin_version():
    importlib.reload(plugin)
    plugin.update_version()
    return plugin.version

# test.py
import unittest

from pyfakefs import fake_filesystem_unittest

import application
import plugin


class TestFake(fake_filesystem_unittest.TestCase):
    def setUp(self):
        # missing module reload, rendering the reloaded plugin module dirty
        # this test will pass, however
        # self.modules_to_reload = [plugin]
        self.setUpPyfakefs()

    def test_fake(self):
        self.fs.create_file("version", contents="fake")
        self.assertEqual("fake", application.get_fresh_version())


class TestReal(unittest.TestCase):
    def test(self):
        # if run after TestFake, will use the dirty plugin module
        plugin.update_version()
        self.assertEqual("real", plugin.version)
```

**Comment by mrbean-bremen** [comment]
Ok, yes, you are right - in this case there is not much we can do - thanks for the analysis!
I hope you can live with that (separating the tests could be a solution).
