### ISSUE TITLE
create_file(..., contents=None) unintentionally crates a "large file"

### ISSUE THREAD

**Issue by kamichal** [jmcgeheeiv/pyfakefs#424]
Seems it's a lack in the API:
```python
    # pytest
    def test_thinks_is_a_large_file(fs):
        fs.create_file("/tmp/file.txt", contents=None)
    
        with open("/tmp/file.txt", 'rt') as ff:
            ff.read()
```
If the contents is `None` there is no chance to later read the file.
In my opinion `None` in this API should be equivalent to `""` - giving an empty file. However at read attempt it raises:

```python
    self = <pyfakefs.fake_filesystem.FakeFileWrapper object at 0x7f5a8c6dd310>
    name = 'read'
    
        def __getattr__(self, name):
            if self.file_object.is_large_file():
    >           raise FakeLargeFileIoException(self._file_path)
    E           FakeLargeFileIoException: Read and write operations not supported for fake large file: /tmp/file.txt
```
Of course setting `contents=''` works OK.

**Comment by mrbean-bremen** [comment]
Well, given that the default value for `contents` is an empty string, you have to explicitely pass `None` to `contents` in `create_file()`, so this has to be a conscious decision. But I agree that handling `None` contents as empty contents as long as `st_size` is also `None` makes sense.
