### ISSUE TITLE
Permission checking does not match Posix behaviour for root

### ISSUE THREAD

**Issue by ttsalo** [jmcgeheeiv/pyfakefs#431]
I'm trying to simulate file operations performed by root but ran into the following problem: 

Permission checking in various operations including mkdir does not match real os behaviour when running as root. Real os ignores filesystem permissions when uid=0 whereas pyfakefs raises permission denied exceptions.

```#!/usr/bin/env python

import os
from pyfakefs import fake_filesystem
filesystem = fake_filesystem.FakeFilesystem()
fake_os = fake_filesystem.FakeOsModule(filesystem)

os.mkdir("/tmp/test")
os.chmod("/tmp/test", 0o444)
os.mkdir("/tmp/test/test2")

os.rmdir("/tmp/test/test2")
os.rmdir("/tmp/test")

fake_os.mkdir("/tmp")
fake_os.mkdir("/tmp/test")
fake_os.chmod("/tmp/test", 0o444)

# Raises EACCES
fake_os.mkdir("/tmp/test/test2")
```

**Comment by mrbean-bremen** [comment]
Yes, this is correct - we currently do not support this. A non-root user is assumed for all operations. 
Also, the `uid` and `gid` file attributes are currently ignored (you can see this in the `FakeFile` description) - they are both set to `None`, though they can be set using `chown`. 
I don't think that we will add full support for these, but support for root should not be too difficult. We may add a function to set the user id (we would assume a non-root user by default, independent of the rights of the user running the test), and handle the root (e.g. 0) case by ignoring the access restrictions if it is set.
Would that be sufficient for you?

**Comment by mrbean-bremen** [comment]
@ttsalo - please have a look if this is what you need. This basically just allows to set the root user, for which some of the permissions are ignored.

**Comment by mrbean-bremen** [comment]
Ok, closing the issue in this case. Please reopen if something does not work as expected.
