### ISSUE TITLE
st_ctime/st_atime/st_mtime differences in behaviour compared to linux

### ISSUE THREAD

**Issue by simonfagerholm** [jmcgeheeiv/pyfakefs#435]
Hi, I might have found a problem depending on the expected behaviour.
I noticed that the times st_ctime/st_atime/st_mtime are behaving differently in regard to when the times are updated and if they are updated.
I created two testfiles that run the same sequences on the real fs and on pyfakefs and checks it, see travis build:
https://travis-ci.org/simonfagerholm/pyfakefs/builds/434572170
The test files are fake_stat_time_test.py and real_stat_time_test.py

On linux the real_stat_time_test.py passes all tests (confirming that the expected result corresponds to linux fs) but many fail on pyfakefs. However, on mac os the real_stat_time_test.py also fails a few times so linux and mac behaves differently.

How is pyfakefs supposed to work?

**Comment by mrbean-bremen** [comment]
The different behavior under MacOS is most likely due to the low time stamp resolution of 1 second in HFS+. In NTFS and most Linux file systems the resolution is much higher (I think we can ignore FAT/FAT32, where the resolution is 2 s for mtime and 1 day for atime). I assume that MacOS behaves the same way as Linux, just with a worse time stamp resolution.

**Comment by simonfagerholm** [comment]
I think you are correct, I tested changing the sleep time (after each read of stat) to 2 s and reran the tests. Now both Linux and MacOS passed the real_stat_time_test.py.
fake_stat_time_test.py still fail on both

**Comment by mrbean-bremen** [comment]
Yes, I did the same (well, almost - I used 1.1 s), you can check it [here](https://github.com/mrbean-bremen/pyfakefs/tree/stat-times).
I adapted the tests to also work [under Windows](https://ci.appveyor.com/project/mrbean-bremen/pyfakefs-ad6k0) where the behavior is slightly different, and adapted them a bit to our test infrastructure. I disabled the tests against pyfakefs to test the real file system first, but will enable them as soon as I fix pyfakefs.
I also think that it makes sense to add a timestamp resolution to the file system, that will default to the value for NTFS under Windows, for ext4 under Linux and HFS+ under MacOS, but can be set by the user to match other file systems (ext3 and before for example also had a resolution of 1s).

**Comment by mrbean-bremen** [comment]
@simonfagerholm - thanks for the report and the tests - this has been quite helpful!
I will try to add the time resolution stuff some time later.
