### ISSUE TITLE
No source package on PyPi for 3.4.2 and 3.4.3

### ISSUE THREAD

**Issue by OskarPersson** [jmcgeheeiv/pyfakefs#438]
Since 3.4.2 there is only a binary package instead of a source package available on PyPi. Source packages are required when doing `pip download --no-binary` for installation on a machine without internet access.

**Comment by mrbean-bremen** [comment]
Hm, we indeed upload a wheel package (as preferred by PyPi / pip), but as I understand this is just another packaging format, you can install it using pip on any machine without internet access. I usually prefer downloaded wheel packages for deployment myself. 
Maybe I don't understand the use case - can you elaborate please?

**Comment by mrbean-bremen** [comment]
For background - we did change the format with the new PyPi deployment site, where wheel deployment is the recommended option.

**Comment by OskarPersson** [comment]
With a project containing multiple dependencies it is useful to simply use `pip download -r requirements.txt --no-binary :all:` to download the source for all packages so that it later can be transferred for compilation to machines of different platforms with no internet access. Now we have to make an exception for pyfakefs: `pip download -r requirements.txt --no-binary :all: --only-binary pyfakefs`.

It isn't the end of the world but it could be simpler :) Packages like lxml and django has both wheels and source which is the optimal solution in my opinion.

**Comment by mrbean-bremen** [comment]
Ok, I updated the [release procedure](https://github.com/jmcgeheeiv/pyfakefs/wiki/Release-procedure), next release will be both source and binary package.

**Comment by OskarPersson** [comment]
Source package of 3.4.3 works great! 👍

**Comment by mrbean-bremen** [comment]
Glad to here that!
