### ISSUE TITLE
Update PyPI package information with new home page pointing to this repository

### ISSUE THREAD

**Issue by jamescooke** [jmcgeheeiv/pyfakefs#44]
Please update the page for [pyfakefs on PyPI](https://pypi.python.org/pypi/pyfakefs/2.4) with URLs that point to this repo. This will help people like me to be certain that this is the official copy that should be contributed to.

The problem is that there are a bunch of clones and there is no certainty around which one should receive community efforts. https://github.com/search?utf8=✓&q=pyfakefs

**Comment by jmcgeheeiv** [comment]
Thank you for your words of encouragement.

Can you verify that jmcgeheeiv/pyfakefs has everything it needs to claim that it is The One True Pyfakefs on PyPi?  If not, what is missing?

**Comment by jamescooke** [comment]
Sorry I'm not able to verify that this repository is "The One True PyPi Pyfakefs". My assumption was that the current user that 'own' the page at https://pypi.python.org/pypi/pyfakefs/2.4 would be able to make that verification and adjust that page to point at this repository once verified.

**Comment by jmcgeheeiv** [comment]
I apologize for not being clear.  I was asking if you think jmcgeheeiv/pyfakefs is complete enough to debut on PyPi.  For example, it needs a .tgz file for download.  What else is missing?

**Comment by jamescooke** [comment]
Given that this commit https://github.com/jmcgeheeiv/pyfakefs/commit/737172ab2173d56fe2a64e33777fb886d3d9e285 is currently on PyPi as a release 2.4 here https://pypi.python.org/pypi/pyfakefs/2.4 and there have been improvements beyond that, then yes I think that the project has enough functionality to be on PyPi.

The sdist can be built with `python setup.py sdist` - I don't think that anything else is missing compared to the existing release. However there need to be some changes made to https://github.com/jmcgeheeiv/pyfakefs/blob/master/setup.py to update the references and documentation strings.

**Comment by jamescooke** [comment]
Hey John, I'm guessing that the original pyfakefs package on PyPI is not going to change. Therefore, have you considered a simple name change and then release on PyPI instead? Something like 'pyfakefs2' could work and would help people to find the package when searching.

**Comment by jmcgeheeiv** [comment]
Okay, give [pyfakefs on PyPi](https://pypi.python.org/pypi/pyfakefs) a try and reopen this issue if you find problems.

**Comment by jamescooke** [comment]
John, thanks for all your hard work on this over the last year! I'm going to unwatch the repo now, but feel free to call me back in if you ever need help - especially testing and or documentation.

Cheers :+1:
