### ISSUE TITLE
pyfakefs breaks subprocesses

### ISSUE THREAD

**Issue by majuscule** [jmcgeheeiv/pyfakefs#447]
`pyfakefs` breaks stdlib subprocess calls as shown below. Running on Ubuntu 16.04.5 LTS. 

```python
import subprocess

def test_fake_fs(fs):
    assert subprocess.run(['echo'])
```

```
self = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7fcbfda2acc0>, errno = 9, filename = '9', winerror = None

    def raise_os_error(self, errno, filename=None, winerror=None):
        """Raises OSError.
        The error message is constructed from the given error code and shall
        start with the error string issued in the real system.
        Note: this is not true under Windows if winerror is given - in this
        case a localized message specific to winerror will be shown in the
        real file system.
    
        Args:
            errno: A numeric error code from the C variable errno.
            filename: The name of the affected file, if any.
            winerror: Windows only - the specific Windows error code.
        """
        message = self._error_message(errno)
        if (winerror is not None and sys.platform == 'win32' and
                self.is_windows_fs):
            if IS_PY2:
                raise WindowsError(winerror, message, filename)
            raise OSError(errno, message, filename, winerror)
>       raise OSError(errno, message, filename)
E       OSError: [Errno 9] Bad file descriptor in the fake filesystem: '9'
```

**Comment by majuscule** [comment]
On second look, I'm guessing this is due to "pyfakefs will not work with Python libraries that use C libraries to access the file system."?

**Comment by mrbean-bremen** [comment]
Yep - correct. Sorry, out of luck here!

**Comment by majuscule** [comment]
Is there any way to temporarily escape the fakefs from a test function, in order to run necessary subprocesses, add their output to the fakefs tree, and return? If not, would this be considered if submitted as a feature request? Thanks for the module!

**Comment by majuscule** [comment]
Yes that is correct. My project is manipulating a git repository and retrieving files from various checkouts. To do this I need a git subprocess, however I desire to test all other functionality (which includes dangerous operations such as file deletions) with the fakefs for safety. The process controlling these checkouts is recursive, which makes it impossible to complete all checkouts before engaging the fakefs. If I was able to "pause" the fakefs, return to the real fs, checkout, add the resulting files to the fakefs, and then resume, it would allow me to continue with this solution. I'll submit a new issue for the feature request. Thank you!

**Comment by GozzoMan** [comment]
Hello, same problem here.

In my case, it would be sufficient to have subprocess.Popen() do nothing, instead of raising bad file descriptor.

**Comment by mrbean-bremen** [comment]
Well, if you just want to ignore that call, that is a valid solution, which is used often enough in Python.
If you really need to access the file system in that call, you can instead pause mocking during the call (as has been introduced in pyfakfs as proposed by @majuscule).

**Comment by stevenengland** [comment]
Hi, I didn't expect this to be a general issue because I have Windows based subprocess calls that are not affected. Strange. But thanks for pointing me into this direction.
