### ISSUE TITLE
Support fakefs "pause and resume"

### ISSUE THREAD

**Issue by majuscule** [jmcgeheeiv/pyfakefs#448]
Feature request to support "pausing" and "resuming" use of the fakefs, allowing for a test process to run code that the fakefs does not support, then adding new data to the fakefs from the real fs upon resumption.

**Comment by mrbean-bremen** [comment]
@majuscule - please check if this works for you.

**Comment by mrbean-bremen** [comment]
Functionality is implemented in the released version - closing.

**Comment by majuscule** [comment]
Looks perfect! Thank you. I don't actually see a release out though? `--pre` or otherwise. Also while I'm here I'll add one more tiny idea - it'd be nice if this was supported as a context manager to be able to do:

```python
with fs.pause():
     # my syscalls
```

**Comment by mrbean-bremen** [comment]
This should be in the latest release (3.5.3), and had already been added in 3.5.2.
About the context manager - I have been thinking about this, but I wasn't sure where to add it (Patcher, UnitTest, or fake_filesystem). I can add this later...

**Comment by majuscule** [comment]
Whoops, my mistake. Thanks!
