### ISSUE TITLE
The pyfakefs on PyPi is obsolete 

### ISSUE THREAD

**Issue by spg** [jmcgeheeiv/pyfakefs#45]
So I `pip install pyfakefs`
Then I `import fake_filesystem_unittest` in one of my test modules
And I get `ImportError: No module named fake_filesystem_unittest` when running tests with `py.test`

Is that expected?

**Comment by megapctr** [comment]
The pyfakefs on PyPy is old. Try installing pyfakefs through github url, this should help

**Comment by centralniak** [comment]
Perhaps it would be better to release a set of unittest pyfakefs tools as a separate package so that there is no need to overwrite original `pyfakefs` on PyPI?

**Comment by jmcgeheeiv** [comment]
in [davidlbaird/pyfakefs issue #33](https://github.com/davidlbaird/pyfakefs/issues/33), I have asked Mr. Baird to allow me access to PyPi pyfakefs.  If you think this is a good idea, please add your opinion as a comment to [davidlbaird/pyfakefs issue #33](https://github.com/davidlbaird/pyfakefs/issues/33).

**Comment by jmcgeheeiv** [comment]
I am considering releasing pyfakefs as pyfakefs3, a name I control.  Comments?

**Comment by jamescooke** [comment]
:+1:  for `pyfakefs3`. I hope that releasing the new version on PyPI will help move the project forwards.

**Comment by holtgrewe** [comment]
:+1: 

Please upload to pypi, I cannot deploy it organisation-wide otherwise

**Comment by cash** [comment]
PyPI lists jmcgeheeiv as the maintainer so @jmcgeheeiv should be able to update the package. https://pypi.python.org/pypi/pyfakefs

**Comment by cburroughs** [comment]
Apologizes for the bump, but I'm using a non-pip system where going around PyPi is extra difficult (pants).  I think pyfakefs3 is fine, if the PyPi metadata means @jmcgeheeiv  has access to the existing package after all, so much the better.

**Comment by jmcgeheeiv** [comment]
I apologize for the delay.  I will get to this soon.  I see that I have quite a corps of testers to make sure PyPi works smoothly.

**Comment by jmcgeheeiv** [comment]
Okay, ladies and gentlemen, give [pyfakefs on PyPi](https://pypi.python.org/pypi/pyfakefs) a try and reopen this issue if you find problems.

**Comment by cburroughs** [comment]
If I go to https://pypi.python.org/simple/pyfakefs/  (which Is I think the same as what pip does) I don't see a version past 2.4.  Looking at the PyPi feed I think the 'add source file' step is missing.

**Comment by jcwilson** [comment]
I'm seeing the same thing:
```
$ pip install pyfakefs==2.6
Collecting pyfakefs==2.6
Could not find a version that satisfies the requirement pyfakefs==2.6 (from versions: 1.1, 1.2, 2.0, 2.1, 2.2, 2.3, 2.4)
No matching distribution found for pyfakefs==2.6
```

**Comment by jmcgeheeiv** [comment]
I apologize.  Please try it now.

**Comment by jcwilson** [comment]
Thanks for taking the time to do this. We're getting closer. :)

The `setup.py` file is looking for `README.md` which doesn't seem to be shipped in `pyfakefs-2.6.tar.gz`.

```
Downloading/unpacking pyfakefs
  Downloading pyfakefs-2.6.tar.gz
  Running setup.py egg_info for package pyfakefs
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_Josh/pyfakefs/setup.py", line 37, in <module>
        LONG_DESCRIPTION = open(readme).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_Josh/pyfakefs/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_Josh/pyfakefs/setup.py", line 37, in <module>

    LONG_DESCRIPTION = open(readme).read()

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_Josh/pyfakefs/README.md'
```

**Comment by jmcgeheeiv** [comment]
Reopening this issue until @jcwilson is satisfied.  Please try pyfakefs 2.7 on PyPi.

**Comment by jcwilson** [comment]
works for me! thanks for being patient with that pull request

**Comment by cburroughs** [comment]
Working for me as well.  Thank you all for getting everything sorted out!

**Comment by jmcgeheeiv** [comment]
@jcwilson, @cburroughs, and Cash Costello confirmed that pyfakefs 2.7 on PyPi works.

Thank you for your patience.
