### ISSUE TITLE
DeprecationWarning when used with pytest

### ISSUE THREAD

**Issue by cubranic** [jmcgeheeiv/pyfakefs#466]
**Describe the bug**
Using pyfakefs with pytest produces a deprecation warning about the `compiler` package as soon as a test depends on the `fs` fixture.
```
plugins: pyfakefs-3.5.6
collected 1 item

tests/test_foo.py .                                                                                           [100%]

================================================= warnings summary ==================================================
tests/test_foo.py::test_fs
  /usr/local/miniconda3/envs/alpenhorn/lib/python2.7/site-packages/py/_code/_assertionold.py:3: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
    from compiler import parse, ast, pycodegen

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================= 1 passed, 1 warnings in 0.11 seconds ========================================
```

**How To Reproduce**
Put the following into test_foo.py:
```py
def test_foo(fs):
    pass
```
Then run pytest test_foo.py.

**Your enviroment**
Please run the following and paste the output.
```bash
Darwin-18.0.0-x86_64-i386-64bit
('Python', '2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
('pyfakefs', '3.5.6')
```

**Comment by mrbean-bremen** [comment]
There is an old (and long fixed) [pytest bug](https://github.com/pytest-dev/pytest/issues/537), which may be related - can you please check which version of pytest you use?

**Comment by cubranic** [comment]
Showing DeprecationWarnings from system libraries [has been enabled in Pytest 3.8](https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning). I'm running Pytest 4.1.1, the latest version on Conda.

**Comment by cubranic** [comment]
I was able to silence the warning with a filter in the configuration file, as described on the same Pytest page. But if pytest is directly importing the `compiler` package, perhaps the import statement can be wrapped in some kind of logging filter?

**Comment by mrbean-bremen** [comment]
Ah, ok - I had used an older version of pytest, now I see the warning, too, thanks!
It is strange that this warning is still occurring (pytest is imported a lot if used in tests), but wrapping the import in a logging filter sounds like a good idea.

**Comment by mrbean-bremen** [comment]
Hm, I didn't succeed in filtering out the warning so far (other than in the config file or on the command line) - maybe I'm doing something wrong.

**Comment by mrbean-bremen** [comment]
I had another try, and couldn't get it to work - either I'm doing something wrong, or this has to be fixed in pytest itself. I'm out of ideas right now. @jmcgeheeiv - any thoughts?

**Comment by diefans** [comment]
@mrbean-bremen 
```
[pytest]
filterwarnings =
    ignore::DeprecationWarning 
```

**Comment by mrbean-bremen** [comment]
@diefans - thanks! I will have a look at this sometime next week, I'm traveling right now.

**Comment by jmcgeheeiv** [comment]
I'm sorry, but I do not see what the problem could be.

**Comment by diefans** [comment]
When I put `catch_warnings` context around `modules = ...` I do not get deprecation warnings in python 2.7...

**Comment by mrbean-bremen** [comment]
@diefans - thanks for that - this works nicely! I obviously had put the filter into the wrong place. 
And we can make this very specific to suppress only this one warning...
