### ISSUE TITLE
`pathlib.Path` is not patched in pyfakefs 3.5.6

### ISSUE THREAD

**Issue by christiankossmann** [jmcgeheeiv/pyfakefs#467]
There seems to be a regression bug with patching `pathlib.Path` in pyfakefs 3.5.6. The following code snippet works perfectly fine in pyfakefs 3.5.5, but fails to patch `pathlib.Path` in 3.5.6.

```python
import pathlib

def test_pathlib(fs):
    pathlib.Path("/path/to").mkdir(parents=True)
```

Executing this code as a non-root user with pyfakefs 3.5.6 results in a `PermissionError` since the underlying file system is touched and not the fake one.

**Environment:**

* Linux-4.4.0-130-generic-x86_64-with-Ubuntu-16.04-xenial
* Python 3.5.2 (default, Nov 12 2018, 13:43:14), [GCC 5.4.0 20160609]
* pytest 4.2.0
* pyfakefs 3.5.6

**Comment by mrbean-bremen** [comment]
Hm, that last release seems to have broken more things than fixed. I will have a look at this tonight... Meanwhile, you can safely work with the previous version.

**Comment by mrbean-bremen** [comment]
Ok, I understood the problem. It happens, if you have `pathlib2` installed with a Python version which has `pathlib` (e.g. with Python 3). This is indeed a regression due to the latest change (which prefers `pathlib2` over `pathlib`). I will try to put a fix together somewhere in the next days. Thanks for the report!

**Comment by christiankossmann** [comment]
Thanks, for investigating the issue. As you pointed out, it is totally fine to use version 3.5.5 for now. So there is no need to hurry.

**Comment by mrbean-bremen** [comment]
@christiankossmann - can you please check if master works for you?

**Comment by christiankossmann** [comment]
Did some quick tests and master seems to work fine for me. Many thanks for your efforts!
