### ISSUE TITLE
Current status has same Version as old Pypi status

### ISSUE THREAD

**Issue by user150512** [jmcgeheeiv/pyfakefs#47]
First I installed `pyfakefs` using `pip`. Then I recognized that the version on Pypi is old and on github are some developments. I tried to upgrade my version to github using pip. It failed, because Pypi version and github version are both `2.4`. I had to remove the old installed version to install this one. If the github version shall be used, there should be a new version number.

**Comment by jmcgeheeiv** [comment]
I uploaded pyfakefs 2.6 to PyPi.  Please give this a try.
