### ISSUE TITLE
Document Temp Dir Creation

### ISSUE THREAD

**Issue by svozza** [jmcgeheeiv/pyfakefs#476]
**Is your feature request related to a problem? 
I recently ran into the the issue desribed in #329, this caused me to waste a significant amount of time trying to figure out why my tests were passing on my Mac but not on my build system running Ubuntu. I assumed the file system was blank and was creating the `/tmp` directory in my tests and of course this worked fine locally because the temp directory pyfakefs creates for MacOS is `/var`.

**Describe the solution you'd like**
Document that the filesystem is not blank and explain the difference between MacOs and Linux.

**Describe alternatives you've considered**
n/a

I'm willing to make the PR to if someone can tell me where this note should live.

**Comment by mrbean-bremen** [comment]
Thanks - good point! That could definitely help other users.
I think this belongs somewhere in the [usage chapter](https://github.com/jmcgeheeiv/pyfakefs/blob/master/docs/usage.rst), though I'm not sure where exactly - probably add a subtopic for trouble shouting? Maybe we can think of other problems that have occurred, for example problems with patching some libraries.
We would definitely appreciate a PR for this!

**Comment by svozza** [comment]
Sounds good, I should be able to stay this tomorrow!
