### ISSUE TITLE
Revert to using mox.stubout instead of mock.patch

### ISSUE THREAD

**Issue by jmcgeheeiv** [jmcgeheeiv/pyfakefs#48]
A few months ago, in `pyfakefs.pyfakefs_unittest._Patcher` I replaced [mox](https://pypi.python.org/pypi/mox) with [unittest.mock](https://docs.python.org/3/library/unittest.mock.html).  mox worked fine, but mock seemed like a more reliable dependency:
* mox is seemingly abandoned while mock is now part of the standard library
* mox does not support Python 3
* The OpenStack people created [mox3](https://pypi.python.org/pypi/mox3) to support Python 3, but it is marked with the omimous comment, "Use at your own risk".  Moreover, [OpenStack stopped using mox3](https://review.openstack.org/#/c/62678/).

Now we are seeing all kinds of trouble caused by [mock module bug 250](https://code.google.com/p/mock/issues/detail?id=250):
* pyfakefs issue #43 
* pyfakefs issue #46

pyfakefs used only one small part of mox, mox.stubout.  I do not care to depend on unmaintained mox, (or to take on maintenance of the mox3 module as a whole), so I am considering salvaging just the part of mox3 that pyfakefs needs:
1. Take just mox3.stubout.py and its test from mox3
2. Add it to pyfakefs as pyfakefs.stubout
3. Revert to using pyfakefs.stubout as I used mox.stubout in earlier versions, eliminating the dependency on both mock and mox

Please tell me what you think of this plan.

**Comment by tomviner** [comment]
Given the issues we're seeing, this sounds like the best option.

**Comment by robintw** [comment]
This sounds like a very good way forward.

(In the meantime, is there anything I can do myself to fix this? I'm really struggling with `fake_filesystem_unittest.py` at the moment)

**Comment by jmcgeheeiv** [comment]
Robin, which issue it it that you are facing?
