### ISSUE TITLE
Documentation: small issues in usage.html and modules.html

### ISSUE THREAD

**Issue by luziferius** [jmcgeheeiv/pyfakefs#480]
**Describe the bug**
This report contains a list of small issues in the online documentation, here http://jmcgeheeiv.github.io/pyfakefs/release

I didn’t fully proof-read it, the list just contains some points I noticed while reading the documents.

The first two are present in the current master branch, too: (I just checked all found items against the current master branch)

- [Section `modules_to_reload`](http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#modules-to-reload): Simple typo: `Given tat the example code […]`
- [Section `fake_filesystem_classes.FakeFilesystem.patcher`](http://jmcgeheeiv.github.io/pyfakefs/release/modules.html#pyfakefs.fake_filesystem.FakeFilesystem.patcher): The description contains two newline characters, causing the second half to be rendered in bold, one indention level below the intended level.

These are only present in the last stable release and fixed in the master branch. So probably not worth reporting, but since I report some other items, I’ll include them anyway.

- [Section `modules_to_patch`](http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#modules-to-patch): The indention in the example code is broken. All methods in the class are indented at the module level.
- [Section `use_dynamic_patch`](http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#use-dynamic-patch): `This parameter will probably removed in the future […]`. I think the sentence misses a `be`.

**Comment by mrbean-bremen** [comment]
Thanks - I will correct these!

**Comment by mrbean-bremen** [comment]
Ok - shall now be fixed both in master and release documentation. Please check!

**Comment by luziferius** [comment]
Thank you for fixing those minor issues. Looks good!

**Comment by mrbean-bremen** [comment]
Thanks for the report!
