### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by florian-fischer** [jmcgeheeiv/pyfakefs#481]
Hi, your implementation of os.makedirs doesn't reflect the official python 3 API https://docs.python.org/3/library/os.html?highlight=os%20makedirs#os.makedirs. Should accept 'name' as parameter.
I'm using your release version 3.5.8.
As far as I can see in the source file fake_filesystem.FakeOsModule.makedirs expects the parameter 'dir_name' instead of 'name'.

**Comment by mrbean-bremen** [comment]
Thanks for the report!
