### ISSUE TITLE
fake_scandir.DirEntry isn't Path-like

### ISSUE THREAD

**Issue by Aran-Fey** [jmcgeheeiv/pyfakefs#483]
Unlike [`os.DirEntry`](https://docs.python.org/3/library/os.html#os.DirEntry), `pyfakefs.fake_scandir.DirEntry` does not implement the [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) interface.

Sample test case that fails if pyfakefs is used, but passes if the `fs` fixture is removed:

```python
import pytest
import os

def test_scandir(fs):
    with os.scandir('/') as scanner:
        for direntry in scanner:
            assert isinstance(direntry, os.PathLike)

if __name__ == '__main__':
    pytest.main([__file__])
```

**Comment by mrbean-bremen** [comment]
Good point.

**Comment by mrbean-bremen** [comment]
Ok, that is not as straightforward as I thought. Under Windows, `scandir.DirEntry` seems not to implement `os.PathLike` (`TypeError: expected str, bytes or os.PathLike object, not scandir.DirEntry`), and the result of `os.fspath()` is different for Python 3.6 and Python 3.7 under Linux (but not under MacOS). I have to understand these differences before implementing this...

**Comment by Aran-Fey** [comment]
It looks like `os.DirEntry` has only become path-like starting with version 3.6 (`DirEntry` was added in 3.5). Do you use 3.5 on Windows?

**Comment by mrbean-bremen** [comment]
Yes, path-like objects have been introduced in Python 3.6. I do get `os.PathLike` behavior under Windows (see my edit above), the reason why the test failed is that it used the `scandir` package, which seems not to implement this behavior under Windows. Maybe the difference under Linux has also to do with that...
We handle `os.scandir` and the `scandir` mostly the same way and test both, so I have to differentiate between them, obviously.
