### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#492]
Support for Python ends in January 2019, and many projects are [committed to drop support](https://python3statement.org/) at that date or before.
I propose to officially drop support for Python 2 in pyfakefs 4.0, which may be released somewhere at the start of 2019 or even earlier, and leave open the possibility for updates to a previous version in case a fix is really needed for Python 2. I would also drop support of the old deprecated API with the same version. 
This will make it possible to better support Python 3 and have cleaner code (I already made [a branch](https://github.com/jmcgeheeiv/pyfakefs/tree/version4) some time ago where I tried that out).
What do you think?

**Comment by hugovk** [comment]
Sounds good. Python 3.4 is also EOL, so that can be dropped already.

**Comment by mrbean-bremen** [comment]
Yes, Python 3.4 will certainly be dropped with the next major release, though that is not such a big deal as Python 2 ;)

@jmcgeheeiv - what do you think?

**Comment by jmcgeheeiv** [comment]
Things will be much easier to support without Python 2. I leave Python 3.4 to your discretion.

**Comment by mrbean-bremen** [comment]
Thanks - I will add pyfakefs to the [Python 3 statement page](https://python3statement.org/) in this case (unfortunately, we have no icon...) and leave this issue open for reference. Probably will add a note in the release notes, too.

**Comment by mrbean-bremen** [comment]
Python 2 support is now dropped in master, with the last release out that still supports it.
Closing.
