### ISSUE TITLE
os.scandir do not raise OSError when target is not directory

### ISSUE THREAD

**Issue by Gapex** [jmcgeheeiv/pyfakefs#498]
**Describe the bug**
As stated in the doc of scandir in pyfakefs, https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/fake_scandir.py#L186, scandir raises OSError if target is not directory, but acutally not.

```python
import os

from pyfakefs.fake_filesystem_unittest import Patcher

with Patcher() as patcher:
    print(os.listdir('.'))
    print(list(os.scandir('not_exist_dir')))

print(os.listdir('.'))
print(list(os.scandir('not_exist_dir')))
```

run the above code: python main2.py, output:
```shell
['tmp']
[]
['main2.py']
Traceback (most recent call last):
  File "main2.py", line 10, in <module>
    print(list(os.scandir('not_exist_dir')))
FileNotFoundError: [Errno 2] No such file or directory: 'not_exist_dir'
```

**My enviroment**
```bash
Linux-4.15.0-55.60-x86_64-with-debian-stretch-sid


Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
[GCC 7.2.0]

output: pyfakefs 3.6.1
```

**Comment by mrbean-bremen** [comment]
Thanks for the report!
What the comment tries to say, is that is raises if the path points to a regular file. The case of a non-existent path seems not to be handled...
I'm traveling right now and will be back in a week, I will have a look then.

**Comment by mrbean-bremen** [comment]
@Gapex - shall be fixed in master, please check!

**Comment by Gapex** [comment]
that's wonderful!
