### ISSUE TITLE
setup.py is missing license header

### ISSUE THREAD

**Issue by nedn** [jmcgeheeiv/pyfakefs#50]
To whom it may concern,
We are using pyfakefs as third_party in chromium project. The file pyfakefs/setup.py is missing license header and make chromium license check fails. My current workaround is copying the license header from other files in the project into it.
It would be great if someone can update the license header in pyfakefs/setup.py so we can make the pyfakefs pass Chromium license check without modification.

Thanks,
Ned

**Comment by jmcgeheeiv** [comment]
Please see if the license is now satisfactory.  If not, please direct me to an example showing a setup.py that meets your requirements.
