### ISSUE TITLE
Usage with importlib.resources.path

### ISSUE THREAD

**Issue by a-recknagel** [jmcgeheeiv/pyfakefs#505]
**Bug description**
When using `pyfakefs` together with `pytest`, `importlib.resources.path` will break with an `IsADirectoryError`.  I also posted this to [stackoverflow](https://stackoverflow.com/questions/59160123/how-to-use-pyfakefs-in-conjunction-with-importlib-resources-path) before thinking that it might be more appropriate to file a bug over here.

**How To Reproduce**
_foo.py_:
```python
import importlib.resources

def print_package_path():
    with importlib.resources.path("importlib", "") as path:
        print(path)

def test_package_path(fs):
    print_package_path()

if __name__ == "__main__":
    print_package_path()
```
Just to make sure that functionality itself of `importlib` is ok:
```bash
$ python foo.py
/home/me/venv/lib/python3.8/importlib
```
Now running the test:
```bash
$ pytest foo.py
================================ test session starts =========================
platform linux -- Python 3.8.0+, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: /home/me/
plugins: pyfakefs-4.0
collected 1 item                               
foo.py F                                                                 [100%]

================================ FAILURES ====================================
______________________________ test_package_path _____________________________

fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f84f2996910>

    def test_package_path(fs):
>       print_package_path()

/home/me/foo.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/me/foo.py:4: in print_package_path
    with importlib.resources.path("importlib", "") as path:
/home/me/pythons/python_3.8/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
/home/me/venv/lib/python3.8/importlib/resources.py:201: in path
    with open_binary(package, resource) as fp:
/home/me/venv/lib/python3.8/importlib/resources.py:91: in open_binary
    return reader.open_resource(resource)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_frozen_importlib_external.SourceFileLoader object at 0x7f84f7527370>
resource = ''

>   ???
E   IsADirectoryError: [Errno 21] Is a directory: '/home/me/venv/lib/python3.8/importlib'

<frozen importlib._bootstrap_external>:988: IsADirectoryError
============================= 1 failed in 0.17s ===============================
```

**My enviroment**
```bash
$ python -c "import platform; print(platform.platform())"
Linux-5.0.0-36-generic-x86_64-with-glibc2.27
$ python -c "import sys; print('Python', sys.version)"
Python 3.8.0+ (heads/3.8:380d443a6a, Oct 18 2019, 09:26:34) 
[GCC 7.4.0]
$ python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 4.0  # also tested on 3.7
```

**Comment by mrbean-bremen** [comment]
As far as I understand that, you want to access the real file system from the fake fs. This will not work out of the box, because the fake fs is empty at test start. 
If you want to access a real directory, you have to [map it into the fake file system](http://jmcgeheeiv.github.io/pyfakefs/master/usage.html#access-to-files-in-the-real-file-system), e.g.
```python
    def test_package_path(fs):
        fs.add_real_directory(os.path.dirname(importlib.__file__))
        print_package_path()
```
If you want to access any resources in the real fs from your test, you have to map them into the fake fs the same way.

**Comment by mrbean-bremen** [comment]
And I just read the answer on stackoverflow - the advice to mock the result of `importlib.resources.path()` call may still make sense in case this will not work.

And you are right - asking the question here gives you a much better chance to get a response from the maintainers ;)

**Comment by a-recknagel** [comment]
Ok, I did some testing and it seems using `add_real_directory` will work for my use case.

In the actual problem I'm facing, I would ultimately end up creating a file during the test that should not exist after the test is done, and I'd assumed that mapping the real files into the fake fs will foil that.

After a quick test, that didn't seem to be the case though. The fact that `importlib` was recognized as a proper package implies that the whole directory was copied over (or at least, that's what it looks like to `importlib.resources`), but when I created a new file in it was still as before.

That was very spooky, but also really cool to see. In case someone finds this ticket in the future, [this section in the docs](http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#access-to-files-in-the-real-file-system) asserts that behavior:

> The access to the files is by default read-only, but even if you add them using read_only=False, the files are written only in the fake system (e.g. in memory). The real files are never changed.

Thanks for writing `pyfakefs`, it makes my life a lot easier. I'm closing the issue, since my problem is solved.

**Comment by mrbean-bremen** [comment]
Glad to help! 
Not touching the real file system is actually one of the main things pyfakefs is about. The fake filesystem lives completely in memory, and mapping a real directory just means that the directory structure is copied to the fake file system, and if the content of a file in this directory is read, it is copied into the fake file on the fly. Any changes you make to the file system while in the test only affect the fake filesystem in memory.
