### ISSUE TITLE
Call os.makedirs('', exist_ok=True) will not raise FileNotFoundError in fakefs

### ISSUE THREAD

**Issue by vuryleo** [jmcgeheeiv/pyfakefs#510]
**Describe the bug**
`os.makedirs('', exist_ok=True)` will not raise `FileNotFoundError`

**How To Reproduce**
```python
import os

from pyfakefs.fake_filesystem_unittest import Patcher

with Patcher():
    print('fakefs')
    os.makedirs('', exist_ok=True)

print('os')
os.makedirs('', exist_ok=True)
```

Output:
```python
fakefs
os
Traceback (most recent call last):
  File "[redacted].py", line 10, in <module>
    os.makedirs('', exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Your enviroment**
Please run the following and paste the output.
```bash
Linux-4.15.0-55.60-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
pyfakefs 3.7.1
```

**Comment by mrbean-bremen** [comment]
Ok, thanks - strange use case, I didn't know that it behaves that way. Will have a look tonight...

**Comment by vuryleo** [comment]
The use case is that we wanna implement something like `shutil.move`. So we need to `makedir(dirname(dst), exist_ok=True)` first. 

Then we encountered that `dirname('local_file') == ''`. Boom.

At last we wish to add this case to our unit test, and discovered that pyfakefs does not complain about this.

**Comment by mrbean-bremen** [comment]
Ok, thanks - I still find the behavior a bit unexpected, and it seems not to be documented. Anyway, I will have a look later.

**Comment by mrbean-bremen** [comment]
Turned out `mkdir` has the same behavior, and that was already implemented - so not so unexpected in the end, I guess...
