### ISSUE TITLE
lstat with bytes file name fails

### ISSUE THREAD

**Issue by sagi-z** [jmcgeheeiv/pyfakefs#517]
**Describe the bug**
Using *dulwich* for git access, and it is using byte strings to access files. This normally works on python. Not working with pyfakefs.

**How To Reproduce**
```python
from pyfakefs import fake_filesystem
filesystem = fake_filesystem.FakeFilesystem()
os_module = fake_filesystem.FakeOsModule(filesystem)
filesystem.create_file('/delme')
os_module.stat('/delme')  # works
os_module.stat(b'/delme')  # works
os_module.lstat('/delme')  # works
os_module.lstat(b'/delme')  # fails
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: b'/delme'
```

**Your enviroment**
Please run the following and paste the output.
```bash
python -c "import platform; print(platform.platform())"
python -c "import sys; print('Python', sys.version)"
python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
```
Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
Python 3.7.3 (default, Nov 21 2019, 15:51:40)
[GCC 7.4.0]
pyfakefs 3.7.1

**Comment by mrbean-bremen** [comment]
Good catch - thanks!

**Comment by mrbean-bremen** [comment]
see also #325

**Comment by mrbean-bremen** [comment]
Ok, this one will take a bit longer - byte string handling is not implemented consistently at the moment, so this needs some thinking through and some restructuring. While it would be easy to fix this concrete problem, there will be similar problems with byte strings in other use cases.
