### ISSUE TITLE
Unable to extract tarball to temporary directory

### ISSUE THREAD

**Issue by noctuid** [jmcgeheeiv/pyfakefs#520]
It does not seem possible to extract a tarball (with `tarfile.extractall`) to a temporary directory (as created with `tempfile.TemporaryDirectory()`). My initial guess was to add `gettempdir()` as a real directory, but it looks like pyfakefs already does this (though I don't know whether it does this as a real or fake directory or if that matters). Anyway, I get an error like this currently: `[Errno 21] Is a directory in the fake filesystem: '/var/folders/qx/hcbbxc3x5qq2dy5z4kz4fxy00000gn/T/tmpnpt7mum2'` (this is on OSX).

Is there a workaround for this? Am I doing something incorrectly?

**Comment by noctuid** [comment]
Think this might just be user error. Will reopen if I can't figure it out.

**Comment by mrbean-bremen** [comment]
That's ok - better reporting a non-bug than not reporting a real bug!
