### ISSUE TITLE
Include fixes from pyfakefs 4.0 in a Python 2.7 compatibility version.

### ISSUE THREAD

**Issue by marcinowski** [jmcgeheeiv/pyfakefs#522]
**Is your feature request related to a problem? Please describe.**
While migrating the Python 2 legacy code using pyfakefs to Python 3 I encountered some issues related to this error (#509 and #511). I can see they'll be included in the 4.0 version which drops the support for Py2

**Describe the solution you'd like**
Is there any chance of including some of the fixes in a 3.7.2 version that will still support Python 2? 
I'm happy to assist with the 3.7.2 version if any help was needed

**Describe alternatives you've considered**
Otherwise I'd have to create a fork (I already did actually to test if the bug's fixed) but I assume more people would be blocked on this.

**Comment by mrbean-bremen** [comment]
Sure, as long as it's only bugfixes, and someone needs them in Python 2.7, we can make patch releases for 3.7. I will have a look.

**Comment by mrbean-bremen** [comment]
Ok, a new patch version [has been released](https://github.com/jmcgeheeiv/pyfakefs/releases/tag/v3.7.2) - please check.

**Comment by marcinowski** [comment]
This is brilliant work, thank you so much!
