### ISSUE TITLE
DEFAULT_TYPES cannot be used on Validators using TypeCheckers with 4.0.0

### ISSUE THREAD

**Issue by retr0h** [jmcgeheeiv/pyfakefs#523]
**Describe the bug**

Seeing the following error as soon as we started using 4.0.0.

```
self = <class 'jsonschema.validators.create.<locals>.Validator'>

    def _DEFAULT_TYPES(self):
        if self._CREATED_WITH_DEFAULT_TYPES is None:
>           raise _DontDoThat()
E           jsonschema.validators._DontDoThat: DEFAULT_TYPES cannot be used on Validators using TypeCheckers

self       = <class 'jsonschema.validators.create.<locals>.Validator'>
```

**How To Reproduce**

```
import contextlib

import flask_restx

@contextlib.contextmanager
def open_file(filename, mode='r'):
    with open(filename, mode) as stream:
        yield stream

def test_open_file(fs):
    f = 'foo.txt'
    fs.create_file(f, contents='foo')

    with open_file(f) as stream:
        assert 'foo' == stream.read()
```

**Your enviroment**
Please run the following and paste the output.
```bash
Darwin-19.3.0-x86_64-i386-64bit

Python 3.7.6 (default, Jan 15 2020, 13:46:19)
[Clang 11.0.0 (clang-1100.0.33.17)]

pyfakefs 4.0.0
```

**Comment by retr0h** [comment]
Ahh... looks to be related to `flask-restx`.

**Comment by mrbean-bremen** [comment]
We're used to get issues roght after a release, but that was really fast... can you elaborate on that? Can we reproduce this?

**Comment by retr0h** [comment]
> We're used to get issues right after a release, but that was really fast... can you elaborate on that? Can we reproduce this?

HAHAH I was working on a project which uses this project quite a bit :)

I updated the example above.  It looks as though simply importing `flask_restx` introduces the issue.

**Comment by mrbean-bremen** [comment]
I guess you would like a patch release with the fix?

**Comment by mrbean-bremen** [comment]
Can you please check if it works for you with current master?

**Comment by mrbean-bremen** [comment]
Ok, I made a new [patch release](https://pypi.org/project/pyfakefs/4.0.1/).

**Comment by retr0h** [comment]
Looks good!  Thanks for the quick reply!
