### ISSUE TITLE
pyfakefs v4 builds as py2.py3 wheel

### ISSUE THREAD

**Issue by Chris2048** [jmcgeheeiv/pyfakefs#524]
**Describe the bug**
In Pypi repos, there is wheel "pyfakefs-4.0.1-py2.py3-none-any.whl" (see https://pypi.org/simple/pyfakefs/ )
But v4 drops support for py2.

**How To Reproduce**
pip install with unpinned pyfakefs for py2.7

**Comment by mrbean-bremen** [comment]
Good point - didn't notice that! Will check this later today. Probably have to delete the current release to not be used for Python 2 install...

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - can you please remove versions 4.0.0 and 4.0.1 from PyPi? I don't have the permission for that. Otherwise these will be installed under Python 2.7.
I had removed the Python 2 qualifier, but forgot the Universal flag in the config file...

**Comment by jmcgeheeiv** [comment]
Deleted.

**Comment by mrbean-bremen** [comment]
Thanks! Closing the issue - shall be fixed now.
