### ISSUE TITLE
Deprecator overrides global warnings

### ISSUE THREAD

**Issue by iandanforth-alation** [jmcgeheeiv/pyfakefs#526]
**Describe the bug**
[This line](https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/deprecator.py#L49) attempts to restore the previous state of `warnings` which is changed on line 42. Unfortunately it assumes that the previous state is 'default' which is not always the case. If you have elsewhere set ENV variables to define your python warnings behavior this will override them.

This bug was surfaced by [this commit](https://github.com/jmcgeheeiv/pyfakefs/commit/0b8923896451001196969633a34eced249354127)
**Your environment**

Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.7.1908-Core
('Python', '2.7.15 (default, Dec 11 2018, 21:06:48) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]')
('pyfakefs', '3.7.2')

**Comment by mrbean-bremen** [comment]
Thanks - good catch! Will probably have a look tonight.
