### ISSUE TITLE
pathlib.Path(".").absolute() uses an unmocked os module

### ISSUE THREAD

**Issue by tnek213** [jmcgeheeiv/pyfakefs#527]
**Description**
`pathlib.Path(".").absolute()` uses an unmocked `os` module and I can't find a way to reload it.

**How To Reproduce**
```
from pyfakefs.fake_filesystem_unittest import TestCase

import os
import pathlib


class Test(TestCase):
    def setUp(self):
        self.setUpPyfakefs()
        os.chdir("/")

    def test_cwd(self):
        print("cwd: %s" % os.getcwd())
        dot_abs = pathlib.Path(".").absolute()
        print("dot abs: %s" % dot_abs)
        print("exists dot abs: %s" % dot_abs.exists())

```
_Prints the following when running test_cwd_

```
cwd: /
dot abs: /home/k/PycharmProjects/mytestproj/tests
exists dot abs: False
```
_While I expected:_
```
cwd: /
dot abs: /
exists dot abs: True
```
As can be seen the file system is mocked, but os.getcwd() used by the absolute() function of Path isn't and returns the real cwd.

**Enviroment**
```
Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.10-cosmic
Python 3.6.8 (default, Apr  9 2019, 04:59:38) 
pyfakefs 4.0.2
```

**Comment by mrbean-bremen** [comment]
Thanks - I will have a look.

**Comment by mrbean-bremen** [comment]
@tnek213 - Thanks for catching this - I'm amazed that this came up only now!

**Comment by tnek213** [comment]
@mrbean-bremen  Thank you! Both for the lib which seems awesome and the amazing response time!
