### ISSUE TITLE
`path` is stubbed out too aggressively

### ISSUE THREAD

**Issue by eakuefner** [jmcgeheeiv/pyfakefs#53]
I have code that looks like this:
```python
import os

from mymodule import path

print path.MyAwesomeMethod
```

When I try to unit test it inside of a `fake_filesystem_unittest.TestCase`, I get:
```
    ...
    File ".../pyfakefs/pyfakefs/fake_filesystem.py", line N, in __getattr__
  KeyError: 'MyAwesomeMethod'
```

However, changing the import in the snippet to `from mymodule import path as path_module` avoids this, which indicates that pyfakefs is stubbing out any module named `path`, where if possible it should only stub out `os.path`.

**Comment by jmcgeheeiv** [comment]
Fixed by PR #130.
