### ISSUE TITLE
Travis.CI tests not running on PRs and in master

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#539]
Since [this commit](https://github.com/jmcgeheeiv/pyfakefs/commit/7b377f32a309b086f9241610042cd6456be8a3fb) the Travis.CI builds are not running any more in master. They work fine if triggered manually, but get not triggered automatically any more.
The commit in question did not change anything (was a documentation change only), so something in the Tracis configuration must have been changed.

**Comment by mrbean-bremen** [comment]
The builds are actually running, they just don't show up in GitHub. There has been a recent issue in the Travis forum - added a respective question in [that thread](https://travis-ci.community/t/github-ci-notifiactions-from-travis-stopped-working/9238).

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv - I just switched the repo off and on again in the Travis configuration for my own fork, and it started to work again, Can you please try to do the same in your Travis settings?

**Comment by jmcgeheeiv** [comment]
I tried it and [it worked](https://travis-ci.org/github/jmcgeheeiv/pyfakefs/builds/707545434). Looks good.

**Comment by mrbean-bremen** [comment]
Thanks - whatever the reason was, it is fixed now!
