### ISSUE TITLE
Address production use?

### ISSUE THREAD

**Issue by FGasper** [jmcgeheeiv/pyfakefs#540]
Hello,

I’m wondering how feasible it is to use this module in production use to block filesystem access.

It appears, for example, that if I do:
```
if __name__ == '__main__':
    patcher = Patcher()
    patcher.setUp()
    run_program(sys.argv[1:])
    patcher.tearDown()
```
… then any attempt to access the filesystem in open() will fail with ENOENT. For a program whose sole purpose is to process an input stream and output it (along the lines of `sed`), that seems to provide a sort of “cheap” replacement for containers.

Just as a suggestion, maybe it would be nice to touch on this potential use of this module?

**Comment by mrbean-bremen** [comment]
If I understand you correctly, you just want to make sure that your program does not access the file system?  
There is one problem with that: if you have Python modules written in C that access the file system via the native C API, pyfakefs will not see these (see [limitations](http://jmcgeheeiv.github.io/pyfakefs/master/intro.html#limitations)). Maybe I didn't understand your use case correctly, though - can you elaborate a bit?

**Comment by FGasper** [comment]
No you’re correct, and yeah that’s a shortcoming of the idea. Not sure how I’d prevent loading C-based modules. <shrug>

**Comment by mrbean-bremen** [comment]
Ok - I don't know your code, and how it could access the file system accidentally, but I think that using pyfakefs for this task is probably not the best option.

**Comment by FGasper** [comment]
Oh ideally I’d love to use an OS namespace or some other tool intended as a sandboxing mechanism. The server doesn’t expose unshare, Docker, etc., though, and I don’t have admin access. CPython doesn’t seem to expose anything like deno’s I/O access controls.
