### ISSUE TITLE
Need guidance on using pkg_resources / importlib

### ISSUE THREAD

**Issue by kuwv** [jmcgeheeiv/pyfakefs#544]
Currently, I am attempting dynamically load modules from a directory path. A similar approach is pluginbase. This involves using pkg_resources and importlib.

Please provide assistance getting module loading working with pyfakefs.

Unfortunately, the only available options are to either choose dynamic modules or pyfakefs.

**Comment by mrbean-bremen** [comment]
Can you give a bit more context about your use case, please? From your description it is not clear to me what you are trying to achieve and how this is related to the fake filesystem, or to testing at all.
It would probably also help to show an example of what you are trying to do.

**Comment by kuwv** [comment]
I figured out the issue. The pkgutil was the cause and had trouble narrowing it down. I needed to skip patching it.

`@pytest.fixture(params=['fs', [[['pkgutil']]], {'indirect': True}])`
