### ISSUE TITLE
Truncating a file with os.truncate does not change its contents

### ISSUE THREAD

**Issue by ollien** [jmcgeheeiv/pyfakefs#545]
**Describe the bug**
When calling `os.truncate` on a file that has been created in the fakefs, the contents are left unchanged

**How To Reproduce**
```py
import os
from pyfakefs.fake_filesystem_unittest import Patcher


patcher = Patcher()
patcher.setUp()

PATH = "/some/path/to/test"
os.makedirs(os.path.dirname(PATH))

with open(PATH, "w") as f:
    f.write("Hello")

os.truncate(PATH, 0)
with open(PATH, "r") as f:
    print(f.read())

patcher.tearDown()
```
This should print out an empty string, but instead, it prints `Hello`. Removing `pyfakefs`, the correct behavior is observed. I separately observed this bug with the pytest fixture, as well.

**Your enviroment**
```
Darwin-19.6.0-x86_64-i386-64bit
Python 3.6.5 (default, May 18 2020, 15:15:10) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]
pyfakefs 4.1.0
```

**Comment by mrbean-bremen** [comment]
Thanks! I have to admit that I was ignorant of `os.truncate` (never used it myself), and pyfakefs has the same problem... This has not been implemented, and apparantly has not been noticed so far.
