### ISSUE TITLE
travis build reports green when there are failures

### ISSUE THREAD

**Issue by odahoda** [jmcgeheeiv/pyfakefs#56]
See e.g. https://travis-ci.org/jmcgeheeiv/pyfakefs/jobs/90503441:

    [...lots of output...]
    ======================================================================
    ERROR: testByteContents (fake_filesystem_test.FakeFileOpenTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/jmcgeheeiv/pyfakefs/fake_filesystem_test.py", line 2079, in testByteContents
        f.write(byte_fractions)
    TypeError: string argument expected, got 'bytes'
    ----------------------------------------------------------------------
    Ran 402 tests in 0.265s
    FAILED (errors=1, skipped=3)
    The command "./all_tests.py" exited with 0.
    Done. Your build exited with 0.

all_tests.py does not return a non-zero return code when there were errors in the test suite.
TestRunner.run() returns a TestResult object and you have to return 1 from the script and not result.wasSuccessful().

**Comment by jmcgeheeiv** [comment]
Nice catch.  Note that this uncovered a problem with byte strings as described in issue #63.
