### ISSUE TITLE
pyfakefs cannot fake open call if script name has specific ending

### ISSUE THREAD

**Issue by hard7** [jmcgeheeiv/pyfakefs#569]
In my project I have a file `logsio.py` and it has `open` inside. `pyfakefs` cannot fake it. The issue relates to #552

**How To Reproduce**
1. create a python file with a name that ends with `io` (example: logsio.py)
2. add a function inside the file that calls `open`
3. call this function inside a unit-test using `pyfakefs`

**Enviroment**
```bash
python -c "import platform; print(platform.platform())"
Linux-4.14.154-boot2docker-x86_64-with

python -c "import sys; print('Python', sys.version)"
Python 3.6.8 (default, Apr  8 2019, 18:17:52)
[GCC 8.3.0]

python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 4.2.1
```

**Comment by mrbean-bremen** [comment]
Thanks! I found the issue, it was indeed related to the fix for #552. I will commit the fix in a moment (if the CI tests pass). Do you need a new release version with the fix?

**Comment by hard7** [comment]
@mrbean-bremen, thanks, that was really fast! It would be great if you make a release with the fix.

**Comment by mrbean-bremen** [comment]
Ok, [done](https://pypi.org/project/pyfakefs/4.3.2/).
