### ISSUE TITLE
pyfakefs >= 3.7 raises KeyError from os.scandir instead of FileNotFoundError

### ISSUE THREAD

**Issue by FelixSchwarz** [jmcgeheeiv/pyfakefs#571]
This code raises a `KeyError` instead of a `FileNotFoundError` when using pyfakefs >= 3.7:

```python
from pyfakefs.fake_filesystem_unittest import Patcher
stubber = Patcher()
stubber.setUp()
import os
os.scandir('/invalid')
```
result:
```
Traceback (most recent call last):
  File "…/pyfakefs/fake_filesystem.py", line 2006, in get_object_from_normpath
  File "…/pyfakefs/fake_filesystem.py", line 690, in get_entry
KeyError: 'invalid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 5, in <module>
  File "…/pyfakefs/fake_filesystem.py", line 3945, in scandir
  File "…/pyfakefs/fake_scandir.py", line 180, in scandir
  File "…/pyfakefs/fake_scandir.py", line 136, in __init__
  File "…/pyfakefs/fake_filesystem.py", line 2980, in confirmdir
  File "…/pyfakefs/fake_filesystem.py", line 2060, in resolve
  File "…/pyfakefs/fake_filesystem.py", line 2011, in get_object_from_normpath
  File "…/pyfakefs/fake_filesystem.py", line 1005, in raise_os_error
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/invalid'
```

pyfakefs < 3.7 did not raise any exception so I guess that was fixed by #498 (more specifically 4f237ea78f5f943d85414274cc4de96e1e70650f) but I'm not sure why that change does not work in my example.

**Your enviroment**

```bash
$ python -c "import platform; print(platform.platform())"
Linux-5.9.8-200.fc33.x86_64-x86_64-with-fedora-33-Thirty_Three
$ python -c "import sys; print('Python', sys.version)"
Python 3.9.0 (default, Oct  6 2020, 00:00:00) 
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
$ python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 4.3.1
```

**Comment by mrbean-bremen** [comment]
It actually raises `FileNotFoundError`, it just happens while handling the `KeyError` which is raised internally. You can check this by adding an exception handler around your test code.
I also find the message in the traceback a bit confusing. While it not incorrect, I find it misleading, because the actual exception that is propagated and which I'm interested in is further down in the message, in that `During handling of the above exception` part.

**Comment by FelixSchwarz** [comment]
That is really confusing, I got the ordering totally wrong (thought the `KeyError` happened while you were internally already handling the `FileNotFoundError`). Sorry for this.

**Comment by mrbean-bremen** [comment]
No problem - as I said, I also find this confusing, and it is better to write an issue that turns out to be an non-issue, than missing a bug.
