### ISSUE TITLE
Inserting bom between write calls with utf-16

### ISSUE THREAD

**Issue by hard7** [jmcgeheeiv/pyfakefs#574]
**Describe the bug**
I found that after doing `write()` a couple of times for a utf-16 file, `read` + `split` adds `BOM` inside.

**How To Reproduce**
``` python
from pyfakefs.fake_filesystem import OSType

fname, enc = "1.txt", "utf-16"


def test_real():
    with open(fname, "wt", encoding=enc) as f:
        f.write("1")
        f.write("2")

    with open(fname, "rt", encoding=enc) as f:
        text = f.read().split("\n")[0]
        assert text == "12"
        # OK


def test_fake_1(fs):
    fs.os = OSType.LINUX
    with open(fname, "w", encoding=enc) as f:
        f.write("1")
        f.write("2")

    with open(fname, "rt", encoding=enc) as f:
        text = f.read()
        assert text == "12"
        # AssertionError: assert '1\ufeff2' == '12'
```

**Your enviroment**
Please run the following and paste the output.
```bash
>python -c "import platform; print(platform.platform())"
Windows-10-10.0.18362-SP0

>python -c "import sys; print('Python', sys.version)"
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]

>python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 4.3.2
```

**Comment by mrbean-bremen** [comment]
Interesting - thanks for the report, this is strange. In the real case, the BOM is written at the beginning, as it should be, but in the fake fs it is written _after_ the first write.  May have something to do with flushing...

**Comment by mrbean-bremen** [comment]
Ok, note to self for reference: the BOM is written on each `write`, so there are actually 2 BOMs written in the example. While reading, the first BOM is discarded (as it should), the number characters are correctly converted from utf-16, but the second BOM remains as is, as it cannot be converted.

**Comment by mrbean-bremen** [comment]
I have to think about it--this may take some time. The current implementation relies on the behavior of `BytesIO`, which in this case won't work; maybe `FileBufferIO` has to be rewritten...

**Comment by mrbean-bremen** [comment]
This was actually a good thing to do. The code has been too complicated (this was needed for Python 2 compatibility), but can now be simplified, with only Python 3 supported. Please check if you find any problems with master.
