### ISSUE TITLE
Support for pathlib.Path.link_to()

### ISSUE THREAD

**Issue by JD-Veiga** [jmcgeheeiv/pyfakefs#580]
Python 3.8 has added a new method to pathlib library: `Path.link_to()` for creating hard links (https://docs.python.org/3/library/pathlib.html#pathlib.Path.link_to). I think that it is not supported by `pyfakefs` yet (v. 4.3.3).

It would be nice to mock this method since it is an easy way to create hard links.

Maybe it would be a good idea to include a `FakeFilesystem.create_link()` method for creating hard links (similar to `FakeFilesystem.create_symlink()` for soft links).

Thank you.

**Comment by mrbean-bremen** [comment]
Good point, thank you!

**Comment by mrbean-bremen** [comment]
@JD-Veiga - shall work in master now. Do you need a released version?

**Comment by JD-Veiga** [comment]
Excellent and quick work! I have installed it from master. Thanks a lot. Happy new year!

**Comment by mrbean-bremen** [comment]
Last sensible thing I did this year ;) Happy New Year to you, too!

**Comment by JD-Veiga** [comment]
Hi,

Everything is running fine until I have updated one of the dependencies of my code this morning. The update has installed `pathlib2` and, tough I do not use directly it in my project, `pyfakefs` imports `pathlib2` now. As a consequence, `Path.link_to()` has vanished because of: https://github.com/jmcgeheeiv/pyfakefs/blob/846ec97c0efe2f819f883f26ae90247e4ea55aee/pyfakefs/fake_pathlib.py#L126

I have uninstalled `pathlib2` from my virtualenv but it is not a permanent solution for everyone everywhere.

Is there a way of adding `link_to()` to `pathlib` but not to `pathlib2`? Maybe a `_FakeAccessor` for `pathlib` and a different one for `pathlib2`? Maybe raising an exception when `pathlib2.link_to()` is called?

Thank you again.

**Comment by mrbean-bremen** [comment]
Ok, I had thought `pathlib2` is not used anymore (it is definitely not needed in Python 3.8). Making a separate accessor for `pathlib2` is probably not worth it. I could just remove the check for `pathlib2` and let it fail if you use `pathlib2` instead of `pathlib`.   
This is probably the best option, because if you want to use `link_to`, you cannot use `pathlib2`, or you would get the same exception.

**Comment by JD-Veiga** [comment]
I think so now that Python2 is in EOL but... everything comes back... in subtle ways... Thank you once again.

**Comment by mrbean-bremen** [comment]
Ok, done. Yeah, I see Python2 used still quite a bit... seems to be unkillable. Though using `pathlib2` with Python 3.8 really doesn't make much sense - `pathlib2` has stopped developing a couple of years ago, while `pathlib` is changing with each Python version.
