### ISSUE TITLE
Add support for glob.iglob

### ISSUE THREAD

**Issue by lobobabysaurus** [jmcgeheeiv/pyfakefs#59]
The [glob](https://docs.python.org/2/library/glob.html) package in python supports glob and iglob methods.  The former creates the file name array immediately, while iglob creates an iterator and lazy evaluates the sequence.  

The latter is not yet supported by this library

**Comment by timofurrer** [comment]
+1

**Comment by daidoji** [comment]
+1

**Comment by mrbean-bremen** [comment]
I just checked this, and I actually don't understand why glob is faked out at all.
As far as I can see, it is implemented using os, and will work correctly with fake_filesystem if faking os. If removing it from the faked modules and the skip names in fake_filesystem_unitest, it seems to work as expected (both glob.glob and glob.iglob). 
@jmcgeheeiv:  What did I miss?

**Comment by jmcgeheeiv** [comment]
@mrbean-bremen, you don't miss much, but could it be that the mock.patch() usage model requires fake glob.glob?

**Comment by mrbean-bremen** [comment]
Sorry, I don't really understand that - could you elaborate on this? Why would it require this?

**Comment by mrbean-bremen** [comment]
@jmcgeheeiv:  Ok, my bad - I didn't understand you mentioning the mock.patch usage model. In that model (which I didn't use, as I find the unit test usage model quite convenient), this may indeed be needed.
OTOH, it is certainly not needed in the unit test context and can savely be removed from the faked modules in the patcher, which will fix these problems at least for that usage. What do you think?

**Comment by jmcgeheeiv** [comment]
@mrbean-bremen, I agree that removing glob/iglob from skipped names in fake_filesystem_unittest would not affect the mock.patch() usage model.  The mock.patch() usage model does not even use that code.

Since you have triaged this issue with such flair and élan, could I ask you to remove  glob/iglob from skipped names, in the manner you believe most appropriate?
