### ISSUE TITLE
Don't import pandas

### ISSUE THREAD

**Issue by lieryan** [jmcgeheeiv/pyfakefs#627]
pandas is really slow to import, importing this library can add seconds to a program's startup time, which can be critical for unittest and CLI programs that needs fast startup time. 

To reproduce:

1. Setup new virtualenv (optional)
1. Install pandas and pyfakefs into your virtualenv
1. Time `python -c "import pyfakefs.fakefilesysem_unittest"`
1. Compare timing with another virtualenv where `pandas` is not installed

Expected behaviour:

pyfakefs should only import pandas or other libraries that it monkey patch, if the main application is already importing them. Just having the library installed in the system packages shouldn't cause pyfakefs to assume that the library is going to be used by the currently running application.

**Comment by mrbean-bremen** [comment]
Good point! The import of `pandas` happens to be able to patch some `pandas` functionality, which is done by default if pandas is installed. However, there is a possibility to avoid this (using `use_known_patches=False`), and in this case, there is no need for the import - I can fix this by using a local import only for the patch case.

**Comment by mrbean-bremen** [comment]
Please check in current master with `use_known_patches=False`.

**Comment by mrbean-bremen** [comment]
Closing as fixed. Please reopen if you still have issues.
