### ISSUE TITLE
(Optionally?) randomize arbitrary orders (e.g. listdir)

### ISSUE THREAD

**Issue by gsnedders** [jmcgeheeiv/pyfakefs#638]
**Is your feature request related to a problem? Please describe.**
This sorta is related to https://github.com/jmcgeheeiv/pyfakefs/issues/151; note that at this point on CPython 3.6 and Python 3.7+ we _are_ using an ordered dictionary type, given `dict` is now ordered.

But, in short, I would like to be able to test that my code doesn't rely on ordering returned by listdir.

**Describe the solution you'd like**
Either `listdir` should always shuffle its result or it should be an option when configuring pyfakefs, depending on whether we view the potential flakiness as a problem for CI systems.

**Describe alternatives you've considered**
I think those are both the obvious options. I guess the other option is "continue to return items in insertion order on recent Python versions", which feels like missing test coverage.

**Comment by mrbean-bremen** [comment]
`listdir` doesn't do any ordering in pyfakefs - it makes a list from `keys()`, which is a set-like object, but I guess the order would still be the same in subsequent calls. So shuffling the result would slightly decrease the performance, but given that `listdir` won't be used too often that shouldn't really matter.
If a test depends on the order of the result of `listdir` it is a problem with the test, so I don't think we should make that conditional, if we change it. And, as I said, the order is already not defined now, so if a test would rely on _that_ order, it would certainly be broken.

Looks like I just convinced myself that this would be a good idea...

**Comment by mrbean-bremen** [comment]
Closing as fixed - feel free to reopen if this is not what you need.
