### ISSUE TITLE
Type warning for `fs.create_file` using `pathlib.Path`

### ISSUE THREAD

**Issue by hofbi** [jmcgeheeiv/pyfakefs#648]
Thank you for this great project. I use it a lot in my tests.

If I use `fs.create_file` with a `pathlib.Path` my IDE shows me the warning _Expected type 'AnyStr', got 'Path' instead _.
Everything still works fine, so I just wanted to report that the warning exists.

According to the definition `def create_file(self, file_path: AnyStr, ...)` the function expects `AnyStr`. I guess the warning should be fixed using `AnyPath` as for the `def create_dir(self, directory_path: AnyPath, ...)`

**Comment by mrbean-bremen** [comment]
Thanks for the report! Actually the correct typing is something that is not finished yet and is on my to-do list, I just didn't get to it for some time. Especially there are several places where `AnyStr` should be replaced by `AnyPath`, but I couldn't get it to work correctly at the first try - it is not as straightforward as I would have hoped, but I will see that I can get back to it in the near future.

**Comment by hofbi** [comment]
Ok, then I guess it is related to #599

**Comment by mrbean-bremen** [comment]
Yes, correct!

**Comment by mrbean-bremen** [comment]
Turned out that fixing `create_file` was not a problem at all (contrary to most of the other methods), so I fixed this separately.
