### ISSUE TITLE
BytesWarning: Comparison between bytes and string

### ISSUE THREAD

**Issue by AliyevH** [jmcgeheeiv/pyfakefs#651]
**Describe the bug**
When using python with '-b' option it raises warning BytesWarning: Comparison between bytes and string.

**How To Reproduce**
```
from pyfakefs.fake_filesystem_unittest import Patcher
import shutil

file_name = '2.txt'

class TestCustomClass(unittest.TestCase):
    def setUp(self):
        self.patcher = Patcher()
        self.patcher.setUp()
        self.patcher.fs.create_file(file_name)

    def test_1(self):
        shutil.rmtree(file_name, ignore_errors=True)
        ... 
```
**Your environment**
```
Linux-5.4.0-90-generic-x86_64-with-Ubuntu-20.04-focal
Python 3.7.12 (default, Oct  1 2021, 10:07:43) [GCC 9.3.0]
pyfakefs 3.5.8
```

https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/fake_filesystem.py#L3204

I have fixed this issue with changing line
```if target_directory in (b'.', u'.'):``` 
to 
```if target_directory in (b'.'.decode('utf-8'), u'.'):```

**Comment by mrbean-bremen** [comment]
Thanks, but your change would defy the purpose of the line, which is to check both `bytes` and `str` variants. Your change would be the same as `if target_directory in ('.'):`, which would break the case of `target_directory == b'.')`.
I'm not sure about that warning; it could probably be avoided by using an `isinstance` check, but that is not really needed, but that would make the code unnecessary more complicated.

Also, there are a few more such warnings in the code - I will have a look at all of them, but that has not a high priority, as the code works fine despite the warning.

**Comment by AliyevH** [comment]
Thanks

**Comment by AliyevH** [comment]
@mrbean-bremen  Thanks
