### ISSUE TITLE
SyntaxError in fake_filesystem_unittest on Python 3.5

### ISSUE THREAD

**Issue by jaraco** [jmcgeheeiv/pyfakefs#659]
**Describe the bug**

Attempting to `import pyfakefs.fake_filesystem_unittest` on Python 3.5 fails with a SyntaxError:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-run-kbh4dqhl/pyfakefs/fake_filesystem_unittest.py", line 371
    CACHED_MODULES: Set[ModuleType] = set()
                  ^
SyntaxError: invalid syntax
```

**How To Reproduce**

This docker command will replicate the issue:

```
$ docker run -it jaraco/multipy-tox py -3.5 -m pip-run pyfakefs -- -c 'import pyfakefs.fake_filesystem_unittest'
Collecting pyfakefs
  Downloading pyfakefs-4.5.0-py3-none-any.whl (186 kB)
     |████████████████████████████████| 186 kB 3.0 MB/s 
Installing collected packages: pyfakefs
Successfully installed pyfakefs-4.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-run-kbh4dqhl/pyfakefs/fake_filesystem_unittest.py", line 371
    CACHED_MODULES: Set[ModuleType] = set()
                  ^
SyntaxError: invalid syntax
```

**Your environment**

[jaraco/multipytox](https://github.com/jaraco/multipy-tox/) is an Ubuntu image with multiple Pythons installed and tools like pylauncher and pip-run.

```bash
$ docker run -it jaraco/multipy-tox py -3.5 -m pip-run -q pyfakefs -- -c "import platform; print(platform.platform()); import sys; print('Python', sys.version); from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
Linux-5.10.76-linuxkit-x86_64-with-Ubuntu-20.04-focal
Python 3.5.10 (default, Feb 20 2021, 21:50:32) 
[GCC 9.3.0]
pyfakefs 4.5.0
```

**Comment by jaraco** [comment]
It looks like #615 acknowledged this issue, but did not correct the issue for 4.5.0. In that case, I believe the proper fix would be to yank 4.5.0 from PyPI. That will leave 4.5.0 published and available for download but not available unless requested explicitly (so it won't be discovered by Python 3.5).

**Comment by jaraco** [comment]
This issue came up in `importlib_metadata`, where a new release of v2.1.2 was being tested for release in [this job](https://github.com/python/importlib_metadata/runs/4912865108?check_suite_focus=true), but failed due to this issue.

**Comment by mrbean-bremen** [comment]
Thanks, good point.
@jmcgeheeiv: can you please yank 4.5.0 from PyPi? I don't have the rights.

**Comment by jmcgeheeiv** [comment]
Version 4.5.0 yanked. Thank you for your report.

**Comment by jaraco** [comment]
Excellent. I can confirm [that fixes the job too](https://github.com/python/importlib_metadata/actions/runs/1736284434).

**Comment by jmcgeheeiv** [comment]
Very good. If you are satisfied with the fix, please close this issue.
