### ISSUE TITLE
binary mode doesn't take an encoding argument

### ISSUE THREAD

**Issue by yaythomas** [jmcgeheeiv/pyfakefs#664]
The actual `open()` function does not allow you to pass an encoding when in binary mode:

```
>>> open('filename', 'wb', encoding='utf-8')
ValueError: binary mode doesn't take an encoding argument
>>> open('arb', 'b', encoding='utf-8')
ValueError: binary mode doesn't take an encoding argument
```

Assuming this is not an intentional divergence from `open()` behaviour, I think the fix would be to insert this:

```python
if binary and encoding:
    raise ValueError("binary mode doesn't take an encoding argument")
```

just after here:
https://github.com/jmcgeheeiv/pyfakefs/blob/4dc8615957dadfc64d6a8f864ee93c7c65da38b5/pyfakefs/fake_filesystem.py#L5574

Before I prepare a PR, I thought I'd ask whether you think this is suitable first?

P.S this is an AMAZING project - it's my favourite new thing in my tool-belt! Thank you so much for all the work and care that went into this complex wonderful beast!

**Comment by mrbean-bremen** [comment]
Thanks :) And good catch - no this wasn't meant to diverge, we just overlooked it.
You mean if its a suitable first PR? Sure, go ahead!

**Comment by yaythomas** [comment]
By suitable I meant more whether my suggested simplistic fix was comically naive and unaware of other complexities :-)

PR incoming. . .

**Comment by mrbean-bremen** [comment]
The test coverage is pretty ok here, so it is not very likely that you will break something if the tests pass. And I guess you will add a test of your own for the change...

**Comment by mrbean-bremen** [comment]
Thank you, nice work!

**Comment by yaythomas** [comment]
Pleasure was mine! Thanks for a smooth contribution experience!
