### ISSUE TITLE
version 4.6.1 issue with opener

### ISSUE THREAD

**Issue by yaronbenezra** [jmcgeheeiv/pyfakefs#689]
Hi,

In the latest version due to "Add support for opener in open() #688" commit we fail to run a tests on python version 3.9 cause:
![image](https://user-images.githubusercontent.com/84681092/178951642-45275d42-94ea-4ad8-b7fe-ffff4fdd1848.png)

seems like _OpenModes is now object instead of int

**Comment by mrbean-bremen** [comment]
Thanks for the report - interesting. `_OpenModes ` has not changed, the difference is that the `opener` call is now executed here. Looks like the flags have to be converted before passing them into the call - this was not a problem with the tested code, but obvioulsy I didn't test this usage.

Do you have a simple reproducable example, that shows this behavior? This would help to find the problem faster. I have to make another patch release anyway...

**Comment by mrbean-bremen** [comment]
Never mind, this was a clear mistake. Never a good idea to rush a patch out without adequate tests...

**Comment by mrbean-bremen** [comment]
Shall be fixed in version 4.6.2.

**Comment by yaronbenezra** [comment]
i will test and update tomorrow

**Comment by yaronbenezra** [comment]
Hi
I have tested it and now we fail on :
 filesystem.add_real_directory
![image](https://user-images.githubusercontent.com/84681092/179492627-f36a9b8c-9c02-4f9c-b563-6af02ecf4160.png)
hope you can help, thanks in advanced

**Comment by mrbean-bremen** [comment]
Ok, that's unfortunate. I will have a look tonight - it would be nice if you could add a test that can reproduce this.

**Comment by yaronbenezra** [comment]
I run my test and a good version that all work for me is: 4.5.6
I will try to write the test  today so I can upload it, I can't expose the company code so I need to write a new test
