### ISSUE TITLE
Infinite loop in test with version 4.6.2

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#691]
This is a spin-off of #689.

@yaronbenezra commented:

Hi
I have tested it and now we fail on :
*filesystem.add_real_directory*
![image](https://user-images.githubusercontent.com/84681092/179492627-f36a9b8c-9c02-4f9c-b563-6af02ecf4160.png)
hope you can help, thanks in advanced

I run my test and a good version that all work for me is: 4.5.6
I will try to write a test today so I can upload it for you(I can't expose company code so I need to write a new test).

**Comment by mrbean-bremen** [comment]
Ok, from the callstack it looks as if you are emulating a Posix system under Windows. Is this correct? How do yo setup your test? Of course, a reproducible example test would still be the best way to understand this.

**Comment by mrbean-bremen** [comment]
@yaythomas - I'm going to close this, as it looks like it is related to #692, which is fixed now, and there is not enough information to reproduce this. Feel free to reopen it if it still happens in version 4.6.3 and you have more information to reproduce it.

**Comment by yaythomas** [comment]
I think you might have tagged me accidentally there @mrbean-bremen - just letting you know in case intended recipient not in the loop otherwise 😄.

**Comment by mrbean-bremen** [comment]
@yaythomas - sorry for that - I just hit the first match that started with "ya" 😊 

@yaronbenezra - that was for you, of course!
