### ISSUE TITLE
pyfakefs cannot fake open calls if module has specific names

### ISSUE THREAD

**Issue by marnanel** [jmcgeheeiv/pyfakefs#708]
**Describe the bug**

If a module under test has a name listed in `FakeIoModule.skip_names`, then `open` calls are never faked.

For example, one of these names is `io.py`. Issue #569 solved the same problem for names ending with that string, such as `logsio.py`. But a submodule within any package may reasonably have the exact name `io.py`, and this will trigger the behaviour nonetheless.

**How To Reproduce**

Example code is in https://github.com/marnanel/pyfakefs-issue . Running the test in that repo gets you a `FileNotFoundError` when the code in `wombat.io` attempts to access the file created in the fake filesystem by the test.

**Environment**
```
Linux-5.10.0-16-amd64-x86_64-with-glibc2.31
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
pyfakefs 4.5.4
```

**Comment by marnanel** [comment]
The workaround is

```
open.__self__.skip_names.remove('io')
```

where "io" is the name of the module that's causing the trouble.

**Comment by mrbean-bremen** [comment]
Thanks - that is indeed a shortcoming of pyfakefs, it just never came up before. I think it is a valid use case and we see how this can be avoided (probably by skipping modules not solely based on their name).
I'm not sure when I will get to it - currently short on free time, and also have a couple of other things to finish - by I will look into it.

**Comment by mrbean-bremen** [comment]
@marnanel - should be fixed in master now - please check if it works for you!

**Comment by marnanel** [comment]
Working fine here. Thanks for the fast response!
