### ISSUE TITLE
ignore_errors and onerror parameters are ignored in FakeShutilModule.rmtree

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#72]
An easy fix could be something like this:

    def rmtree(self, path, ignore_errors=False, onerror=None):
        try:
            self.filesystem.RemoveObject(path)
        except IOError:
            if not ignore_errors:
                if onerror:
                    onerror(rmtree, path, sys.exc_info())
                raise

**Comment by mrbean-bremen** [comment]
Reopening - the related code shall be reverted (accidental merge) and re-submitted correctly afterwards.

**Comment by jmcgeheeiv** [comment]
Please verify whether this can be closed.

**Comment by mrbean-bremen** [comment]
Works fine - thanks also for the corrections.
Closing this one.
