### ISSUE TITLE
Support for st_blocks field

### ISSUE THREAD

**Issue by albrycht** [jmcgeheeiv/pyfakefs#722]
**Is your feature request related to a problem? Please describe.**
I have a code that crawls filesystem. One of most important field that I read from stat is `st_blocks` (see: https://docs.python.org/3/library/os.html#os.stat_result.st_blocks)
Without that field my code fails with: `AttributeError: 'FakeStatResult' object has no attribute 'st_blocks'`

I know that theoretically, it doesn't have to be there but I haven't met POSIX filesystem that wouldn't have that field yet. 

**Describe the solution you'd like**
Add `st_blocks` field to FakeStatResult.

**Describe alternatives you've considered**
The only alternative I see right now is not to use pyfakefs and mock os calls by myself.

**Comment by mrbean-bremen** [comment]
I guess it would be enough if the result would just be something like `st_size / 512 + 1`?

**Comment by albrycht** [comment]
Result should be int so I would suggest `st_size // 512 + 1`.

**Comment by mrbean-bremen** [comment]
Implemented in master now - please check!
