### ISSUE TITLE
FakePathModule.__getattr__ raises KeyError instead of NameError

### ISSUE THREAD

**Issue by timdiels** [jmcgeheeiv/pyfakefs#79]
Things like hasattr only work when NameError is raised, not KeyError, here's a hotfix as example:

```python
from pyfakefs.fake_filesystem import FakePathModule
def _fake_os_path_getattr(self, name):
    return getattr(self._os_path, name)
FakePathModule.__getattr__ = _fake_os_path_getattr
```

**Comment by jmcgeheeiv** [comment]
I'm sorry, I'm not quite clear about your example.

**Comment by timdiels** [comment]
I had a module that calls `hasattr(os.path, '__path__')`. The current `FakePathModule.__getattr__` raises a `KeyError` and `hasattr` only catches `NameError` so instead of returning `False`, `hasattr` raises `KeyError`. Switching from [this](https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/fake_filesystem.py#L1187) to `getattr` would fix that.
