### ISSUE TITLE
Fake "normpath" doesn't replace forward slash with backslash on Windows

### ISSUE THREAD

**Issue by CausticYarn** [jmcgeheeiv/pyfakefs#91]
Per the documentation for os.path.normpath, "On Windows, it converts forward slashes to backward slashes." However, the fake normpath does not perform this conversion on Windows.

**Comment by jmcgeheeiv** [comment]
In the last few weeks a tremendous amount of work has been done on Windows compatibility.

Could I ask you to clone the master branch here on GitHub and try that?  I think you and other Windows users will be very pleased.

**Comment by mrbean-bremen** [comment]
Just for reference - the fasted way to do this under Windows is:
pip install https://github.com/jmcgeheeiv/pyfakefs/archive/master.zip

**Comment by jmcgeheeiv** [comment]
@mrbean-bremen and I are very interested in your impression of the latest pyfakefs.

**Comment by CausticYarn** [comment]
Thanks so much for the quick turnaround on this issue! I use pyfakefs very heavily in my unit tests, but it's part of an automated deployment system that pulls from pypi. At the moment unfortunately I don't have any cycles free to test a build, but when a new release version is available I will certainly deploy and test.

**Comment by mrbean-bremen** [comment]
If you are still interested - @jmcgeheeiv just made a new pypi release (2.9).

**Comment by jmcgeheeiv** [comment]
Come on @CausticYarn, if you close this pyfakefs is down to zero bugs!  It's an emotional thing, you see.

**Comment by mrbean-bremen** [comment]
Issue is fixed, unit-tested and released - closing.
