### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by uiii** [jmcgeheeiv/pyfakefs#98]
Hi, your implementation of `os.makedirs` doesn't reflect the official python 3 API https://docs.python.org/3/library/os.html#os.makedirs. Should accept `exist_ok` argument as well.

**Comment by jmcgeheeiv** [comment]
Indeed this optional argument was added in Python 3.2.

**Comment by jmcgeheeiv** [comment]
Added `exist_ok` plus additional test, merged to master.
